
			<!-- /section:basics/sidebar -->
			<div class="main-content">
                	      
				<div class="main-content-inner">
                <link href="<?php echo $this->basePath('css/modal.css'); ?>" rel="stylesheet">   
                
    
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index')); ?>">Home</a>
							</li>

							<li class="active">Relatório simplificado de cumprimento do objeto</li>
						</ul><!-- /.breadcrumb -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">

						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Relatório simplificado de cumprimento do objeto
							</h3>
						</div><!-- /.page-header -->
 
						<div id="mascara"></div>

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">                      
									<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>								         
								    <script type="text/javascript">
									$(document).ready(function() {
								        $('#estado').change(function() {
									        var area_id = $('#estado').val();		            
								    		var ajax_url = "/uab/projetos/atividade-ptc/get-submetas/"+area_id;
								    		
								    		 $.ajax({
								 	            type: "POST",
								 	            url: ajax_url,
								 	            data: "area="+area_id,
								 	            success: function(msg){ 		
								 	                $("#submeta_id").html(msg);
								 	        	}
								 	     	});     	   
								        });
									});
								   
								    </script>   
     
                                 
                                    <form class="form-horizontal" role="form" action="<?php echo $this->url('relatorio-cumprimento-objeto/consulta', array('action'=>'consulta')); ?>" method="post">
								
									<div class="form-group" id="conteudo">
                                    
                                    
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Área</label>

										<div class="col-sm-9">

                                            <select  class="form-control"  name="area_id" id="estado"  >
                                            <option value=""></option>
                                            <?php foreach ($areas as $area){ ?>  
                                            <option value="<?php echo $area['id']; ?>"><?php echo ($area['descricao']); ?></option>
                                            <?php } ?>	  
                                            </select>
										</div>
									<br /><br /><br />

                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Submeta</label>
                                <div class="col-sm-9">
                                
                                <div id="nucleo"></div>
                                            <select  class="form-control"  name="submeta_id" id="submeta_id"  >
                                            </select>
                                </div>
                                </div>
                                
                                	<div class="form-group" id="conteudo">
                                    
                                    
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp;</label>

										<div class="col-sm-9">
                                <button class="btn btn-info" type="submit">
												
												Ver
											</button>
                                            </div></div>
                                    <hr />									
									
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
									</div><!-- /.span -->
								</div><!-- /.row -->
                                
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->

			</div><!-- /.main-content -->
