			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try {
								ace.settings.check('breadcrumbs', 'fixed')
							} catch (e) {}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action' => 'index')); ?>">Home</a>
							</li>

							<li class="active">Assinar relatório de atividade mensal</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">

						<div class="page-header">
							<h1>
								Assinar relatório de atividade mensal
							</h1>
						</div>


						<script type="text/javascript">
							var rec = "O preenchimento do campo é obrigatório";

							function aviso($campo) {
								if ("" == document.meuform.campo.value) {
									document.write("preenchimento obrigatorio");
									return false;
								} else {
									return true;
								}
							}
						</script>
						<?
						function br2nl($string)
						{
							return preg_replace('/\<br(\s*)?\/?\>/i', "\n", $string);
						}
						?>
						<form name="meuform" class="form-horizontal" role="form" action="<?php echo $this->url('usuario-atividade/assinar', array('action' => 'assinar', 'id' => $id)); ?>" method="post">
							<input type="hidden" style="width:100%" value="<?php echo md5(strip_tags($usuario_atividade->texto)) . "|" . base64_encode($dados_sessao_atual->id); ?>|" name="hash">
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome do Projeto: </label>
								<div class="col-sm-9">
									<DIV class="col-xs-10 col-sm-8"><strong><?php echo ($projeto->descricao); ?></strong></DIV>
								</div>
							</div>


							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Disciplina:</label>
								<div class="col-sm-9">
									<DIV class="col-xs-10 col-sm-8"><strong><?php echo ($usuario_atividade->disciplina); ?></strong></DIV>


								</div>
							</div>

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Período:</label>
								<div class="col-sm-9">
									<DIV class="col-xs-10 col-sm-8"><strong><?php echo date("d/m/Y", strtotime($usuario_atividade->data_inicial)); ?> à <?php echo date("d/m/Y", strtotime($usuario_atividade->data_final)); ?></strong></DIV>


								</div>
							</div>


							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Senha:</label>
								<div class="col-sm-9">
									<input <? if ($usuario_atividade->assinatura_colaborador) {
												echo "disabled";
											} ?> type="password" name="password" value="" class="col-xs-10 col-sm-5" required />

								</div>
							</div>


							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> </label>
								<div class="col-sm-9">
									<? if ($_GET['erro'] == 1) { ?>
										<div class="alert alert-danger col-md-4">
											Erro ao assinar documento.
										</div>
									<? } ?>

								</div>
							</div>





							<div class="clearfix form-actions">
								<? if ($usuario_atividade->assinatura_colaborador == "") { ?>
									<div class="col-md-offset-3 col-md-9">
										<button class="btn btn-info" type="submit">
											<i class="ace-icon fa fa-check bigger-110"></i>
											Salvar
										</button>
									</div>
								<? } else { ?>
									<div class="col-md-offset-3 col-md-9">
									Documento já assinado
									</div>
								<? } ?>
							</div>

						</form>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.page-content -->
			</div>
			</div><!-- /.main-content -->