
			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Alterar senha</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Alterar senha
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->
                        
						<div class="row">
							<div class="col-xs-12">                   

								<!-- PAGE CONTENT BEGINS -->
								<form class="form-horizontal" id="changepasswordform" name="changepasswordform"  role="form" action="" method="post"  onSubmit="validateForm(); return false;" action="<?php echo $this->url('login', array('action' => 'logar')); ?>"  enctype="application/x-www-form-urlencoded">
																			
									<!-- #section:elements.form -->
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nova senha </label>

										<div class="col-sm-9">
                                        <input type="password" name="senha1" id="senha1" class="form-control" class="col-xs-10 col-sm-5"  placeholder="Senha" required="required"/>

										</div>
									</div>
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Repetir a senha </label>

										<div class="col-sm-9">
                                        <input type="password" name="senha2" id="senha2" class="form-control" class="col-xs-10 col-sm-5"  placeholder="Confirme a senha" required="required" />											
										</div>
									</div>
                                    
                                      <div class="form-group">
										<div class="clearfix form-actions">
											<div class="col-md-offset-3 col-md-9">											
												<button class="btn btn-info" value="Submit"  type="submit" id="btnsubmit">
													<i class="ace-icon fa fa-check bigger-110"></i>
													Salvar
												</button>
											</div>
										</div>
									</div>
                        		</form>
									
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div><!-- /.main-content-inner -->
			</div><!-- /.main-content -->
			
			<script>

function validateForm(){
	var segundos = 5;

	
	var senha1 = document.getElementById("senha1").value;
	var senha2 = document.getElementById("senha2").value;

		if(senha1 != senha2){
		    alert('A nova senha e a confirmação da senha devem ser iguais!');
	    	return false;	
		}else{
		       $('#changepasswordform').submit(); 
		       return true;			
		}


}

</script>


