<?php 

use Zend\Session\Container;

$msg = "Não foi possivel fazer login!";

?>
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>Login</title>

		<meta name="description" content="User login page" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="<?php echo $this->basePath('public/css/bootstrap.css'); ?>" />
		<link rel="stylesheet" href="<?php echo $this->basePath('public/css/font-awesome.css'); ?>" />

		<!-- text fonts -->
		<link rel="stylesheet" href="<?php echo $this->basePath('public/css/ace-fonts.css'); ?>" />

		<!-- ace styles -->
		<link rel="stylesheet" href="<?php echo $this->basePath('public/css/ace.css'); ?>" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="assets/css/ace-part2.css" />
		<![endif]-->
		<link rel="stylesheet" href="<?php echo $this->basePath('public/css/ace-rtl.css'); ?>" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="assets/css/ace-ie.css" />
		<![endif]-->

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="assets/js/html5shiv.js"></script>
		<script src="assets/js/respond.js"></script>
		<![endif]-->
	</head>

	<body class="login-layout">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">

							<h1>
									<!--i class="ace-icon fa fa-leaf green"></i-->
									<span class="red" id="id-text2" style="font-size:18px; font-weight:bolder">
                                     Sistema de Gestão de Projetos<br>
                                    Universidade Aberta do Brasil
                                    </span>
								</h1>
								<h4 class="green" id="id-company-text" style="font-size:12px;">UFMT</h4>
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header red lighter bigger">
												<i class="ace-icon fa fa-key"></i>
												Recuperar Senha</h4>

											<div class="space-6"></div>
											<p>
												Informe seu cpf
											</p>
                                            <?php					                            
					                            if(isset($_GET['erro'])){
					                            	if($_GET['erro'] == 1){
					                        ?>
                                            <p style="color:red">CPF nao encontrado</p>
											<?php 	}else{
					                            		if($_GET['erro'] == 2){
					                            			?>
                                            <p style="color:green">Verifique seu email!</p>
					                            			<?php 
					                            		}
				                            		}
														
				                            	}
				                            	?>

                                            <form  id="loginform" class="" role="form" action="<?php echo $this->url('login', array('action' => 'recuperarsenha')); ?>" method="post"  enctype="application/x-www-form-urlencoded">
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="text" name="cpf" class="form-control" placeholder="Apenas números" />
															<i class="ace-icon fa fa-envelope"></i>
														</span>
													</label>

													<div class="clearfix">
														<button type="submit" class="width-35 pull-right btn btn-sm btn-danger">
															<i class="ace-icon fa fa-lightbulb-o"></i>
															<span class="bigger-110">Ok!</span>
														</input>
													</div>
												</fieldset>
											</form>

										</div><!-- /.widget-main -->

										<div class="toolbar clearfix">

											<!--div>
												<a href="#" data-target="#signup-box" class="user-signup-link">
													I want to register
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div-->
										</div>
									</div><!-- /.widget-body -->
								</div><!-- /.login-box -->

								

										<div class="toolbar center">
											<a href="<?php echo $this->url('login', array('action' => 'index')); ?>" class="back-to-login-link">
												<i class="ace-icon fa fa-arrow-left"></i>
												Voltar para o login
											</a>
										</div>
									</div><!-- /.widget-body -->
								</div><!-- /.signup-box -->
							</div><!-- /.position-relative -->

						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
		<script type="text/javascript">
			window.jQuery || document.write("<script src='<?php echo $this->basePath('public/js/jquery.js'); ?>'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='assets/js/jquery1x.js'>"+"<"+"/script>");
</script>
<![endif]-->
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath('public/js/jquery.mobile.custom.js'); ?>'>"+"<"+"/script>");
		</script>

		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			jQuery(function($) {
			 $(document).on('click', '.toolbar a[data-target]', function(e) {
				e.preventDefault();
				var target = $(this).data('target');
				$('.widget-box.visible').removeClass('visible');//hide others
				$(target).addClass('visible');//show target
			 });
			});
			
			
			
			//you don't need this, just used for changing background
			jQuery(function($) {
			 $('#btn-login-dark').on('click', function(e) {
				$('body').attr('class', 'login-layout');
				$('#id-text2').attr('class', 'white');
				$('#id-company-text').attr('class', 'blue');
				
				e.preventDefault();
			 });
			 $('#btn-login-light').on('click', function(e) {
				$('body').attr('class', 'login-layout light-login');
				$('#id-text2').attr('class', 'grey');
				$('#id-company-text').attr('class', 'blue');
				
				e.preventDefault();
			 });
			 $('#btn-login-blur').on('click', function(e) {
				$('body').attr('class', 'login-layout blur-login');
				$('#id-text2').attr('class', 'white');
				$('#id-company-text').attr('class', 'light-blue');
				
				e.preventDefault();
			 });
			 
			});
		</script>
	</body>
</html>
