			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}				
						</script>
                        
                        <ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Meus Projetos</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h1>
								Meus projetos
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th width="90%">Nome do projeto</th>
                                                    <th>Opções</th>													
												</tr>
											</thead>

											<tbody>
                                                  <?php foreach ($usuarios_projetos as $usuario_projeto_id => $projeto_id){ ?>
												<tr>
													
													<td>
														<?php echo $projetos[$projeto_id]; ?>
													</td>
													<td>
														<div class="hidden-sm hidden-xs btn-group">                                                      
															<a  href="<?php echo $this->url('usuario-atividade/add', array('action'=>'add', 'projeto_id' => $projeto_id)); ?>" class="btn btn-xs btn-success">
																<i class="ace-icon fa fa-check bigger-120"></i>
															</a>       
															                                                     
                                                            <a  href="<?php echo $this->url('usuario-atividade/consulta', array('action'=>'consulta', 'projeto_id' => $projeto_id)); ?>" class="btn btn-xs btn-success">
																<i class="ace-icon fa fa-edit bigger-120"></i>
															</a>
                                                            
                                                             <a  href="<?php echo $this->url('relatorio-colaborador/ver-relatorio-colaborador-projeto', array('action'=>'ver-relatorio-colaborador-projeto', 'id' => $usuario_projeto_id)); ?>" class="btn btn-xs btn-default">
                                                            <span class="white"><i class="ace-icon fa fa-print bigger-120"></i></span>
                                                            </a>
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
																	<li>
																		<a href="" class="tooltip-info" data-rel="tooltip" title="Ver">
																			<span class="blue">
																				<i class="ace-icon fa fa-check bigger-120"></i>
																			</span>
																		</a>
																	</li>
                
                													<li>
																		<a href="" class="tooltip-info" data-rel="tooltip" title="Ver">
																			<span class="blue">
																				<i class="ace-icon fa fa-edit bigger-120"></i>
																			</span>
																		</a>
																	</li>                                                                    
                                                                    
																	<li>
																		<a href="" class="tooltip-info" data-rel="tooltip" title="Ver">
																			<span class="blue">
																				<i class="ace-icon fa fa-print bigger-120"></i>
																			</span>
																		</a>
																	</li>
																	
																</ul>
															</div>
														</div>
													</td>
												</tr>
                                                <?php } ?>												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div>