
			<!-- /section:basics/sidebar -->
			<div class="main-content">
                              <script language="Javascript">
function confirmacao(id) {
     var resposta = confirm("Deseja remover esse registro?");
 
     if (resposta == true) {
          window.location.href = "<?=$root;?>remover.php?t=atividade_projeto&redirect=ver-projeto/<?=$_GET['p1'];?>&id="+id;
     }
}
</script> 	       	      
	
        	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?=$root;?>">Home</a>
							</li>

							<!--li class="active">Projetos</li-->
						</ul><!-- /.breadcrumb -->

						<!-- #section:basics/content.searchbox ->
						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- /.nav-search -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Colaborador: <strong><?=$usuario->nome;?></strong>
								

							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								
                                
                             

								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    <form action="" method="post">
									<input type="hidden" name="flag" value="1" />
                                    <table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th class="center">
														#
													</th>
													<th width="60%">Descrição</th>
                                                    <th>Data Inicial</th>
                                                    <th>Data Final</th>

													
												</tr>
											</thead>

											<tbody>
                                                  
                                                <?php 
												
												
												
												foreach($atividades as $atividade){	?>
                       							
                                                
                                                  
												<tr>

                                                    <td>
                                                    <label class="pos-rel">
                                                   
                                                    <input name="atividade_id[]" <? if(in_array($atividade['id'], $atividade_projeto_usuario1)){ echo "checked"; } ?> value="<?=$atividade['id'];?>" type="checkbox" class="ace" />
                                                    <span class="lbl"></span>
                                                    </label>
                                                    </td>
													
													<td>
													<?=$atividade['descricao'];?>
													</td>
                                                  
                                                  <td>
														<? echo  implode("-",array_reverse(explode("-",$atividade['dt_inicial']))); ?> </td>
                                                        <td>
														<? echo  implode("-",array_reverse(explode("-",$atividade['dt_final'])));?>
													</td>
												</tr>
                                                <?  } ?>

												
											</tbody>
										</table>
                                        <input type="submit" value="salvar" />
									</div><!-- /.span -->
								</div><!-- /.row -->

								</form>
								<div class="row">
									<div class="col-xs-12">
										
											<!--div class="modal-footer no-margin-top">
												

												<ul class="pagination pull-right no-margin">
													<li class="prev disabled">
														<a href="#">
															<i class="ace-icon fa fa-angle-double-left"></i>
														</a>
													</li>

													<li class="active">
														<a href="#">1</a>
													</li>

													<li>
														<a href="#">2</a>
													</li>

													<li>
														<a href="#">3</a>
													</li>

													<li class="next">
														<a href="#">
															<i class="ace-icon fa fa-angle-double-right"></i>
														</a>
													</li>
												</ul>
											</div-->
										</div><!-- /.modal-content -->
									</div><!-- /.modal-dialog -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
