			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Editar projeto</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Editar projeto
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">

								<!-- PAGE CONTENT BEGINS -->
								<form id="projeto_edit" name="projeto_edit" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php echo $this->url('projeto/edit', array('action' => 'edit', 'id'=> $projeto->id));?>" role="form" class="form-horizontal form-label-left">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Área: </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="form-field-1" disabled="disabled" value="<?php echo $areas[$projeto->area_id]; ?>" class="col-xs-10 col-sm-9" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Núcleo: </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="form-field-1" disabled="disabled" value="<?php echo ($nucleos[$projeto->nucleo_id]); ?>" class="col-xs-10 col-sm-9" required />
                                        </div>
                                    </div>

                                    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>
                                    <script type="text/javascript">
                                        //										$(document).ready(function() {
                                        //
                                        //									        $('#estado').change(function() {
                                        //									    		var ajax_url = "/tce/convenio19/projeto/listacidade/"+$('#estado').val();
                                        //									    		//var ajax_url = "/tce/convenio19/projeto/listacidade/"+$('#estado').val();
                                        //									    		 $.ajax({
                                        //									 	            type: "POST",
                                        //									 	            url: ajax_url,
                                        //									 	            data: "area="+$(this).val(),
                                        //									 	            success: function(msg){
                                        //									 	                $("#nucleo_id").html(msg);
                                        //									 	        	}
                                        //									 	     	});
                                        //									        });
                                        //										});

                                        window.onload = function() {
                                            $(document).ready(function () {
                                                $('#estado').change(function() {
                                                    $.post( "/tce/convenio22/projeto/listacidade/"+$('#estado').val(), { area: ""+$('#estado').val()},function(data){
                                                        $("#nucleo_id").html(data);
                                                    } );

                                                });
                                            });
                                        };

                                        function exibe(id) {
                                            if(document.getElementById(id).style.display=="none") {
                                                document.getElementById(id).style.display = "inline";
                                            } else {
                                                document.getElementById(id).style.display = "none";
                                            }
                                        }
                                    </script>




                                    <div class="form-group" >
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">&nbsp;</label>

                                        <div class="col-sm-9">
                                            <a href="#" onclick="javascript: exibe('conteudo');">Clique para alterar</a></div></div>




                                    <div class="form-group" id="conteudo" style="display: none;">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Área</label>

                                        <div class="col-sm-9">

                                            <select  class="form-control"  name="area_id" id="estado" >
                                                <option value=""></option>
                                                <?php
                                                foreach($areas as $key => $descricao){
                                                    ?>
                                                    <option value="<?php echo $key; ?>"><?php echo $descricao; ?></option>
                                                <?php 	}
                                                ?>
                                            </select>
                                        </div>
                                        <br /><br /><br />

                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Núcleo</label>
                                        <div class="col-sm-9">
                                            <div id="nucleo"></div>
                                            <select  class="form-control"  name="nucleo_id" id="nucleo_id"></select>
                                        </div>
                                    </div>
              						
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Projeto Pai</label>

									<div class="col-sm-9">

                                            <select  class="form-control"  name="pai" >
                                            <option value=""></option>
                                            <?php
                                            		foreach($projetospai as $pai){
                                            ?>
											<option  <?php if ($pai['id'] == $projeto->pai){ ?> selected="selected" <? } ?> value="<?php echo ($pai['id']); ?>"><?=$pai['area']?> - <?php echo $pai['descricao']; ?></option>
                                            <?php 	} ?>	  
                                            </select>
										</div>
									</div>
              
									<!-- #section:elements.form -->
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome do projeto </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="descricao" value="<?php echo ($projeto->descricao);?>" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Nome do coordenador do projeto EPE (UFMT)</label>

										<div class="col-sm-9">

                                            <select  class="form-control"  name="coordenador_id" >
                                            <option value=""></option>
                                            <?php
                                            		foreach($usuarios as $usuario){
                                            			if($usuario['id'] == $projeto->coordenador_id){
                                            ?>
                                            				<option selected="selected" value="<?php echo ($usuario['id']); ?>"><?php echo $usuario['nome']; ?></option>
                                            				<?php 
                                            			}else{
                                            ?>
                                            		<option value="<?php echo ($usuario['id']); ?>"><?php echo $usuario['nome']; ?></option>
                                            <?php 		}
                                            		}
                                            ?>	  
                                            </select>
										</div>
									</div>
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome do coordenador no TCE/MPC </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="coordenador_tce_mpc" value="<?php echo ($projeto->coordenador_tce_mpc);?>"  class="col-xs-10 col-sm-9"  />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Tipo</label>

										<div class="col-sm-9">

                                            <select  class="form-control"  name="tipo_projeto" >
                                            <option value=""></option>
                                            <?php
                                            		foreach($tipos_projeto as $tipo_projeto){
                                            			if($tipo_projeto['id'] == $projeto->tipo_projeto){
                                            ?>
                                            				<option selected="selected" value="<?php echo ($tipo_projeto['id']); ?>"><?php echo $tipo_projeto['descricao']; ?></option>
                                            				<?php 
                                            			}else{
                                            ?>
                                            		<option value="<?php echo ($tipo_projeto['id']); ?>"><?php echo $tipo_projeto['descricao']; ?></option>
                                            <?php 		}
                                            		}
                                            ?>	  
                                            </select>
										</div>
									</div>
                                    
                                    
        
        
                                <script language="JavaScript" type="text/javascript">
   function mascaraData(campoData){
              var data = campoData.value;
              if (data.length == 2){
                  data = data + '/';
                  document.forms[0].data_inicio.value = data;
      return true;              
              }
              if (data.length == 5){
                  data = data + '/';
                  document.forms[0].data_inicio.value = data;
                  return true;
              }
         }

   function mascaraData1(campoData){
              var data = campoData.value;
              if (data.length == 2){
                  data = data + '/';
                  document.forms[0].data_fim.value = data;
      return true;              
              }
              if (data.length == 5){
                  data = data + '/';
                  document.forms[0].data_fim.value = data;
                  return true;
              }
         }
		 

</script>


<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data In&iacute;cio </label>

										<div class="col-sm-9">
											<input type="date" id="form-field-1" maxlength="10" name="data_inicio" 
                                            value="<? echo $projeto->data_inicio;?>" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    

                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data Fim</label>

										<div class="col-sm-9">
											<input type="date" id="form-field-1" name="data_fim" class="col-xs-10 col-sm-5" value="<? echo $projeto->data_fim;?>"  />
										</div>
									</div>
                                    
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Carga Horária</label>

										<div class="col-sm-9">
											<input type="text" class="form-field-1" name="carga_horaria" class="col-xs-10 col-sm-9" value="<?=$projeto->carga_horaria;?>" />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Vagas ofertadas</label>

										<div class="col-sm-9">
											<input type="text" class="form-field-1" name="vagas_ofertadas" class="col-xs-10 col-sm-9" value="<?=$projeto->vagas_ofertadas;?>" />
										</div>
									</div>
                                    
                                      <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Entidade Certificadora </label>

										<div class="col-sm-9">


                                            <select  class="form-control"  name="entidade_certificadora" >
                                            <option value=""></option>
                                            <option <? if ($projeto->entidade_certificadora == 'UFMT'){ ?> selected="selected" <? } ?> value="UFMT">UFMT</option>
                                            <option <? if ($projeto->entidade_certificadora == 'TCE - ESCOLA DE CONTAS'){ ?> selected="selected" <? } ?> value="TCE - ESCOLA DE CONTAS">TCE - ESCOLA DE CONTAS</option>
                                            <option <? if ($projeto->entidade_certificadora == 'UNISELVA'){ ?> selected="selected" <? } ?> value="UNISELVA">UNISELVA</option>
                                            <option <? if ($projeto->entidade_certificadora == 'HIBRIDA - UFMT e TCE'){ ?> selected="selected" <? } ?> value="HIBRIDA - UFMT e TCE">HIBRIDA - UFMT e TCE</option>
                                            <option <? if ($projeto->entidade_certificadora == 'OUTRAS'){ ?> selected="selected" <? } ?> value="OUTRAS"></option>
                                            </select>
										</div>
									</div>
                                    
                                    <div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Status</label>

												<div class="radio">
													<label>
														<input  type="radio" name="status" value="em andamento" <?php if ($projeto->status=='em andamento'){ ?> checked="checked" <? } ?> class="ace" />
														<span class="lbl"> em andamento</span>
													</label>
												&nbsp;&nbsp;
													<label>
														<input  type="radio" name="status" value="concluido" <?php if ($projeto->status=='concluido'){ ?> checked="checked" <? } ?> class="ace" />
														<span class="lbl"> conclu&iacute;do</span>
													</label>
												</div>
                                          </div>						
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Representante TCE</label>

										<div class="col-sm-9">

                                            <select  class="form-control" name="representante_tce_id[]" multiple="multiple">
                                            <option value=""></option>
                                            <?php
                                            		foreach($representantes as $representante){
                                            			if(in_array($representante['id'], $representantes_projeto)){
                                            ?>
                                            				<option selected="selected" value="<?php echo ($representante['id']); ?>"><?php echo $representante['nome']; ?></option>
                                            				<?php 
                                            			}else{
                                            ?>
                                            				<option value="<?php echo ($representante['id']); ?>"><?php echo $representante['nome']; ?></option>
                                            <?php 		}
                                            		}
                                            ?>	  
                                            </select>
										</div>
									</div>
									                                    



                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Projeto digitalizado:</label>

                                        <div class="col-sm-9">
                                            <p><input type="file" class="form-field-1" name="arquivo" class="col-xs-10 col-sm-9"/></p>

                                            <? $nomeArquivo = '../../public/projetos/'.$projeto->arquivo; ?>
                                            <br>
                                            <?php if(isset($projeto->arquivo)!=""){ ?> Download do arquivo:
                                                <a href="<?php echo $nomeArquivo; ?>"><?=$projeto->arquivo;?></a>
                                                <br>
                                                <label><input type="checkbox" name="delete_anexo" value="1"> Marque para excluir o arquivo</label>
                                            <?php } ?>



                                        </div>
                                    </div>
                                    
                                  <div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1"></label>

												<div class="radio">
													<label>
														<input type="checkbox" name="projeto_especial"  <?php if ($projeto->projeto_especial==1){ ?> checked="checked" <? } ?>  value="1" /> Projeto Especial
													</label>
												&nbsp;&nbsp;
												</div>
                                          </div>  

									

									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
