<?php
echo pack("CCC",0xef,0xbb,0xbf);

    $html = "<table border='1'>";
    $html .= "<tr>";
    $html .= "<td><b>Colaborador</b></td>";
    $html .= "<td><b>Representante</b></td>";
	$html .= "<td><b>Vinculo</b></td>";
	$html .= "<td><b>Email</b></td>";
	$html .= "<td><b>Cpf</b></td>";
	$html .= "<td><b>Telefone</b></td>";
	$html .= "<td><b>Status</b></td>";
    $html .= "</tr>";
    
	foreach ($usuariosporprojeto as $usuario_projeto){
		
    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".($usuario_projeto['colaborador'])."</td>";
    $html .= "<td>".($usuario_projeto['representante'])."</td>";
    $html .= "<td>".($usuario_projeto['vinculo'])."</td>";
    $html .= "<td>".($usuario_projeto['email'])."</td>";
    $html .= "<td>".($usuario_projeto['cpf'])."</td>";
    $html .= "<td>".($usuario_projeto['telefone'])."</td>";
    $html .= "<td>".($usuario_projeto['status'])."</td>";	


    $html .= "</tr>";
    
}
$html .= "</table>";
 
$arquivo = 'colaboradores_por_projeto.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header ("Content-type: application/x-msexcel");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );
  
  echo   $html;
  

?>