
			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('projeto/delete', array('action'=>'delete', 'id' => ''));?>"+id;
				     }
				}
			</script> 	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Projetos inativos</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Projetos inativos

							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    <p>
									<i class="ace-icon fa fa-angle-double-right"></i>
									<a href="<?php echo $this->url('projeto', array('action'=>'index'));?>"> VOLTAR </a>
                                    </p> 
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
                                                    <th width="20%">Área/Núleo</th>                                                    
													<th width="20%">Nome do projeto</th>
                                                    <th width="15%"><small>Líder de projeto (UFMT)</small></th>
                                                    <th width="15%"><small>Representante TCE</small></th>                                                    
													<th width="5%"><small>Atividades Contempladas</small></th>
								                  <?php if  (($_SESSION['permissao']==8) || ($_SESSION['permissao']==2) || ($_SESSION['usuario_id'] == 286)) { ?>
								                   <th width="5%"><small>Colaboradores</small></th>
								                   <?php } ?>

 												<?php if ($_SESSION['permissao'] ==8 ){ ?>
                                                    <th>Opções</th>
                                                <?php } ?>
													
												</tr>
											</thead>

											<tbody>         
											<?php 
												foreach($projetos as $projeto){	
											?>                                   
												<tr>
													<td><strong><?php echo $areas[$projeto['area_id']]; ?></strong><br /><span style="color:#666"><?php echo ($nucleos[$projeto['nucleo_id']]); ?></span></td>													
													<td><?php echo ($projeto['descricao']); ?></td>
                                                    <td><?php if(array_key_exists($projeto['coordenador_id'], $usuarios)){ echo $usuarios[$projeto['coordenador_id']]; }else{ echo ''; } ?></td>

                                                    <td><?php                                                          	
													 	  	if(array_key_exists($projeto['id'], $projetos_representantes)){
															 	  foreach ($projetos_representantes[$projeto['id']] as $key => $representante_id){
															 	  	if(array_key_exists($representante_id, $representantes)){
																   		echo "- ".($representantes[$representante_id])."<br>";
															 	  	}
																  }
													 	  	}
														  ?>
													</td>                                                                                   
													<td>
	                                                    <a href="">
	                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
														<?php ?></span></a>
													</td>                                                    
                            						<?php if  (($_SESSION['permissao']==8) || ($_SESSION['permissao']==2) || ($_SESSION['usuario_id'] == 286)) { ?>                       
                            						<td>							
	                                                    <a href="">
	                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
														<?php ?>
	                                                    </span>
	                                                    </a>                                                    
                                                    </td>
                                                    <?php } ?>												

 <?php if ($_SESSION['permissao'] ==8 ){ ?>
													<td>
														<div class="hidden-sm hidden-xs btn-group">                                                      
															<!--button  onclick="window.location.href='<?=$root;?>ver-projeto/<?=$r['id'];?>';" class="btn btn-xs btn-success">
																<i class="ace-icon fa fa-check bigger-120"></i>
															</button-->
                                                            <? if ($_SESSION['permissao'] ==8){ ?>

															<button onClick="window.location='<?=$root;?>edit-projeto/<?=$r['id'];?>';" class="btn btn-xs btn-info">
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</button>
                                                            <? } ?>
															<button class="btn btn-xs btn-danger" onclick="confirmacao('<?=$r['id']?>')">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button>

															<!--button class="btn btn-xs btn-warning">
																<i class="ace-icon fa fa-flag bigger-120"></i>
															</button-->
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                                    

																	<li>
																		<a href="<?php echo $this->url('projeto/edit', array('action'=>'edit', 'id'=> $projeto['id'])); ?>" class="btn btn-xs btn-info">	
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                 
																	<li>
																		<a href="javascript:func()" onclick="confirmacao('<?php echo  $projeto['id']; ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
																</ul>
															</div>
														</div>
													</td>
                                                       <?php } ?>
												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->
                             
                                
                                <div class="page-header">
							<h3>
								Matriz de Responsabilidade
                            </h3>
						</div><!-- /.page-header -->
                                
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
                                                    <th width="20%">Área/Núleo</th>                                                    
													<th width="20%">Nome do projeto</th>
                                                    <th width="15%"><small>Líder de projeto (UFMT)</small></th>
                                                    <th width="15%"><small>Representante TCE</small></th>                                                    
													<th width="5%"><small>Atividades Contempladas</small></th>
								                  <?php if  (($_SESSION['permissao']==8) || ($_SESSION['permissao']==2) || ($_SESSION['usuario_id'] == 286)) { ?>
								                   <th width="5%"><small>Colaboradores</small></th>
								                   <?php } ?>

 												<?php if ($_SESSION['permissao'] ==8 ){ ?>
                                                    <th>Opções</th>
                                                <?php } ?>
													
												</tr>
											</thead>

											<tbody>         
											<?php 
												foreach($projetos_matriz_responsabilidade as $projeto){	
											?>                                   
												<tr>
													<td><strong><?php if(array_key_exists($projeto['area_id'], $areas)){ echo ($areas[$projeto['area_id']]); }else{ echo ''; } ?></strong><br /><span style="color:#666"><?php if(array_key_exists($projeto['nucleo_id'], $nucleos)){ echo ($nucleos[$projeto['nucleo_id']]); }else{ echo ''; } ?></span></td>													
													<td><?php echo ($projeto['descricao']); ?></td>
                                                    <td><?php if(array_key_exists($projeto['coordenador_id'], $usuarios)){ echo $usuarios[$projeto['coordenador_id']]; }else{ echo ''; } ?></td>

                                                    <td><?php                                                          	
													 	  	if(array_key_exists($projeto['id'], $projetos_representantes)){
															 	  foreach ($projetos_representantes[$projeto['id']] as $key => $representante_id){
															 	  	if(array_key_exists($representante_id, $representantes)){
																   		echo "- ".($representantes[$representante_id])."<br>";
															 	  	}
																  }
													 	  	}
														  ?>
													</td>                                                                                   
													<td>
	                                                    <a href="">
	                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
														<?php ?></span></a>
													</td>                                                    
                            						<?php if  (($_SESSION['permissao']==8) || ($_SESSION['permissao']==2) || ($_SESSION['usuario_id'] == 286)) { ?>                       
                            						<td>							
	                                                    <a href="">
	                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
														<?php ?>
	                                                    </span>
	                                                    </a>                                                    
                                                    </td>
                                                    <?php } ?>												

 <?php if ($_SESSION['permissao'] ==8 ){ ?>
													<td>
														<div class="hidden-sm hidden-xs btn-group">                                                      
															<!--button  onclick="window.location.href='<?=$root;?>ver-projeto/<?=$r['id'];?>';" class="btn btn-xs btn-success">
																<i class="ace-icon fa fa-check bigger-120"></i>
															</button-->
                                                            <? if ($_SESSION['permissao'] ==8){ ?>

															<button onClick="window.location='<?=$root;?>edit-projeto/<?=$r['id'];?>';" class="btn btn-xs btn-info">
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</button>
                                                            <? } ?>
															<button class="btn btn-xs btn-danger" onclick="confirmacao('<?=$r['id']?>')">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button>

															<!--button class="btn btn-xs btn-warning">
																<i class="ace-icon fa fa-flag bigger-120"></i>
															</button-->
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                                    

																	<li>
																		<a href="<?php echo $this->url('projeto/edit', array('action'=>'edit', 'id'=> $projeto['id'])); ?>" class="btn btn-xs btn-info">	
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                 
																	<li>
																		<a href="javascript:func()" onclick="confirmacao('<?php echo  $projeto['id']; ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
																</ul>
															</div>
														</div>
													</td>
                                                       <?php } ?>
												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->


								<div class="row">
									<div class="col-xs-12">
										</div><!-- /.modal-content -->
									</div><!-- /.modal-dialog -->
								</div><!-- PAGE CONTENT ENDS -->


					</div><!-- /.page-content -->
			</div><!-- /.main-content -->
