
			<!-- /section:basics/sidebar -->
			<div class="main-content">
                              <script language="Javascript">
function confirmacao(id) {
     var resposta = confirm("Deseja remover esse registro?");
 
     if (resposta == true) {
          window.location.href = "<?=$root;?>remover.php?t=atividade_projeto&redirect=ver-projeto/<?=$_GET['p1'];?>&id="+id;
     }
}
</script> 	       	      
	<? 
		$sql = "SELECT * FROM `projeto` WHERE id = ".(int)$_GET['p1']." and del = 0";
		$executa2 = mysql_query($sql) or die (mysql_error());
		$p = mysql_fetch_array($executa2);
		?>
        	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Projetos</li>
						</ul><!-- /.breadcrumb -->

						<!-- #section:basics/content.searchbox ->
						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- /.nav-search -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Projeto: <strong><?=$p['descricao'];?></strong>
								

							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">


								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    <?
									$sql=mysql_query("
									select a.*, b.id as usuario_id, b.nome as colaborador, b.permissao, b.email, b.cpf, b.tel_fixo,b.status, c.descricao as vinculo from usuario_projeto a
									 left join usuario b on b.id = a.usuario_id 
									 left join tipo_vinculo c on c.id = b.vinculo
									 where a.del = 0 and b.del = 0 and b.status = 'ativo' and a.projeto_id = ".(int)$_GET['p1']." order by b.nome") or die (mysql_error());?>
                                     
                                     <span style="float:right"><a href="<?=$root;?>exportar-colaborador-projeto.php?p1=<?=$_GET['p1'];?>"><img src="<?=$root;?>ico_excel.png" width="30" height="30"  /></a></span><br /><br />
                                    <table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th>Colaborador</th>
                                                    <th>Tipo</th>
                                                    <th>Representantes</th>
                                                    <? if ($_SESSION['permissao'] == 8){ ?>
                                                    <th>Vinculo</th>
                                                    <? } ?>
                                                    <th>Email</th>
                                                    <th>Cpf</th>
                                                    <th>Telefone fixo</th>
                                                    <th>Status</th>
                                                     <? //if (($_SESSION['permissao'] == 8)||($_SESSION['permissao'] == 4)){ ?>
                                                    <th>Atividades</th>
                                                    <th>Relat&oacute;rios</th>
                                                    <? //} ?>

													
												</tr>
											</thead>

											<tbody>
                                                  <? $i = 1; while($r=mysql_fetch_array($sql)){ ?>
												<tr>
													
													<td>
													<?=($r['colaborador']);?>
													</td>
                                                  <td>
                                                  <? 
		  if ($r['permissao'] ==1){ echo "colaborador"; }
		  if ($r['permissao'] ==2){ echo "coordenador de área"; }
		  if ($r['permissao'] ==3){ echo "coordenador de projeto"; }
		  if ($r['permissao'] ==4){ echo "coordenador de núcleo"; }

		  if ($r['permissao'] ==5){ echo "coordenador técnico"; }
		  if ($r['permissao'] ==6){ echo "coordenador administrativo"; }
		  if ($r['permissao'] ==7){ echo "membro de projeto EPE"; }
		  if ($r['permissao'] ==8){ echo "Geral"; }


		  
		  ?></td>  
          <td>
          <?
													$psql=mysql_query("select a.id, a.representante_id, p.nome as descricao from usuario_projeto a left join representante_tce p on p.id = a.representante_id where a.del = 0 and a.usuario_id = $r[usuario_id] group by a.representante_id") or die (mysql_error());
													while($p=mysql_fetch_array($psql)){
														echo $p['descricao']."<br>";
													} ?></td>
                                                    <? if ($_SESSION['permissao'] == 8){ ?>
										           <td>
													<?=(utf8_encode($r['vinculo']));?>
													</td>
                                                    <? } ?>
                                                    
         											 <td>
													<?=($r['email']);?>
													</td>
                                                    
                                                    <td>
													<?=($r['cpf']);?>
													</td>
                                                    <td>
													<?=($r['tel_fixo']);?>
													</td>
                                                    <td>
                                                    <?=utf8_encode($r['status']);?>
                                                    
                                                    <? if ($r['status']== 'inativo'){ echo '<br>'.$r['data_inatividade'];}?>
                                                    </td>
                                                    <? //if (($_SESSION['permissao'] == 8)||($_SESSION['permissao'] == 4)){ 
													
										
							$total_atividade_projeto=mysql_num_rows(mysql_query("select * from atividade_projeto_usuario where projeto_id = ".(int)$_GET[p1]." and usuario_id = $r[usuario_id]")); ?>
                                                    
                                                    <th>
                     <a href="<?=$root;?>atividade_projeto_usuario/<?=($r['usuario_id']);?>/<?=($_GET['p1']);?>"><?=$total_atividade_projeto;?></a></th>
                                                    
                                                    <th><a href="<?=$root;?>ver-relatorio-colaborador/<?=($r['usuario_id']);?>">relat&oacute;rios</a></th>
                                                    <? //} ?>
												</tr>
                                                <? $i++; } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->


								<div class="row">
									<div class="col-xs-12">
										
											<!--div class="modal-footer no-margin-top">
												

												<ul class="pagination pull-right no-margin">
													<li class="prev disabled">
														<a href="#">
															<i class="ace-icon fa fa-angle-double-left"></i>
														</a>
													</li>

													<li class="active">
														<a href="#">1</a>
													</li>

													<li>
														<a href="#">2</a>
													</li>

													<li>
														<a href="#">3</a>
													</li>

													<li class="next">
														<a href="#">
															<i class="ace-icon fa fa-angle-double-right"></i>
														</a>
													</li>
												</ul>
											</div-->
										</div><!-- /.modal-content -->
									</div><!-- /.modal-dialog -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
