
			<!-- /section:basics/sidebar -->
			<div class="main-content">
				       	      
                
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<? //$root;?>">Home</a>
							</li>

							<li class="active">Projetos</li>
						</ul><!-- /.breadcrumb -->

						<!-- #section:basics/content.searchbox ->
						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- /.nav-search -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Projeto: <strong><? echo $projeto->descricao;?></strong>
								

							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
					
                    
                    <p> Total de participantes: <?php echo count($participantesporprojeto); ?> 

                                    <!--i class="ace-icon fa fa-angle-double-right"></i>
                                    <a href="<?php echo $this->url('participante/add', array('action'=>'add', 'projeto_id' => $id));?>"> cadastrar novo participante</a-->

								 <form action="" name="formulario" method="POST">
								
								<p>
								<select name="status" required>
								 <option></option>
								 <option value="0">não concluído</option>
								 <option value="1">em processo de conclusao</option>
								 <option value="2">concluído</option>
								 
								 
								</select>
								<input type="submit" value="salvar">
								</p>
								<script language=javascript>
								<!--
								cont = 0;
								function CheckAll() { 
								for (var i=0;i<document.formulario.elements.length;i++) {
									var x = document.formulario.elements[i];
									if (x.name == 'concluido[]') { 
								x.checked = document.formulario.selall.checked;
								} 
								}
								if (cont == 0){    
								var elem = document.getElementById("checar");
								//elem.innerHTML = "Desmarcar todos";
								cont = 1;
								} else {
								var elem = document.getElementById("checar");
								//elem.innerHTML = "Marcar todos";
								cont = 0;
								}

								} 
								//-->
								</script>

                                 <table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th><input type=checkbox name="selall" onClick="CheckAll()"><span id="checar"></span><br></th>
													<th>Nome</th>
                                                    <th>Cpf</th>
                                                    <th>Email</th>
                                                    <th>Telefone</th>
													<th>Status</th>
                                                    <!--th>Data de nascimento</th-->
                                                    <!--th>Opções</th-->
												</tr>
											</thead>

											<tbody>
                                            
                                            <?php 
												foreach($participantesporprojeto as $colaborador){	
													if ($colaborador['concluido']==0){$status="não concluído";}
													if ($colaborador['concluido']==1){$status="em processo de conclusão ";}
													if ($colaborador['concluido']==2){$status="concluído";}
											?>     
                                            
                                            <tr>
													<td><input type="checkbox" name="concluido[]" value="<?=$colaborador['id'];?>">
													<td><?=($colaborador['colaborador']);?></td>
                                                    <td><?=($colaborador['cpf']);?></td>
                                                    <td><?=($colaborador['email']);?></td>
                                                    <td><?=($colaborador['tel_movel']);?></td>
													<td><?=($status);?></td>
                                                    <!--td><?=date('d/m/Y', strtotime($colaborador['data_nascimento']));;?></td>
                                                    <!--td>
                                                    
                       <a href="<?php //echo $this->url('participante/delete-projeto-participante', array('action'=>'delete-projeto-participante', 'projeto_id' => $id, 'id' => $colaborador['participante_projeto_id']));?>">
                                                    <button class="btn btn-xs btn-danger">
                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                    </button></a>
                                                     </td-->
                                            </tr>
                                            <? } ?>                                                                                      
                                            </tbody>
										</table>
									
                                   </form>
                                </div>
                                
                                
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
