
			<!-- /section:basics/sidebar -->
			<div class="main-content">
				       	      
                
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<? //$root;?>">Home</a>
							</li>

							<li class="active">Projetos</li>
						</ul><!-- /.breadcrumb -->

						<!-- #section:basics/content.searchbox ->
						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- /.nav-search -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Projeto: <strong><? echo $projeto->descricao;?></strong>
								

							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
					
                    <span style="float:right"><a target="_blank" href="<?php echo $this->url('projeto/exportar-colaboradores-por-projeto', array('action'=>'exportarColaboradoresPorProjeto',  'id'=> $projeto->id));?>">exportar</a></span>

								
                                 <table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th>Colaborador</th>
                                                    <th>Tipo</th>
                                                    <th>Lotação</th>
                                                    <th>Representante</th>
                                                    <th>Vinculo</th>
                                                    <th>Email</th>
                                                    <th>Cpf</th>
                                                    <th>Telefone fixo</th>
                                                    <th>Status</th>
                                                    <th>Atividades</th>
                                                    <th>Relat&oacute;rios</th>
												</tr>
											</thead>

											<tbody>
                                            
                                            <?php 
												foreach($usuariosporprojeto as $colaborador){	
											?>     
                                            
                                            <tr>
													
													<td>
													<a href="<?php echo $this->url('usuario-projeto/consulta', array('action'=>'consulta', 'usuario_id'=> $colaborador['usuario_id'])); ?>">
													<?=($colaborador['colaborador']);?>
													</a>
												<? if ($usuario_dados->permissao==8){ ?><Br><a href="https://setec.ufmt.br/tce/convenio2020/usuario-projeto/consulta/<?=$colaborador['usuario_id'];?>" target="_blank"><i class="ace-icon fa fa-link bigger-120"></i></a><? } ?>
													<? $nome = explode(" ",$colaborador['colaborador']);$firstname = $nome[0];unset($nome[0]);$lastname= implode(" ", $nome);?>
												<? if ($usuario_dados->permissao==8){ ?>
													<a  href="http://setec.ufmt.br/tce/cursosead/logar.php?username=<?=base64_encode($colaborador['cpf']);?>&firstname=<?=base64_encode($firstname);?>&lastname=<?=base64_encode($lastname);?>&email=<?=base64_encode($colaborador['email']);?>" target="_blank">
													<i class="ace-icon fa fa-graduation-cap"></i></a><? } ?>
													</td>
                                                    
                                                    <td>
                                                    
                                                    <?php 
														  if ($colaborador['permissao'] ==1){ echo "colaborador"; }
														  if ($colaborador['permissao'] ==2){ echo "Secretaria do convênio"; }
														  if ($colaborador['permissao'] ==4){ echo "coordenador de núcleo"; }
														  if ($colaborador['permissao'] ==8){ echo "Administrador do sistema"; }		  
														  ?>
                                                    
                                                    </td>
                                                    <td><?=($colaborador['unidade_lotacao']);?></td>
                                                    <td><?=($colaborador['representante']);?></td>
                                                    <td><?=($colaborador['vinculo']);?></td>
		                                            <td><?=($colaborador['email']);?></td>
                                                    <td><?=($colaborador['cpf']);?></td>
                                                    <td><?=$colaborador['tel_fixo'];?></td>
                                                    <td><?=$colaborador['status'];?></td>
                                                    <td><a href="<?php echo $this->url('projeto/associar-atividades-projeto-colaborador', array('action'=>'associarAtividadesProjetoColaborador', 'projeto_id'=> $colaborador['projeto_id'], 'usuario_id'=> $colaborador['usuario_id'])); ?>"><?=$colaborador['total_atividades'];?></a></td>
                                                    <td><a target="_blank" href="<?php echo $this->url('relatorio-colaborador/ver-relatorio-colaborador', array('action'=>'ver-relatorio-colaborador',  'usuario_id'=> $colaborador['usuario_id']));?>">relatório</a></td>
                                            </tr>
                                            <? } ?>                                                                                      
                                            </tbody>
										</table>
                                
                                </div>
                                
                                
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
