<!-- /section:basics/sidebar -->

<div class="main-content">
	<div class="main-content-inner">
		<!-- #section:basics/content.breadcrumbs -->
		<div class="breadcrumbs" id="breadcrumbs">
			<script type="text/javascript">
				try {
					ace.settings.check('breadcrumbs', 'fixed')
				} catch (e) {}
			</script>

			<ul class="breadcrumb">
				<li>
					<i class="ace-icon fa fa-home home-icon"></i>
					<a href="<?php echo $this->url('home', array('action' => 'index')); ?>">Home</a>
				</li>

				<li class="active">Cadastrar novo colaborador</li>
			</ul><!-- /.breadcrumb -->


			<!-- /section:basics/content.searchbox -->
		</div>

		<!-- /section:basics/content.breadcrumbs -->
		<div class="page-content">

			<div class="page-header">
				<h3>
					Cadastrar colaborador
				</h3>
			</div><!-- /.page-header -->

			<div class="row">
				<div class="col-xs-12">

					<!-- PAGE CONTENT BEGINS -->
					<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
						<!-- #section:elements.form -->


						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Código </label>

							<div class="col-sm-9">
								<input type="text" disabled value="<?php echo $colaborador->id; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome </label>

							<div class="col-sm-9">
								<input type="text" id="nome" name="nome" value="<?php echo $colaborador->nome; ?>" class="col-xs-10 col-sm-5" required />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Email </label>

							<div class="col-sm-9">
								<input type="email" id="email" name="email" value="<?php echo $colaborador->email; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Fixo </label>

							<div class="col-sm-9">
								<input type="text" id="tel_fixo" name="tel_fixo" value="<?php echo $colaborador->tel_fixo; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Móvel </label>

							<div class="col-sm-9">
								<input type="text" id="tel_movel" name="tel_movel" value="<?php echo $colaborador->tel_movel; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> CPF/CNPJ </label>

							<div class="col-sm-9">
								<input type="text" id="cpf1" name="cpf" value="<?php echo $colaborador->cpf; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nº termo de autorização/ Contrato </label>

							<div class="col-sm-9">
								<input type="text" id="termo_autorizacao" name="termo_autorizacao" value="<?php echo $colaborador->termo_autorizacao; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<!-- <div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Parcelas </label>

							<div class="col-sm-9">
								<input type="text" id="parcelas" name="parcelas" value="<?php echo $colaborador->parcelas; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> CNPJ </label>

							<div class="col-sm-9">
								<input type="text" id="cnpj" name="cnpj" value="<?php echo $colaborador->cnpj; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div> -->

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Instituição </label>

							<div class="col-sm-9">
								<input type="text" id="instituicao" name="instituicao" value="<?php echo $colaborador->instituicao; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data Admissão </label>

							<div class="col-sm-9">
								<input type="date" id="data_admissao" name="data_admissao" value="<?php echo $colaborador->data_admissao; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

					


						<!-- <div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Raz&atilde;o Social </label>

							<div class="col-sm-9">
								<input type="text" id="razao_social" name="razao_social" value="<?php echo $colaborador->razao_social; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div> -->


						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Vínculo</label>

							<div class="col-sm-4">

								<select name="vinculo" class="form-control" id="vinculo">
									<option></option>
									<?php foreach ($tipo_vinculos as $tipo_vinculo) { ?>
										<option <?php if ($colaborador->vinculo == $tipo_vinculo['id']) {
													echo "selected";
												} ?> value="<?php echo $tipo_vinculo['id']; ?>"><?php echo $tipo_vinculo['descricao']; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> SIAPE </label>

							<div class="col-sm-9">
								<input type="text" id="siape" name="siape" value="<?php echo $colaborador->siape; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Curso / Unidade de Lotação: </label>

							<div class="col-sm-9">
								<input type="text" id="razao_social" name="curso_estagio" value="<?php echo $colaborador->curso_estagio; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Professor (em caso de estágio): </label>

							<div class="col-sm-9">
								<input type="text" id="razao_social" name="professor_estagio" value="<?php echo $colaborador->professor_estagio; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>


						<!-- <div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Status do enquadramento funcional: </label>

							<div class="col-sm-9">
								<input type="text" id="status_enquadramento_funcional" name="status_enquadramento_funcional" value="<?php echo $colaborador->status_enquadramento_funcional; ?>" class="col-xs-10 col-sm-2" />
							</div>
						</div> -->

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Local em que o colaborador, bolsista ou prestador de serviço executará o projeto EPE: </label>

							<div class="col-sm-9">
								<input type="text" id="unidade_lotacao" name="unidade_lotacao" value="<?php echo $colaborador->unidade_lotacao; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Bonificação </label>

							<div class="col-sm-9">
								<select name="bonificacao_id" class="form-control" id="bonificacao_id">
									<option></option>
									<?php foreach ($bonificacoes as $bonificacao) { ?>
										<option <?php if ($colaborador->bonificacao_id == $bonificacao['id']) {
													echo "selected";
												}
												?> value="<?php echo $bonificacao['id']; ?>"><?php echo $bonificacao['codigo']; ?> - <?php echo $bonificacao['descricao']; ?> - <?php echo $bonificacao['carga_horaria']; ?>h - <?php echo $bonificacao['meses']; ?> meses</option>
									<?php } ?>
								</select>
							</div>
						</div>

						<? if ($colaborador->bonificacao_id) { ?>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Projeto bonificação: </label>

								<div class="col-sm-9">
									<select name="bonificacao_projeto" class="form-control" id="bonificacao_projeto">
										<option></option>
										<?php foreach ($projetos as $projeto) { ?>
											<option <?php if ($colaborador->bonificacao_projeto == $projeto['id']) {
														echo "selected";
													}
													?> value="<?php echo $projeto['id']; ?>"><?php echo $projeto['descricao']; ?></option>
										<?php } ?>
									</select>
								</div>
							</div>
						<? } ?>



						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Bolsa </label>

							<div class="col-sm-9">
								<select name="bolsa_id" class="form-control" id="bolsa_id">
									<option></option>
									<?php foreach ($bolsas as $bolsa) { ?>
										<option <?php if ($colaborador->bolsa_id == $bolsa['id']) {
													echo "selected";
												}
												?> value="<?php echo $bolsa['id']; ?>"><?php echo $bolsa['codigo']; ?> - <?php echo $bolsa['descricao']; ?> - <?php echo $bolsa['carga_horaria']; ?>h - <?php echo $bolsa['meses']; ?> meses</option>
									<?php } ?>
								</select>
							</div>
						</div>

						<? if ($colaborador->bolsa_id) { ?>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Projeto bolsa: </label>

								<div class="col-sm-9">
									<select name="bolsa_projeto" class="form-control" id="bolsa_projeto">
										<option></option>
										<?php foreach ($projetos1 as $projeto) { ?>
											<option <?php if ($colaborador->bolsa_projeto == $projeto['id']) {
														echo "selected";
													}
													?> value="<?php echo $projeto['id']; ?>"><?php echo $projeto['descricao']; ?></option>
										<?php } ?>
									</select>
								</div>
							</div>
						<? } ?>


						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Tipo</label>

							<div class="col-sm-9">

								<?php foreach ($permissoes as $permissao) { ?>

									<div class="radio">
										<?php if ($permissao['id'] == $colaborador->permissao) { ?>
											<label>
												<input checked="checked" type="radio" class="ace" name="permissao" value="<?php echo $permissao['id']; ?>" />
												<span class="lbl"> <?php echo $permissao['descricao']; ?></span>
											</label>
										<?php } else { ?>
											<label>
												<input type="radio" class="ace" name="permissao" value="<?php echo $permissao['id']; ?>" />
												<span class="lbl"> <?php echo $permissao['descricao']; ?></span>
											</label>
										<?php } ?>
									</div>

								<?php } ?>

							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Status</label>

							<div class="col-sm-2">

								<select name="status" class="form-control" id="status">
									<option value="">Selecione...</option>

									<option <?php if ($colaborador->status == 'ativo') {
												echo "selected";
											} ?> value="ativo">ativo</option>
									<option <?php if ($colaborador->status == 'inativo') {
												echo "selected";
											} ?> value="inativo">inativo</option>

									<option <?php if ($colaborador->status == 'licenca maternidade') {
												echo "selected";
											} ?> value="licenca maternidade">licença maternidade</option>

									<option <?php if ($colaborador->status == 'licenca medica') {
												echo "selected";
											} ?> value="licenca medica">licença médica</option>

									<option <?php if ($colaborador->status == 'férias') {
												echo "selected";
											} ?> value="férias">férias</option>
								</select>

							</div>
						</div>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data inatividade:</label>

							<div class="col-sm-4">
								<input type="date" id="data_inatividade" name="data_inatividade" value="<?php echo $colaborador->data_inatividade; ?>" class="col-xs-10 col-sm-5" />
							</div>
						</div>


						<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>
						<script type="text/javascript">
							window.onload = function() {
								$(document).ready(function() {
									$('#estado').change(function() {
										$.post("/tce/convenio22/colaborador/get-funcoes/" + $('#estado').val(), {
											area: "" + $('#estado').val()
										}, function(data) {
											$("#cargo_funcao").html(data);
										});

									});
								});
							};
						</script>


						<div class="form-group" id="conteudo">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Área 1</label>

							<div class="col-sm-9">

								<select class="form-control" name="area_id" id="estado">
									<option value="0"></option>
									<?php foreach ($areas as $area) {
										if ($colaborador->area_id == $area['id']) { ?>
											<option selected="selected" value="<?php echo $area['id']; ?>"><?php echo ($area['descricao']); ?></option>
										<?php } else { ?>
											<option value="<?php echo $area['id']; ?>"><?php echo ($area['descricao']); ?></option>
									<?php 		}
									} ?>
								</select>
							</div>

						</div>


						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Função:</label>
							<div class="col-sm-9">

								<div id="nucleo"></div>
								<select class="form-control" name="cargo_funcao" id="cargo_funcao" require>
									<option></option>
									<option></option>
									<?php foreach ($funcoes_por_area as $funcao) { ?>
										<option <?php if ($funcao['colaborador_id'] != "") {
													echo " style='background:#EEE'";
												} ?> <?php if ($colaborador->cargo_funcao == $funcao['id']) {
															echo "selected";
														} ?> value="<?php echo $funcao['id']; ?>"><?php echo $funcao['funcao']; ?> - <?php echo $funcao['carga_horaria']; ?>h - <?php echo $funcao['meses']; ?> meses</option>
									<?php } ?>
								</select>
							</div>
						</div>


						<div class="form-group" id="conteudo">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Representante:</label>

							<div class="col-sm-9">
								<select required class="form-control" name="representante_id" class="chosen">
									<option value="0"></option>
									<?php foreach ($representantes as $representante) { ?>
										<option <?php if ($colaborador->representante_id == $representante['id']) { ?> selected="selected" <?php } ?> value="<?php echo $representante['id']; ?>"><?php echo ($representante['nome']); ?></option>
									<?php } ?>
								</select>
							</div>

						</div>



						<!-- <hr>

                                    <div class="form-group" id="conteudo">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Área 2</label>

                                        <div class="col-sm-9">

                                            <select  class="form-control"  name="area_id2" id="estado" required >
                                                <option value="0"></option>
                                                <?php foreach ($areas2 as $area) {
													if ($colaborador->area_id2 == $area['id']) { ?>
                                                        <option selected="selected" value="<?php echo $area['id']; ?>"><?php echo ($area['descricao']); ?></option>
                                                    <?php } else { ?>
                                                        <option value="<?php echo $area['id']; ?>"><?php echo ($area['descricao']); ?></option>
                                                    <?php 		}
												} ?>
                                            </select>
                                        </div>

                                    </div>

                                    <div class="form-group" id="conteudo">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Representante:</label>

                                        <div class="col-sm-9">
                                            <select  class="form-control"  name="representante_id2" class="chosen">
                                                <option value="0"></option>
                                                <?php foreach ($representantes2 as $representante) { ?>
                                                    <option <?php if ($colaborador->representante_id2 == $representante['id']) { ?> selected="selected" <?php } ?> value="<?php echo $representante['id']; ?>"><?php echo ($representante['nome']); ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>

                                    </div> -->




						<div class="form-group">


							<div class="">
								<div class="col-md-offset-3 col-md-">
									<button class="btn btn-info" type="submit">
										<i class="ace-icon fa fa-check bigger-110"></i>
										Salvar
									</button>

								</div>


							</div>

						</div><!-- /.col -->
					</form>



					<div class="page-header">
						<h3>
							Documentação do colaborador
						</h3>
					</div><!-- /.page-header -->
					<form class="form-horizontal" role="form" action="<?php echo $this->url('colaborador/upload-documento', array('action' => 'upload-documento', 'id' => $colaborador->id)); ?>" method="post" enctype="multipart/form-data">
						<div class="form-group" id="conteudo">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Tipo:</label>

							<div class="col-sm-9">
								<select required class="form-control" name="tipo" class="chosen">
									<option></option>
									<option value="Declaração">Declaração</option>
									<option value="Termo de autorização">Termo de autorização</option>
									<option value="Contrato">Contrato</option>
								</select>
							</div>

						</div>

						<br>

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Selecionar arquivo</label>
							<div class="col-sm-9">
								<p><input type="file" class="form-field-1" name="arquivo" class="col-xs-10 col-sm-9" /></p>
							</div>
						</div>
						<br>




						<div class="">
							<div class="col-md-offset-3 col-md-">
								<button class="btn btn-info" type="submit">
									<i class="ace-icon fa fa-check bigger-110"></i>
									Salvar
								</button>
							</div>
						</div>
						<br>
					</form>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Documentos:</label>
						<div class="col-sm-9">
							<script language="Javascript">
								function confirmacao(id) {
									var resposta = confirm("Deseja remover esse registro?");

									if (resposta == true) {
										window.location.href = "<?php echo $this->url('colaborador/delete-documento', array('action' => 'delete', 'id' => '')); ?>" + id + "?uid=<?= $id; ?>";
									}
								}
							</script>
							<table class="table">
								<thead>
									<tr>
										<th>Documentos</th>
										<th>Opções</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach ($documentos as $documento) { ?>
										<tr>
											<td>
												<A target="_blank" href="../../public/colaborador-anexo/<?= $documento['arquivo']; ?>"><?= $documento['tipo']; ?></A>
											</td>
											<td>
												<button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo $documento['id']; ?>')">
													<i class="ace-icon fa fa-trash-o bigger-120"></i>
												</button>
											</td>
										</tr>
									<?php } ?>



								</tbody>

							</table>


						</div>
					</div>






				</div><!-- /.row -->
			</div><!-- /.main-content -->

			<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js"></script>
			<script src="dist/jquery.maskMoney.min.js" type="text/javascript"></script>
			<script>
				$("#cpf").mask("999.999.999-99");
				$("#cnpj").mask("99.999.999/9999-99");

				$("#tel_movel").mask("(99) 99999999?9");
				$("#tel_movel").blur(function(event) {
					var verificastring = $(this).val().substring($(this).val().length - 1, $(this).val().length);
					if ($(this).val().length == 15) {
						$("#tel_movel").mask("(99) 99999999?9");
					} else {
						$("#tel_movel").mask("(99) 99999999?9");
					}
				});

				$("#tel_fixo").mask("(99) 99999999?9");
				$("#tel_fixo").blur(function(event) {
					var verificastring = $(this).val().substring($(this).val().length - 1, $(this).val().length);
					if ($(this).val().length == 15) {
						$("#tel_fixo").mask("(99) 99999999?9");
					} else {
						$("#tel_fixo").mask("(99) 99999999?9");
					}
				});
			</script>