<?php
echo pack("CCC",0xef,0xbb,0xbf);

$html = "<table border='1'>";
$html .= "<tr>";
$html .= "<td><b>&nbsp;</b></td>";
$html .= "<td><b>Nome</b></td>";
$html .= "<td><b>Instituição</b></td>";
$html .= "<td><b>Curso</b></td>";
$html .= "<td><b>cpf</b></td>";
$html .= "<td><b>email</b></td>";
$html .= "<td><b>telefone</b></td>";
$html .= "<td><b>Função</b></td>";
$html .= "<td><b>Carga horária</b></td>";
$html .= "<td><b>Área</b></td>";
$html .= "<td><b>Tipo</b></td>";
$html .= "<td><b>Status</b></td>";
$html .= "</tr>";



$i =1;
foreach ($colaboradores as $colaborador){

 if(isset($colaborador_projetos[$colaborador['id']])){ $total = count($colaborador_projetos[$colaborador['id']]); }

    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".$i."</td>";
	$html .= "<td>".$colaborador['nome']."</td>";
	$html .= "<td>".$colaborador['instituicao']."</td>";
	$html .= "<td>".$colaborador['curso_estagio']."</td>";
	$html .= "<td>".$colaborador['cpf']."</td>";
	$html .= "<td>".$colaborador['email']."</td>";
	$html .= "<td>".$colaborador['tel_movel']."</td>";
	$html .= "<td>".$colaborador['funcao']."</td>";
	$html .= "<td>".$colaborador['carga_horaria']."</td>";
    $html .= "<td>".$areas[$colaborador['area_id']]."</td>";
    $html .= "<td>".$colaborador['tipo']."</td>";   
    $html .= "<td>".($colaborador['status'])."</td>";
    

    $html .= "</tr>";
$i++;
}
$html .= "</table>";

$arquivo = 'usuarios.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header ("Content-type: application/x-msexcel");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );

echo   $html;


?>