<?php
echo pack("CCC",0xef,0xbb,0xbf);

$html = "<table border='1'>";
$html .= "<tr>";
$html .= "<td><b>&nbsp;</b></td>";
$html .= "<td><b>Nome</b></td>";
$html .= "<td><b>Email</b></td>";
$html .= "<td><b>Telefone</b></td>";
$html .= "<td><b>CPF</b></td>";
$html .= "<td><b>Area</b></td>";
$html .= "<td><b>Projeto</b></td>";
$html .= "<td><b>Representantes</b></td>";
$html .= "<td><b>Vinculo</b></td>";
$html .= "<td><b>Tipo</b></td>";
$html .= "<td><b>Cargo função</b></td>";
$html .= "<td><b>Status</b></td>";
$html .= "<td><b>Enquadramento funcional</b></td>";
$html .= "<td><b>Unidade de atuação</b></td>";
$html .= "<td><b>Ultima atividade</b></td>";
$html .= "</tr>";



$i =1;
foreach ($colaboradores as $colaborador){

 if(isset($colaborador_projetos[$colaborador['id']])){ $total = count($colaborador_projetos[$colaborador['id']]); }else{ echo '0'; }

    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".$i."</td>";
	$html .= "<td>".($colaborador['nome'])."</td>";
	$html .= "<td>".($colaborador['email'])."</td>";
	$html .= "<td>".($colaborador['tel_movel'])."</td>";
	$html .= "<td>".($colaborador['cpf'])."</td>";
    $html .= "<td>".$areas[$colaborador['area_id']]."</td>";
    //$html .= "<td>".($areas[$usuario_projeto['area_id']])."</td>";
    $html .= "<td>";
    foreach ($colaborador_projetos[$colaborador['id']] as $projeto_id){

        $html .= $projetos[$projeto_id].';';

    }
    $html .= "</td>";
    $html .= "<td>";
    if(isset($representantes[$colaborador['representante_id']])){
        $html .= ($representantes[$colaborador['representante_id']]);
    }

    $html .= "</td>";
    $html .= "<td>";
    if(isset($tipo_vinculos[$colaborador['vinculo']])){
        $html .= ($tipo_vinculos[$colaborador['vinculo']]);
    }
    $html .= "</td>";

    $html .= "<td>".$colaborador['permissao']."</td>";
    $html .= "<td>".($colaborador['cargo_funcao'])."</td>";
    $html .= "<td>".($colaborador['status'])."</td>";
    $html .= "<td>".($colaborador['status_enquadramento_funcional'])."</td>";
    $html .= "<td>".($colaborador['unidade_lotacao'])."</td>";
    $html .= "<td>";

    if(isset($usuarios_atividades[$colaborador['id']][$usuarios_atividades['projeto_id']][0]['texto'])){
        $html .= strip_tags(($usuarios_atividades[$colaborador['id']][$usuarios_atividades['projeto_id']][0]['texto']));
    }

    $html .= "</td>";

    $html .= "</tr>";
$i++;
}
$html .= "</table>";

$arquivo = 'usuarios.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header ("Content-type: application/x-msexcel");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );

echo   $html;


?>