<?php
echo pack("CCC",0xef,0xbb,0xbf);

    $html = "<table border='1'>";
    $html .= "<tr>";
    $html .= "<td><b>Nome</b></td>";
    $html .= "<td><b>Area</b></td>";
	$html .= "<td><b>Projeto</b></td>";
	$html .= "<td><b>Representantes</b></td>";
	$html .= "<td><b>Vinculo</b></td>";
	$html .= "<td><b>Tipo</b></td>";
	$html .= "<td><b>Cargo função</b></td>";
	$html .= "<td><b>Status</b></td>";
	$html .= "<td><b>Enquadramento funcional</b></td>";
	$html .= "<td><b>Unidade lotação</b></td>";
	$html .= "<td><b>Ultima atividade</b></td>";

    $html .= "</tr>";
    
	foreach ($usuario_projetos as $usuario_projeto){
		
	

    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".($usuario_projeto['nome'])."</td>";
    $html .= "<td>".($areas[$usuario_projeto['area_id']])."</td>";
    $html .= "<td>".($projetos[$usuario_projeto['projeto_id']])."</td>";
    $html .= "<td>"; 
    	if(isset($representantes[$usuario_projeto['representante_id']])){
    		$html .= ($representantes[$usuario_projeto['representante_id']]);
    	}

    $html .= "</td>";
    $html .= "<td>";
    	if(isset($vinculos[$usuario_projeto['vinculo']])){
    		$html .= ($vinculos[$usuario_projeto['vinculo']]);
    	}
	$html .= "</td>";
	
    $html .= "<td>".$usuario_projeto['permissao']."</td>";
	$html .= "<td>".($usuario_projeto['cargo_funcao'])."</td>";	
    $html .= "<td>".($usuario_projeto['status'])."</td>";	
    $html .= "<td>".($usuario_projeto['status_enquadramento_funcional'])."</td>";	
    $html .= "<td>".($usuario_projeto['unidade_lotacao'])."</td>";
	 $html .= "<td>";
	 
 	if(isset($usuarios_atividades[$usuario_projeto['usuario_id']][$usuarios_atividades['projeto_id']][0]['texto'])){
	 	$html .= strip_tags(($usuarios_atividades[$usuario_projeto['usuario_id']][$usuarios_atividades['projeto_id']][0]['texto']));
 	}
	
	$html .= "</td>";

    $html .= "</tr>";
    
}
$html .= "</table>";
 
$arquivo = 'usuarios.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header ("Content-type: application/x-msexcel");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );
  
  echo   $html;
  

?>