<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Cadastrar nova submeta</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Cadastrar submeta
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
                            <p>
                            	<a href="<?php echo $this->url('submeta/consulta', array('action'=>'consulta', 'area_id' => $area_id));?>">Voltar</a>
                            </p>

								<!-- PAGE CONTENT BEGINS -->
								<form id="submeta_add" name="submeta_add" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php echo $this->url('submeta/add', array('action' => 'add', 'area_id' => $area_id));?>" role="form" class="form-horizontal form-label-left">
               									
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Área </label>
										<div class="col-sm-9">
											<input type="text" id="form-field-1" value="<?php echo $area->descricao; ?>" name="descricao" class="col-xs-10 col-sm-5" disabled="disabled" />
										</div>
									</div>
                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Submeta </label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="descricao" class="col-xs-10 col-sm-5" required style="width:100%" /></textarea>
										</div>
									</div>
									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
