<?php 

$_SESSION['permissao'] = 8 ;

?>
			<!-- /section:basics/sidebar -->
			<div class="main-content">

				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="">Home</a>
							</li>

							<li class="active">Programas de fomento</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
                                Programa de fomento
							</h3>
						</div><!-- /.page-header -->
                        

						<div class="row">
							<div class="col-xs-12">
                                <p>
                                <i class="ace-icon fa fa-angle-double-right"></i>
                                <a href="<?php echo $this->url('area/add', array('action'=>'add'));?>"> cadastrar novo programa de fomento</a></span                                ></p>
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th width="50%">Descrição</th>
                                                    <th>Submetas</th>
													<th>Núcleos</th>
                                                    <th>Opções</th>
													
												</tr>
											</thead>

											<tbody>
                                                  <?php
											  
												  foreach ($areas as $area){ 
												  
												  ?>
												<tr>
													
													<td><?php echo $area['descricao']; ?></td>
													<td>
                                                    <a href="<?php echo $this->url('submeta/consulta', array('action'=>'consulta', 'area_id'=> $area['id'])); ?>">
                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
													<?php echo $submetas_count[$area['id']]; ?>
                                                    </span>
                                                    </a>
                                                    </td>
                                                    
                                                    <td>
                                                    <a href="<?php echo $this->url('nucleo/consulta', array('action'=>'consulta', 'area_id'=> $area['id'])); ?>">
                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
													<?php echo $nucleo_count[$area['id']]; ?>
                                                    </span>
                                                    </a>
                                                    </td>
													
													<td>
														<div class="hidden-sm hidden-xs btn-group">    

															<a href="<?php echo $this->url('area/edit', array('action'=>'edit', 'id'=> $area['id'])); ?>" class="btn btn-xs btn-info">															
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a>
														</div>
                                                        

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
																	<li>
																		<a href="ver-area/<?php echo $area['id']; ?>" class="tooltip-info" data-rel="tooltip" title="Ver">
																			<span class="blue">
																				<i class="ace-icon fa fa-search-plus bigger-120"></i>
																			</span>
																		</a>
																	</li>
																</ul>
															</div>
														</div>
													</td>
												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->


								<div class="row">
									<div class="col-xs-12">
										
											
										</div><!-- /.modal-content -->
									</div><!-- /.modal-dialog -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
