<div class="main-content">

            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				         window.location.href = "<?php echo $this->url('cumprimento-objeto-atividade/delete', array('action'=>'delete', 'id' => '')); ?>"+id;
				     }
				}
			</script> 	    
			                   
	<div class="main-content-inner">
 					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index')); ?>">Home</a>
							</li>

							<li class="active">Editar Atividade</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->                                        

			<div class="page-content">
						<div class="page-header">
							<h3>
								Cumprimento do Objeto
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div>
                        
                        
						  <?php
									/*
							'<div class="alert alert-success" role="alert" style="display: none;">
						        <strong>Salvo com sucesso!</strong></div>';							
							*/
						  ?>
                        <br /><br />
                        <div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
                                
                                <form class="form-horizontal" role="form" name="form" method="post" action="<?php echo $this->url('cumprimento-objeto/add', array('action' => 'add', 'atividade_id' => $atividade_id)); ?>" enctype="multipart/form-data">
									<!-- #section:elements.form -->
                                         
                                      <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Meta: </label>

										<div class="col-sm-9">                                        
											<input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9"  rows="3" style="width:100%" value="<?php echo $area->descricao; ?>" />
										</div>
									 </div>
									 
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Submeta: </label>

										<div class="col-sm-9">                                        
										<input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9"  rows="3" style="width:100%" value="<?php echo $submeta->codigo; ?>" />
										</div>
									</div>
                                    
                                     
                                      <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Atividade</label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9"  rows="3" style="width:100%" value="<?php echo ($atividade_ptc->atividade); ?>" />										</div>
									</div>
									
										<div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                                O relatório que está sendo gerado é parcial ou de conclusão da atividade?
                                                </label>

												<div class="radio">
													<label>
														<input <?php if ($last_cumprimento_objeto['parcial_total'] == 'p'){ ?> checked="checked" <?php } ?>  type="radio" name="parcial_total" value="p" class="ace" />
														<span class="lbl"> Parcial</span>
													</label>
												&nbsp;&nbsp;
													<label>
														<input <?php if ($last_cumprimento_objeto['parcial_total'] == 't'){ ?> checked="checked" <?php } ?>   type="radio" name="parcial_total" value="t" class="ace" />
														<span class="lbl"> Total</span>
													</label>
												</div>
                                          </div>	
                                          
                                          
                                     <div class="form-group">
											<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 
	                                        Resumo de cumprimento de objeto (Ênfase nos indicadores e artefatos entregues):
	                                        </label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="resumo_relatorio" class="col-xs-10 col-sm-5"  style="width:100%" rows="4"><?php echo ($last_cumprimento_objeto['resumo_relatorio']); ?></textarea>
										</div>
									</div>			                                    
                                   
                                    
                                 	<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data de geração do relatório </label>

										<div class="col-sm-9">
                                        <input type="text" id="form-field-1" OnKeyUp="mascaraData(this);" maxlength="10" name="data_geracao" class="col-xs-10 col-sm-5"  value="<?php echo date('d/m/Y', strtotime($last_cumprimento_objeto['data'])); ?>" />
										</div>
									</div>
                                    
									<script type="text/javascript">
									
									   	function mascaraData(campoData){
									    	var data = data_geracao.value;
										    if (data.length == 2){
											    data = data + '/';
											    document.forms[0].data_geracao.value = data;
											    return true;              
										    }
										    if (data.length == 5){
											    data = data + '/';
											    document.forms[0].datadata_geracao.value = data;
										    	return true;
										    }
									    }
								         
										function pf(){
											document.form.pfisica.style.visibility='visible';
											document.form.pjuridica.style.visibility='hidden';
										}
										
										function pj(){
											document.form.pjuridica.style.visibility='visible';
											document.form.pfisica.style.visibility='hidden';
										}
									
									</script>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                        	Houve alterações na atividade ou cronograma programado e o cumprido? Se sim, justifique.
                                        </label>

										<div class="radio">
											<label>
												<input   <?php if ($last_cumprimento_objeto['atividade_1'] == '1'){ ?> checked="checked" <?php } ?>  type="radio" name="atividade_1" value="1" class="ace"  />
												<span class="lbl"> Sim</span>
											</label>
											&nbsp;&nbsp;
											<label>
												<input id="nao"  <?php if ($last_cumprimento_objeto['atividade_1'] == '0'){ ?> checked="checked" <?php } ?>   type="radio" name="atividade_1" value="0" class="ace" />
												<span class="lbl"> Não</span>
											</label>
                                                    
                                            <div style="padding:5px;">&nbsp; <textarea name="atividade_1_justifique" placeholder="se sim justifique..." style="width:50%"><?php echo ($last_cumprimento_objeto['atividade_1_justifique']); ?></textarea></div>
                                                    
										</div>
                                     </div>
                        
                        					<div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                                	No atual estágio de execução da atividade, há necessidade de mudança na atividade ou cronograma programado? Caso sim propor
                                                </label>

												<div class="radio">
													<label>
														<input   <?php if ($last_cumprimento_objeto['atividade_2'] == '1'){ ?> checked="checked" <?php } ?>  type="radio" name="atividade_2" value="1" class="ace"  />
														<span class="lbl"> Sim</span>
													</label>
													&nbsp;&nbsp;
													<label>
														<input id="nao"  <?php if ($last_cumprimento_objeto['atividade_2'] == '0'){ ?> checked="checked" <?php } ?>   type="radio" name="atividade_2" value="0" class="ace" />
														<span class="lbl"> Não</span>
													</label>
                                                    
                                                    <div style="padding:5px;">&nbsp; <textarea name="atividade_2_justifique" placeholder="Caso sim propor..." style="width:50%"><?php echo ($last_cumprimento_objeto['atividade_2_justifique']); ?></textarea>
                                                    <br /><br />&nbsp;
                                                    <button name="salvar" class="btn btn-info" type="submit">
														<i class="ace-icon fa fa-check bigger-110"></i>
														Salvar
													</button></div>
												</div>
                                          	</div>
                                          	                                    
                                    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>
                                    
								    <script type="text/javascript">
										$(document).ready(function() {
										        
									        $('#projeto_id').change(function() {
									            
									    		var ajax_url = "/uab/projetos/atividade-projeto/get-atividades-projeto/"+$('#projeto_id').val();
									    		//var ajax_url = "/uab/convenio/projeto/listacidade/"+$('#estado').val();
										        
									    		 $.ajax({
									 	            type: "POST",
									 	            url: ajax_url,
									 	            data: "projeto_id="+$(this).val(),
									 	            success: function(msg){ 
									 	                $("#atividade_epe_id").html(msg);
									 	        }
									 	     });     	   
									        });
										});								   
								    </script>
									    
										<br />
										<hr />

									<h2>Atividades:</h2>
                  					<div style="padding:30px; border:2px solid #EEE; background:#EEE;">      
                  						
										<div class="form-group">
											<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Projeto</label>
	
											<div class="col-sm-9">
	                                            <select  class="form-control"  name="projeto_id" id="projeto_id" >
	                                            <option></option>
	                                            <?php foreach($projetos_ativos as $projeto){ ?>		  
	                                            <option value="<?php echo $projeto['id']; ?>"><?php echo ($projeto['meta']); ?> - <?php echo ($projeto['descricao']); ?></option>
	                                            <?php } ?>	  
	                                            </select>
											</div>
										</div>
                                    
		                                <div class="form-group">
			                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Atividade</label>
			                                <div class="col-sm-9">			                                
			                                	<div id="nucleo"></div>			                                	
												<select class='form-control'  name='atividade_epe_id[]' id='atividade_epe_id' multiple='multiple' style='height:200px'>
												</select>
			                                </div>
		                                </div>          
		                                
		                                <div class="form-group">
			                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"></label>
			                                <div class="col-sm-9">			                                
		                                		<input type='submit' value='+ adicionar atividades' formaction="<?php echo $this->url('cumprimento-objeto-atividade/add', array('action' => 'add', 'atividade_id' => $atividade_id)); ?>">
		                                    </div>
		                                </div>          
		                                
                                
	                                	<div class="form-group">
											<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp;</label>
	
											<div class="col-sm-9">
		                                        <table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">
		                                        	<thead>
			                                         	<tr>
				                                          <th width="80%">Atividades</th>
				                                          <th>Opções</th>
			                                          	</tr>
		                                          	</thead>
													 <tbody>
			                                         <?php 	foreach($cumprimento_objeto_atividades as $cumprimento_objeto_atividade){ ?>
				                                         <tr>
					                                           <th><?php echo ($atividades_projeto[$cumprimento_objeto_atividade['atividade_epe_id']]);?><br />
					                                           		<small><strong>Projeto</strong>: <?php echo ($projetos[$cumprimento_objeto_atividade['area_id']]['descricao']);?></small><br /><?php echo ($projetos[$cumprimento_objeto_atividade['area_id']]['meta']); ?>
					                                           </th>
					
					                                           <th>
						                                           	<div class="hidden-sm hidden-xs btn-group">                                                      
						                                           		<a href="javascript:func()" onclick="confirmacao('<?php echo $cumprimento_objeto_atividade['id']?>')" >
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
						                                                    </span>
																		</a>
																	</div>
																	<div class="hidden-md hidden-lg">
																		<div class="inline pos-rel">
																			<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																				<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																			</button>
					
																			<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
																				<li>
																					<a href="javascript:func()" onclick="confirmacao('<?php echo $cumprimento_objeto_atividade['id']?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
			                                                							<span class="red">
																							<i class="ace-icon fa fa-trash-o bigger-120"></i>
																						</span>
																					</a>
																				</li>                                                                    
																			</ul>
																		</div>
																	</div>
																</th>
				                                          </tr>
			                                        <?php } ?>
													 </tbody>
		                                        </table>                                          
											</div>
										</div>                                    
                                 	</div> 
                                 	  
                                    <br />
									<hr /><br />
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Descreva as principais ações executadas para a realização da atividade do PTC (procedimento, método ou processo)</label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="acoes_executadas" rows="7" style="width:100%" class="col-xs-10 col-sm-5"  /><?php echo ($last_cumprimento_objeto['acoes_executadas']); ?></textarea>
											<p>
				                           <button name="salvar" class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button></p>
										</div>
									</div>
							        <br />
							<hr /><br />
							<h2>Artefatos:</h2>
                         <div style="padding:30px; border:2px solid #EEE; background:#EEE;">           
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">Selecione tipos de artefatos, anexe arquivos comprobatórios e faça uma breve descrição sobre o artefato anexado:</label>

										<div class="col-sm-3">
                                        
                                            <select  class="form-control" name="tipo"  >
                                            <option></option>
                                            <option>Declarações assinadas pelo interlocutor do projeto</option>
                                            <option>Relatório de realização de capacitação</option>
                                            <option>Atas de reuniões realizadas</option>
                                            <option>Relatório técnico</option>
                                            <option>Relatório de consultor</option>
                                            <option>Fotografia</option>
                                            <option>Ilustrações (folders, imagens de jornal, revista, sites, impressão de telas de sistema).</option>
                                            <option>Outros</option>
                                            </select></div>
                                        <div class="col-sm-3">
                                           <input type="file" name="arquivo" value="enviar" />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Informe o nome padrão do artefato (até 60 posições)</label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="descricao" rows="3" style="width:100%" class="col-xs-10 col-sm-5"  /></textarea>
										</div>
									</div>
                                    
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                        Informe uma breve legenda (Caso de ilustrações, fotografias ou títulos para relatórios)
                                        </label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="legenda" rows="3" style="width:100%" class="col-xs-10 col-sm-5"  /></textarea>
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Digite a data em que o artefato foi concebido ou registrado </label>

										<div class="col-sm-3">
                                        <input type="text" id="form-field-1" OnKeyUp="mascaraData(this);" maxlength="10" name="data" class="col-xs-10 col-sm-5"  value="" />
										</div>
									</div>
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> local em que o artefato foi concebido ou registrado.</label>

										<div class="col-sm-9">
                                        <input type="text" id="form-field-1"  maxlength="10" name="local" class="col-xs-10 col-sm-9"  value="" />
                                        <br />

										</div>
									</div>
                                    
                                   	<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"></label>

										<div class="col-sm-9">
                                        &nbsp;<input formaction="<?php echo $this->url('artefato/add', array('action' => 'add', 'atividade_id' => $atividade_id)); ?>" type="submit" value="+ adicionar artefato" name="artefato" />
                                        <br />

										</div>
									</div>
                                    
                                    
                                    
                                   <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp;</label>
	                                    <div class="col-sm-9">
	                                        <table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">
	                                        	<thead>
		                                         <tr>
		                                          	<th width="80%" colspan="3">Artefatos</th>
		                                           	<th>Opções</th>
		                                          </tr>
	                                          	</thead>
											 	<tbody>
	                                         <?php 
	                                         
	                                         /* Diretorio Local */
	                                         $dir = __DIR__;
	                                         $dir = str_replace("\\", '/', $dir);
	                                         $dir = explode("projetos", $dir);
	                                         /* Diretorio Local */
	                                          
	                                         $dir = $dir[0].'projetos/public/artefatos/';
	                                         
	                                         		foreach ($artefatos as $artefato){ 	                                         
	                                         ?>
		                                         <tr>
		                                          	<th><?php echo ($artefato['tipo']); ?></th>
		                                           	<th><?php echo ($artefato['descricao']); ?></th>
		                                           	<th><?php echo date('d/m/Y',  strtotime($artefato['data'])); ?></th>                                           
		                                           	<th>
			                                           	<a href="<?php echo $this->basePath('public/artefatos/'.$artefato['arquivo']); ?>" target="_blank">
			                                           		<span class="blue"><i class="ace-icon fa fa-download bigger-120"></i></span>
		                                           		</a>
		                                           &nbsp;&nbsp;
		                                           		<a href="<?php echo $this->url('artefato/delete', array('action' => 'delete', 'atividade_id' => $atividade_id, 'id' => $artefato['id'])); ?>">
		                                           			<span class="red"><i class="ace-icon fa fa-trash-o bigger-120"></i></span>
		                                           		</a>
		                                           	</th>
		                                        </tr>
	                                          <?php } ?>
											 	</tbody>
	                                        </table>                                          
										</div>
									</div>
                                    
                                    </div>
                                    <br />
<hr /><br />
                                    	<br />
										<hr /><br />
                                          	                                          	                                    
	                                    <div class="form-group">
											<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Qual é a avaliação da atividade até o momento:</label>
	
											<div class="col-sm-9">
												<textarea id="form-field-1" name="avaliacao" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['avaliacao']); ?></textarea>
											</div>
										</div>
                                    
                                         <div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                                Os quantitativos descritos nas atividades (indicadores físicos ou de desempenho) foram executados de acordo com o programado? Se negativo justificar</label>

												<div class="radio">
													<label>
														<input   <?php if ($last_cumprimento_objeto['quantitativos_executados'] == '1'){ ?> checked="checked" <?php } ?>  type="radio" name="quantitativos_executados" value="1" class="ace"  />
														<span class="lbl"> Sim</span>
													</label>
												&nbsp;&nbsp;
													<label>
														<input id="nao"  <?php if ($last_cumprimento_objeto['quantitativos_executados'] == '0'){ ?> checked="checked" <?php } ?>   type="radio" name="quantitativos_executados" value="0" class="ace" />
														<span class="lbl"> Não</span>
													</label>
                                                    
                                                    <div style="padding:5px;">&nbsp; <textarea name="quantitativos_executados_justifique" placeholder="se sim justifique..." style="width:50%"><?php echo ($last_cumprimento_objeto['quantitativos_executados_justifique']); ?></textarea></div>
                                                    
												</div>
                                          </div>
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Fale sobre os principais resultados ou contribuições da atividade para o contexto de Ensino, Pesquisa ou Extensão da UFMT</label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="principais_resultados" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['principais_resultados']); ?></textarea>
										</div>
									</div>
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Comentar (se houver) restrições que impediram o fiel desempenho da atividade em conformidade com o planejado</label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="restricoes" rows="3" style="width:100%" class="col-xs-10 col-sm-5"><?php echo ($last_cumprimento_objeto['restricoes']); ?></textarea>
										</div>
									</div>
                                          	
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button name="salvar" class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
                                




                             </div>
                         </div>
                        
                        
                        <!-- /.page-header -->
                        </div>
                    

