<?php

ini_set('display_errors', 0);
ini_set('log_errors', 0);
error_reporting(E_ALL);
session_start();
setlocale(LC_ALL, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Cuiaba');

use Zend\Session\Container;

if (defined('RUNNING_FROM_ROOT')) {
	$this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}

$usuario_dados = new Container('usuario_dados');
?>

<!DOCTYPE html>
<html lang="pt_br">

<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('STI UFMT ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath('css/bootstrap.css'))
		->prependStylesheet($this->basePath('css/font-awesome.css'))
		->prependStylesheet($this->basePath('css/ace-fonts.css'))
		->prependStylesheet($this->basePath('css/ace.css')) ?>

	<link href="<?php echo $this->basePath('js/chosen/chosen.css'); ?>" rel="stylesheet">
	<style type="text/css" media="all">
		/* fix rtl for demo */
		.chosen-rtl .chosen-drop {
			left: -9000px;
		}
	</style>


	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo $this->basePath('css/ace.css'); ?>" class="ace-main-stylesheet" id="main-ace-style" />

	<!-- Le script -->
	<?php echo $this->headScript()
		->prependFile($this->basePath('js/ace-extra.js'))
		->prependFile($this->basePath('js/ckeditor/ckeditor.js')); ?>

</head>

<body class="no-skin">
	<!-- #section:basics/navbar.layout -->
	<div id="navbar" class="navbar navbar-default">
		<script type="text/javascript">
			try {
				ace.settings.check('navbar', 'fixed')
			} catch (e) {}
		</script>

		<div class="navbar-container" id="navbar-container">
			<!-- #section:basics/sidebar.mobile.toggle -->
			<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
				<span class="sr-only">Toggle sidebar</span>

				<span class="icon-bar"></span>

				<span class="icon-bar"></span>

				<span class="icon-bar"></span>
			</button>

			<!-- /section:basics/sidebar.mobile.toggle -->
			<div class="navbar-header pull-left">
				<!-- #section:basics/navbar.layout.brand -->
				<a href="" class="navbar-brand">
					<small>
						<!--img src="<?php //$root;
										?>logo.png"-->
					</small>
				</a>

				<!-- /section:basics/navbar.layout.brand -->

				<!-- #section:basics/navbar.toggle -->

				<!-- /section:basics/navbar.toggle -->
			</div>

			<!-- #section:basics/navbar.dropdown -->
			<div class="navbar-buttons navbar-header pull-right" role="navigation">
				<ul class="nav ace-nav">
					<li class="grey">
						<?php $nome = explode(" ", $usuario_dados->nome);
						$firstname = $nome[0];
						unset($nome[0]);
						$lastname = implode(" ", $nome); ?>
						<a href="https://setec.ufmt.br/tce/ava-tce/logar.php?username=<?= base64_encode($usuario_dados->cpf); ?>&firstname=<?= base64_encode($firstname); ?>&lastname=<?= base64_encode($lastname); ?>&email=<?= base64_encode($usuario_dados->email); ?>" target="_blank">
							<!-- <a  href="http://setec.ufmt.br/tce/ava-tce/logar.php?username=<?= base64_encode($usuario_dados->cpf); ?>&firstname=<?= base64_encode($firstname); ?>&lastname=<?= base64_encode($lastname); ?>&email=<?= base64_encode($usuario_dados->email); ?>" target="_blank"> -->
							<i class="ace-icon fa fa-graduation-cap"></i>
							<!--span class="badge badge-grey">4</span-->
						</a>
					</li>


					<!-- #section:basics/navbar.user_menu -->
					<li class="light-green">
						<a data-toggle="dropdown" href="#" class="dropdown-toggle">
							<img class="nav-user-photo" src="<?php echo $this->basePath('avatars/user.jpg'); ?>" alt="Jason's Photo" />
							<span class="user-info">
								<small>Olá,</small>
								<?php echo	$usuario_dados->nome; ?>
							</span>

							<i class="ace-icon fa fa-caret-down"></i>
						</a>

						<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">


							<li>
								<a href="<?php echo $this->url('login', array('action' => 'meusdados')); ?>">
									<i class="ace-icon fa fa-user"></i>
									Meus dados
								</a>
							</li>

							<li>
								<a href="<?php echo $this->url('login', array('action' => 'changepassword')); ?>">
									<i class="ace-icon fa fa-lock"></i>
									Alterar senha
								</a>
							</li>

							<li class="divider"></li>

							<li>
								<a href="<?php echo $this->url('login', array('action' => 'sair')); ?>">
									<i class="ace-icon fa fa-power-off"></i>
									Sair
								</a>
							</li>
						</ul>
					</li>

					<!-- /section:basics/navbar.user_menu -->
				</ul>
			</div>

			<!-- /section:basics/navbar.dropdown -->
		</div><!-- /.navbar-container -->
	</div>

	<!-- /section:basics/navbar.layout -->
	<div class="main-container" id="main-container">
		<script type="text/javascript">
			try {
				ace.settings.check('main-container', 'fixed')
			} catch (e) {}
		</script>

		<!-- #section:basics/sidebar -->
		<div id="sidebar" class="sidebar responsive">
			<script type="text/javascript">
				try {
					ace.settings.check('sidebar', 'fixed')
				} catch (e) {}
			</script>

			<ul class="nav nav-list">
				<li <?php //if ($_GET['p'] == ''){ echo "class='active'"; } 
					?>>
					<a href="<?php echo $this->url('home', array('action' => 'index')); ?>">
						<i class="menu-icon fa fa-home"></i>
						<span class="menu-text"> Home </span>
					</a>

					<b class="arrow"></b>
				</li>

				<?php if (in_array('area', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'listar-areas') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('area', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-list-alt"></i>
							<span class="menu-text"> Áreas</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>

				<?php if (in_array('representante', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'listar-representante-tce') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('representante', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-user"></i>
							<span class="menu-text">Representantes</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>

				<?php if (in_array('funcao', $usuario_dados->funcionalidades_usuario)) { ?>
					<li>
						<a href="<?php echo $this->url('funcao', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-list"></i>
							<span class="menu-text">Funções</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>


				<?php if (in_array('bonificacao', $usuario_dados->funcionalidades_usuario)) { ?>
					<li>
						<a href="<?php echo $this->url('bonificacao', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-list"></i>
							<span class="menu-text">Bonificações</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>

				<?php if (in_array('bolsa', $usuario_dados->funcionalidades_usuario)) { ?>
					<li>
						<a href="<?php echo $this->url('bolsa', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-list"></i>
							<span class="menu-text">Bolsas</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>



				<?php if (in_array('colaborador', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'colaborador') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('colaborador', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-user"></i>
							<span class="menu-text"> Colaboradores</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>





				<?php if (in_array('participante', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'participante') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('participante', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-user"></i>
							<span class="menu-text"> Beneficiários</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>


				<?php if (in_array('projeto', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'listar-projeto') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('projeto', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-list-alt"></i>
							<span class="menu-text"> Projetos</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>

				<?php if (in_array('atividade-ptc', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'plano-de-trabalho') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('atividade-ptc', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-book"></i>
							<span class="menu-text"> Plano de Trabalho</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>

				<?php if (in_array('relatorio-colaborador', $usuario_dados->funcionalidades_usuario) || in_array('relatorio-cumprimento-objeto', $usuario_dados->funcionalidades_usuario)) { ?>
					<li>
						<a href="#" class="dropdown-toggle">
							<i class="menu-icon fa fa-list"></i>
							<span class="menu-text"> Relatórios </span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<?php if (in_array('relatorio-colaborador', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador', array('action' => 'index')); ?>">
										<i class="menu-icon fa fa-caret-right"></i>
										Colaborador
									</a>

									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (in_array('relatorio-colaborador/funcoes', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador/funcoes', array('action' => 'index')); ?>?t=1">
										<i class="fa fa-download" aria-hidden="true"></i>
										Funções - CLT
									</a>
									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (in_array('relatorio-colaborador/funcoes', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador/funcoes', array('action' => 'index')); ?>?t=2">
										<i class="fa fa-download" aria-hidden="true"></i>
										Funções - Bolsista
									</a>
									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (in_array('relatorio-colaborador/bolsista', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador/bolsista', array('action' => 'index')); ?>">
										<i class="fa fa-download" aria-hidden="true"></i>
										Bolsista
									</a>
									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (in_array('relatorio-colaborador/bonificacoes', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador/bonificacoes', array('action' => 'index')); ?>">
										<i class="fa fa-download" aria-hidden="true"></i>
										Bonificações
									</a>
									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (in_array('relatorio-colaborador/atividade-mensal', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador/atividade-mensal', array('action' => 'index')); ?>">
										<i class="menu-icon fa fa-caret-right"></i>
										Atividade Mensal Colaborador
									</a>

									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (
								(in_array('relatorio-colaborador/ver-relatorio-estagiarios', $usuario_dados->funcionalidades_usuario) and ($usuario_dados->id == 1079))
								or
								($usuario_dados->permissao == 8)
							) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-colaborador/ver-relatorio-estagiarios', array('action' => 'index')); ?>">
										<i class="menu-icon fa fa-caret-right"></i>
										Estagiários
									</a>

									<b class="arrow"></b>
								</li>
							<?php } ?>

							<?php if (in_array('relatorio-cumprimento-objeto', $usuario_dados->funcionalidades_usuario)) { ?>
								<li class="">
									<a href="<?php echo $this->url('relatorio-cumprimento-objeto', array('action' => 'index')); ?>">
										<i class="menu-icon fa fa-caret-right"></i>
										Cumprimento do Objeto
									</a>

									<b class="arrow"></b>
								</li>
							<?php } ?>

						</ul>
					</li>
				<?php } ?>


				<?php if (in_array('projeto/meus-projetos', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'meus-projetos') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('projeto/meus-projetos', array('action' => 'meus-projetos')); ?>">
							<i class="menu-icon fa fa-list-alt"></i>
							<span class="menu-text"> Meus projetos</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>


				<?php if (in_array('colaborador/folha-ponto', $usuario_dados->funcionalidades_usuario)) { ?>
					<li>
						<a href="<?php echo $this->url('colaborador/folha-ponto', array('action' => 'folha-ponto')); ?>">
							<i class="menu-icon fa fa-list-alt"></i>
							<span class="menu-text"> Folha de ponto</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>



				<?php if (in_array('perfil-acesso', $usuario_dados->funcionalidades_usuario)) { ?>
					<li <?php if ($_GET['p'] == 'meus-projetos') {
							echo "class='active'";
						} ?>>
						<a href="<?php echo $this->url('perfil-acesso', array('action' => 'index')); ?>">
							<i class="menu-icon fa fa-list-alt"></i>
							<span class="menu-text"> Perfil de Acesso</span>
						</a>

						<b class="arrow"></b>
					</li>
				<?php } ?>

				<li>
					<a href="#" class="dropdown-toggle">
						<i class="menu-icon fa fa-list"></i>
						<span class="menu-text"> Uniselva </span>

						<b class="arrow fa fa-angle-down"></b>
					</a>

					<b class="arrow"></b>

					<ul class="submenu">

						<?php if (in_array('colaborador/uniselva', $usuario_dados->funcionalidades_usuario)) { ?>
							<li>
								<a href="<?php echo $this->url('colaborador/uniselva', array('action' => 'colaborador/uniselva')); ?>">

									<span class="menu-text"> Colaboradores</span>
								</a>

								<b class="arrow"></b>
							</li>
						<?php } ?>

						<?php if (in_array('ferias', $usuario_dados->funcionalidades_usuario)) { ?>
							<li>
								<a href="<?php echo $this->url('ferias', array('action' => 'index')); ?>">

									<span class="menu-text"> Férias</span>
								</a>

								<b class="arrow"></b>
							</li>
						<?php } ?>
					</ul>
				</li>



			</ul><!-- /.nav-list -->

			<!-- #section:basics/sidebar.layout.minimize -->
			<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
				<i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
			</div>

			<!-- /section:basics/sidebar.layout.minimize -->
			<script type="text/javascript">
				try {
					ace.settings.check('sidebar', 'collapsed')
				} catch (e) {}
			</script>
		</div>



		<?php echo $this->content; ?>



		<div class="footer">
			<div class="footer-inner">
				<!-- #section:basics/footer -->
				<div class="footer-content">
					<span>
						<!-- <span class="green bolder">IMPLEMENTAÇÃO DOS PROGRAMAS DE MODERNIZAÇÃO DO TCE-MT</span><br>
							 MELHORIA DOS PROCESSOS INTERNOS, TI E EAD -->
					</span>

				</div>

				<!-- /section:basics/footer -->
			</div>
		</div>

		<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
			<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
		</a>
	</div><!-- /.main-container -->
	<!-- basic scripts -->



	<?php echo $this->inlineScript() ?>








	<!--[if !IE]> -->
	<script type="text/javascript">
		window.jQuery || document.write("<script src='<?php echo $this->basePath('js/jquery.js'); ?>'>" + "<" + "/script>");
	</script>

	<!-- <![endif]-->

	<!--[if IE]>
		<script type="text/javascript">
		 window.jQuery || document.write("<script src='assets/js/jquery1x.js'>"+"<"+"/script>");
		</script>
		<![endif]-->

	<script type="text/javascript">
		if ('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath('js/jquery.mobile.custom.js'); ?>'>" + "<" + "/script>");
	</script>
	<script src="<?php echo $this->basePath('js/bootstrap.js'); ?>"></script>

	<!-- page specific plugin scripts -->

	<!--[if lte IE 8]>
		  <script src="assets/js/excanvas.js"></script>
		<![endif]-->
	<script src="<?php echo $this->basePath('js/jquery-ui.custom.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/jquery.ui.touch-punch.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/jquery.ui.touch-punch.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/jquery.sparkline.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/flot/jquery.flot.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/flot/jquery.flot.pie.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/flot/jquery.flot.resize.js'); ?>"></script>

	<!-- ace scripts -->
	<script src="<?php echo $this->basePath('js/ace/elements.scroller.js'); ?>"></script>
	<script src="<?php echo $this->basePath('assets/js/ace/elements.colorpicker.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.fileinput.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.typeahead.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.wysiwyg.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.spinner.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.treeview.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.wizard.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/elements.aside.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.ajax-content.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.touch-drag.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.sidebar.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.sidebar-scroll-1.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.submenu-hover.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.widget-box.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.settings.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.settings-rtl.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.settings-skin.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.widget-on-reload.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.searchbox-autocomplete.js'); ?>"></script>


	</script>
	<!-- inline scripts related to this page -->
	<script type="text/javascript">
		jQuery(function($) {
			$('.easy-pie-chart.percentage').each(function() {
				var $box = $(this).closest('.infobox');
				var barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');
				var trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';
				var size = parseInt($(this).data('size')) || 50;
				$(this).easyPieChart({
					barColor: barColor,
					trackColor: trackColor,
					scaleColor: false,
					lineCap: 'butt',
					lineWidth: parseInt(size / 10),
					animate: /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,
					size: size
				});
			})

			$('.sparkline').each(function() {
				var $box = $(this).closest('.infobox');
				var barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';
				$(this).sparkline('html', {
					tagValuesAttribute: 'data-values',
					type: 'bar',
					barColor: barColor,
					chartRangeMin: $(this).data('min') || 0
				});
			});


			//flot chart resize plugin, somehow manipulates default browser resize event to optimize it!
			//but sometimes it brings up errors with normal resize event handlers
			$.resize.throttleWindow = false;

			var placeholder = $('#piechart-placeholder').css({
				'width': '90%',
				'min-height': '150px'
			});
			var data = [{
					label: "social networks",
					data: 38.7,
					color: "#68BC31"
				},
				{
					label: "search engines",
					data: 24.5,
					color: "#2091CF"
				},
				{
					label: "ad campaigns",
					data: 8.2,
					color: "#AF4E96"
				},
				{
					label: "direct traffic",
					data: 18.6,
					color: "#DA5430"
				},
				{
					label: "other",
					data: 10,
					color: "#FEE074"
				}
			]

			function drawPieChart(placeholder, data, position) {
				$.plot(placeholder, data, {
					series: {
						pie: {
							show: true,
							tilt: 0.8,
							highlight: {
								opacity: 0.25
							},
							stroke: {
								color: '#fff',
								width: 2
							},
							startAngle: 2
						}
					},
					legend: {
						show: true,
						position: position || "ne",
						labelBoxBorderColor: null,
						margin: [-30, 15]
					},
					grid: {
						hoverable: true,
						clickable: true
					}
				})
			}
			drawPieChart(placeholder, data);

			/**
			we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically
			so that's not needed actually.
			*/
			placeholder.data('chart', data);
			placeholder.data('draw', drawPieChart);


			$('[data-rel=tooltip]').tooltip();
			$('[data-rel=popover]').popover({
				html: true
			});

			//pie chart tooltip example
			var $tooltip = $("<div class='tooltip top in'><div class='tooltip-inner'></div></div>").hide().appendTo('body');
			var previousPoint = null;

			placeholder.on('plothover', function(event, pos, item) {
				if (item) {
					if (previousPoint != item.seriesIndex) {
						previousPoint = item.seriesIndex;
						var tip = item.series['label'] + " : " + item.series['percent'] + '%';
						$tooltip.show().children(0).text(tip);
					}
					$tooltip.css({
						top: pos.pageY + 10,
						left: pos.pageX + 10
					});
				} else {
					$tooltip.hide();
					previousPoint = null;
				}

			});

			/////////////////////////////////////
			$(document).one('ajaxloadstart.page', function(e) {
				$tooltip.remove();
			});




			var d1 = [];
			for (var i = 0; i < Math.PI * 2; i += 0.5) {
				d1.push([i, Math.sin(i)]);
			}

			var d2 = [];
			for (var i = 0; i < Math.PI * 2; i += 0.5) {
				d2.push([i, Math.cos(i)]);
			}

			var d3 = [];
			for (var i = 0; i < Math.PI * 2; i += 0.2) {
				d3.push([i, Math.tan(i)]);
			}


			var sales_charts = $('#sales-charts').css({
				'width': '100%',
				'height': '220px'
			});
			$.plot("#sales-charts", [{
					label: "Domains",
					data: d1
				},
				{
					label: "Hosting",
					data: d2
				},
				{
					label: "Services",
					data: d3
				}
			], {
				hoverable: true,
				shadowSize: 0,
				series: {
					lines: {
						show: true
					},
					points: {
						show: true
					}
				},
				xaxis: {
					tickLength: 0
				},
				yaxis: {
					ticks: 10,
					min: -2,
					max: 2,
					tickDecimals: 3
				},
				grid: {
					backgroundColor: {
						colors: ["#fff", "#fff"]
					},
					borderWidth: 1,
					borderColor: '#555'
				}
			});


			$('#recent-box [data-rel="tooltip"]').tooltip({
				placement: tooltip_placement
			});

			function tooltip_placement(context, source) {
				var $source = $(source);
				var $parent = $source.closest('.tab-content')
				var off1 = $parent.offset();
				var w1 = $parent.width();

				var off2 = $source.offset();
				//var w2 = $source.width();

				if (parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2)) return 'right';
				return 'left';
			}


			$('.dialogs,.comments').ace_scroll({
				size: 300
			});


			//Android's default browser somehow is confused when tapping on label which will lead to dragging the task
			//so disable dragging when clicking on label
			var agent = navigator.userAgent.toLowerCase();
			if ("ontouchstart" in document && /applewebkit/.test(agent) && /android/.test(agent))
				$('#tasks').on('touchstart', function(e) {
					var li = $(e.target).closest('#tasks li');
					if (li.length == 0) return;
					var label = li.find('label.inline').get(0);
					if (label == e.target || $.contains(label, e.target)) e.stopImmediatePropagation();
				});

			$('#tasks').sortable({
				opacity: 0.8,
				revert: true,
				forceHelperSize: true,
				placeholder: 'draggable-placeholder',
				forcePlaceholderSize: true,
				tolerance: 'pointer',
				stop: function(event, ui) {
					//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved
					$(ui.item).css('z-index', 'auto');
				}
			});
			$('#tasks').disableSelection();
			$('#tasks input:checkbox').removeAttr('checked').on('click', function() {
				if (this.checked) $(this).closest('li').addClass('selected');
				else $(this).closest('li').removeClass('selected');
			});


			//show the dropdowns on top or bottom depending on window height and menu position
			$('#task-tab .dropdown-hover').on('mouseenter', function(e) {
				var offset = $(this).offset();

				var $w = $(window)
				if (offset.top > $w.scrollTop() + $w.innerHeight() - 100)
					$(this).addClass('dropup');
				else $(this).removeClass('dropup');
			});

		})
	</script>
	<script src="<?php echo $this->basePath('js/chosen/chosen.jquery.js'); ?>" type="text/javascript"></script>
	<script type="text/javascript">
		var config = {
			'.chosen-select': {},
			'.chosen-select-deselect': {
				allow_single_deselect: true
			},
			'.chosen-select-no-single': {
				disable_search_threshold: 10
			},
			'.chosen-select-no-results': {
				no_results_text: 'Oops, nothing found!'
			},
			'.chosen-select-width': {
				width: "95%"
			}
		}
		for (var selector in config) {
			$(selector).chosen(config[selector]);
		}
	</script>

	<!-- the following scripts are used in demo only for onpage help and you don't need them -->
	<link rel="stylesheet" href="<?php echo $this->basePath('css/ace.onpage-help.css'); ?>" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
	<script type="text/javascript">
		ace.vars['base'] = '..';
	</script>
	<script src="<?php echo $this->basePath('js/ace/elements.onpage-help.js'); ?>"></script>
	<script src="<?php echo $this->basePath('js/ace/ace.onpage-help.js'); ?>"></script>


</body>

</html>