<div class="main-content">

    <script language="Javascript">
        function confirmacao(id) {
            var resposta = confirm("Deseja remover esse registro?");

            if (resposta == true) {
                window.location.href = "<?php echo $this->url('cumprimento-objeto-atividade/delete', array('action' => 'delete', 'id' => '')); ?>" + id;
            }
        }
    </script>

    <!-- TAB 2 -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            $(document).ready(function() {
                $('#projeto_id').change(function() {
                    $.post("/tce/convenio22/atividade-projeto/get-atividades-projeto/" + $('#projeto_id').val(), {
                        projeto_id: "" + $('#projeto_id').val()
                    }, function(data) {
                        $("#atividade_epe_id").html(data);
                    });

                });
            });
        };
    </script>

    <div class="main-content-inner">
        <!-- #section:basics/content.breadcrumbs -->
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try {
                    ace.settings.check('breadcrumbs', 'fixed')
                } catch (e) {}
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="<?php echo $this->url('home', array('action' => 'index')); ?>">Home</a>
                </li>

                <li class="active">Editar Atividade</li>
            </ul><!-- /.breadcrumb -->


            <!-- /section:basics/content.searchbox -->
        </div>

        <!-- /section:basics/content.breadcrumbs -->

        <div class="page-content">
            <div class="page-header">
                <h3>
                    Cumprimento do Objeto
                    <!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
                </h3>
            </div>
            <style>
                @import url('https://fonts.googleapis.com/css?family=Open+Sans:400,600,700');
                @import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');

                *,
                *:before,
                *:after {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }



                h1 {
                    padding: 50px 0;
                    font-weight: 400;
                    text-align: center;
                }

                p {
                    margin: 0 0 20px;
                    line-height: 1.5;
                }

                main {
                    min-width: 320px;
                    /*max-width: 800px;*/

                    margin: 0 auto;
                    background: #fff;
                }

                section {
                    display: none;
                    padding: 20px 0 0;
                    border-top: 1px solid #ddd;
                }

                input[type=checkbox] {
                    display: none;
                }

                label {
                    display: inline-block;
                    margin: 0 0 -1px;
                    padding: 15px 25px;
                    font-weight: 600;
                    text-align: center;
                    color: #bbb;
                    border: 1px solid transparent;
                }

                label:before {
                    font-family: fontawesome;
                    font-weight: normal;
                    margin-right: 10px;
                }

                /*label[for*='1']:before { content: '\f1cb'; }*/
                /*label[for*='2']:before { content: '\f17d'; }*/
                /*label[for*='3']:before { content: '\f16b'; }*/
                /*label[for*='4']:before { content: '\f1a9'; }*/

                label:hover {
                    color: #888;
                    cursor: pointer;
                }

                input:checked+label {
                    color: #555;
                    border: 1px solid #ddd;
                    border-top: 2px solid orange;
                    border-bottom: 1px solid #fff;
                }

                #tab1:checked~#content1,
                #tab2:checked~#content2,
                #tab3:checked~#content3,
                #tab4:checked~#content4 {
                    display: block;
                }

                @media screen and (max-width: 650px) {
                    label {
                        font-size: 0;
                    }

                    label:before {
                        margin: 0;
                        font-size: 18px;
                    }
                }

                @media screen and (max-width: 90%) {
                    label {
                        padding: 15px;
                    }
                }
            </style>



            <main>

                <input style="display:none" id="tab1" type="radio" name="tabs" checked>
                <label for="tab1">Informações gerais</label>

                <input style="display:none" id="tab2" type="radio" name="tabs">
                <label for="tab2">Atividades EPE</label>

                <input style="display:none" id="tab3" type="radio" name="tabs">
                <label for="tab3">Adicionar artefatos</label>

                <!--                    <input id="tab4" type="radio" name="tabs">-->
                <!--                    <label for="tab4">Drupal</label>-->

                <section id="content1">
                    <p>

                    <form class="form-horizontal" role="form" name="form" method="post" action="<?php echo $this->url('cumprimento-objeto/add', array('action' => 'add', 'atividade_id' => $atividade_id)); ?>" enctype="multipart/form-data">
                        <!-- #section:elements.form -->

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Área: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9" rows="3" style="width:100%" value="<?php echo $area->descricao; ?>" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Meta: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9" rows="3" style="width:100%" value="<?php echo $submeta->descricao; ?>" />
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Código da etapa</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9" rows="3" style="width:100%" value="<?php echo ($atividade_ptc->etapa); ?>" />
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Descrição da etapa</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" disabled="disabled" class="col-xs-10 col-sm-9" rows="3" style="width:100%" value="<?php echo ($atividade_ptc->atividade); ?>" />
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Previs&atilde;o Inicio </label>

                            <div class="col-sm-9">
                                <input <?php if ($usuario_dados->permissao != 8) { ?> disabled="disabled" <?php } ?> type="text" id="form-field-1" OnKeyUp="mascaraData3(this);" maxlength="10" name="inicio" class="col-xs-10 col-sm-5" value="<?php if ($atividade_ptc->inicio != "0000-00-00") {
                                                                                                                                                                                                                                                    echo date('d/m/Y', strtotime($atividade_ptc->inicio));
                                                                                                                                                                                                                                                } ?>" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Previs&atilde;o Fim</label>

                            <div class="col-sm-9">
                                <input <?php if ($usuario_dados->permissao != 8) { ?> disabled="disabled" <?php } ?> value="<?php if ($atividade_ptc->fim != "0000-00-00") {
                                                                                                                                echo date('d/m/Y', strtotime($atividade_ptc->fim));
                                                                                                                            } ?>" type="text" id="form-field-1" OnKeyUp="mascaraData4(this);" name="fim" class="col-xs-10 col-sm-5" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Indicador Físico - <small>Unid</small></label>

                            <div class="col-sm-9">
                                <input <?php if ($usuario_dados->permissao != 8) { ?> disabled="disabled" <?php } ?> type="text" id="form-field-1" name="indicador_unid" class="col-xs-10 col-sm-5" value="<?php echo ($atividade_ptc->indicador_unid); ?>" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Indicador Físico - <small>Quant</small></label>

                            <div class="col-sm-9">
                                <input <?php if ($usuario_dados->permissao != 8) { ?> disabled="disabled" <?php } ?> type="text" id="form-field-1" name="indicador_quant" class="col-xs-10 col-sm-5" value="<?php echo ($atividade_ptc->indicador_quant); ?>" />
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Produtos obtidos (Descrição do coordenador de núcleo sobre os produtos entregues)</label>

                            <div class="col-sm-9">
                                <textarea id="form-field-1" name="produtos_esperados" rows="7" style="width:100%" class="col-xs-10 col-sm-5"><?php echo ($last_cumprimento_objeto['produtos_esperados']); ?></textarea>
                            </div>
                        </div>
                        <br /><br />


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Resultados obtidos - (Descrição do coordenador de núcleo sobre os produtos entregues)</label>

                            <div class="col-sm-9">
                                <textarea id="form-field-1" name="resultados_esperados" rows="7" style="width:100%" class="col-xs-10 col-sm-5"><?php echo ($last_cumprimento_objeto['resultados_esperados']); ?></textarea>
                            </div>
                        </div>





                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Status</label>

                            <div class="radio">
                                <label>
                                    <input <?php if ($atividade_ptc->status == '1') { ?> checked="checked" <?php } ?> type="radio" name="status" value="1" class="ace" />
                                    <span class="lbl"> Concluido</span>
                                </label>
                                &nbsp;&nbsp;
                                <label>
                                    <input <?php if ($atividade_ptc->status == '2') { ?> checked="checked" <?php } ?> type="radio" name="status" value="2" class="ace" />
                                    <span class="lbl"> Cancelado</span>
                                </label>
                                &nbsp;&nbsp;
                                <label>
                                    <input <?php if ($atividade_ptc->status == '3') { ?> checked="checked" <?php } ?> type="radio" name="status" value="3" class="ace" />
                                    <span class="lbl"> Parcialmente conclu&iacute;do</span>
                                </label>
                                &nbsp;&nbsp;
                                <label>
                                    <input <?php if ($atividade_ptc->status == '4') { ?> checked="checked" <?php } ?> type="radio" name="status" value="4" class="ace" />
                                    <span class="lbl"> N&atilde;o iniciada</span>
                                </label>
                                &nbsp;&nbsp;

                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Início da execução da etapa, conforme cronograma alinhado com o concedente: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" OnKeyUp="mascaraData3(this);" maxlength="10" name="inicio" class="col-xs-10 col-sm-5" value="<?php //if ($atividade_ptc->inicio != "0000-00-00"){ echo date('d/m/Y', strtotime($atividade_ptc->inicio)); } 
                                                                                                                                                                    ?>" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Início de finalização da etapa, conforme cronograma alinhado com concedente</label>

                            <div class="col-sm-9">
                                <input value="<?php //if ($atividade_ptc->fim != "0000-00-00"){ echo date('d/m/Y', strtotime($atividade_ptc->fim)); } 
                                                ?>" type="text" id="form-field-1" OnKeyUp="mascaraData4(this);" name="fim" class="col-xs-10 col-sm-5" />
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                Resumo de cumprimento de objeto (Ênfase nos indicadores e artefatos entregues):
                            </label>

                            <div class="col-sm-9">
                                <textarea id="resumo_relatorio" name="resumo_relatorio" class="col-xs-10 col-sm-5" style="width:100%" rows="4"><?php echo ($last_cumprimento_objeto['resumo_relatorio']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('resumo_relatorio', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>

                        <script type="text/javascript">
                            function mascaraData(campoData) {
                                var data = data_geracao.value;
                                if (data.length == 2) {
                                    data = data + '/';
                                    document.forms[0].data_geracao.value = data;
                                    return true;
                                }
                                if (data.length == 5) {
                                    data = data + '/';
                                    document.forms[0].datadata_geracao.value = data;
                                    return true;
                                }
                            }

                            function pf() {
                                document.form.pfisica.style.visibility = 'visible';
                                document.form.pjuridica.style.visibility = 'hidden';
                            }

                            function pj() {
                                document.form.pjuridica.style.visibility = 'visible';
                                document.form.pfisica.style.visibility = 'hidden';
                            }
                        </script>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                Houve alterações na atividade ou cronograma programado e o cumprido? Se sim, justifique.
                            </label>

                            <div class="radio">
                                <label>
                                    <input <?php if ($last_cumprimento_objeto['atividade_1'] == '1') { ?> checked="checked" <?php } ?> type="radio" name="atividade_1" value="1" class="ace" />
                                    <span class="lbl"> Sim</span>
                                </label>
                                &nbsp;&nbsp;
                                <label>
                                    <input id="nao" <?php if ($last_cumprimento_objeto['atividade_1'] == '0') { ?> checked="checked" <?php } ?> type="radio" name="atividade_1" value="0" class="ace" />
                                    <span class="lbl"> Não</span>
                                </label>

                                <div style="padding:5px;">&nbsp; <textarea name="atividade_1_justifique" placeholder="se sim justifique..." style="width:50%"><?php echo ($last_cumprimento_objeto['atividade_1_justifique']); ?></textarea></div>

                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                No atual estágio de execução da atividade, há necessidade de mudança na atividade ou cronograma programado? Caso sim propor
                            </label>

                            <div class="radio">
                                <label>
                                    <input <?php if ($last_cumprimento_objeto['atividade_2'] == '1') { ?> checked="checked" <?php } ?> type="radio" name="atividade_2" value="1" class="ace" />
                                    <span class="lbl"> Sim</span>
                                </label>
                                &nbsp;&nbsp;
                                <label>
                                    <input id="nao" <?php if ($last_cumprimento_objeto['atividade_2'] == '0') { ?> checked="checked" <?php } ?> type="radio" name="atividade_2" value="0" class="ace" />
                                    <span class="lbl"> Não</span>
                                </label>

                                <div style="padding:5px;">&nbsp; <textarea name="atividade_2_justifique" placeholder="Caso sim propor..." style="width:50%"><?php echo ($last_cumprimento_objeto['atividade_2_justifique']); ?></textarea> </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Descreva as principais ações executadas para a realização da atividade do PTC (procedimento, método ou processo)</label>

                            <div class="col-sm-9">
                                <textarea id="acoes_executadas" name="acoes_executadas" rows="7" style="width:100%" class="col-xs-10 col-sm-5" /><?php echo ($last_cumprimento_objeto['acoes_executadas']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('acoes_executadas', {
                                        height: 200
                                    });
                                </script>




                            </div>
                        </div>






                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Qual é a avaliação da execução da atividade até o momento:</label>

                            <div class="col-sm-9">
                                <textarea id="avaliacao" name="avaliacao" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['avaliacao']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('avaliacao', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Em uma escala de 0 a 100 identifique a porcentagem de realização que mais se aproxima da execução desta ação/atividade (Observar o indicador físico)</label>
                            <div class="col-sm-2">
                                <input type="number" max="100" style="width:60px" name="porcentagem_realizacao" value="<?php echo ($last_cumprimento_objeto['porcentagem_realizacao']); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                Os quantitativos descritos nas atividades (indicadores físicos ou de desempenho) foram executados de acordo com o programado? Se negativo justificar</label>

                            <div class="radio">
                                <label>
                                    <input <?php if ($last_cumprimento_objeto['quantitativos_executados'] == '1') { ?> checked="checked" <?php } ?> type="radio" name="quantitativos_executados" value="1" class="ace" />
                                    <span class="lbl"> Sim</span>
                                </label>
                                &nbsp;&nbsp;
                                <label>
                                    <input id="nao" <?php if ($last_cumprimento_objeto['quantitativos_executados'] == '0') { ?> checked="checked" <?php } ?> type="radio" name="quantitativos_executados" value="0" class="ace" />
                                    <span class="lbl"> Não</span>
                                </label>

                                <div style="padding:5px;">&nbsp; <textarea id="quantitativos_executados_justifique" name="quantitativos_executados_justifique" placeholder="se sim justifique..." style="width:50%"><?php echo ($last_cumprimento_objeto['quantitativos_executados_justifique']); ?></textarea>

                                </div>

                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Descrever a inovação em produto, serviço ou processo e a referência de publicação de artigo publicado quando aplicável (Atividade obrigatória para projetos de pesquisa). Deve-se detalhar: Qual produto? Qual o serviço? Qual processo? inovador a referência do material a ser publicado. Quando não houver resultado inserir a previsão de realização de cada item:</label>

                            <div class="col-sm-9">
                                <textarea id="principais_resultados" name="principais_resultados" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['principais_resultados']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('principais_resultados', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Que ou quais atividades de <b>ensino</b> foram planejadas para essa ação:</label>

                            <div class="col-sm-9">
                                <textarea id="atividades_ensino_planejadas" name="atividades_ensino_planejadas" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['atividades_ensino_planejadas']); ?></textarea>
                            </div>
                            <script type="text/javascript">
                                var editor = CKEDITOR.replace('atividades_ensino_planejadas', {
                                    height: 200
                                });
                            </script>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Descreva brevemente os resultados de <b>ensino</b> obtidos até o momento:</label>

                            <div class="col-sm-9">
                                <textarea id="atividades_ensino_planejadas_resultados" name="atividades_ensino_planejadas_resultados" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['atividades_ensino_planejadas_resultados']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('atividades_ensino_planejadas_resultados', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Que ou quais atividades de <b>pesquisa</b> foram planejadas para essa ação:</label>

                            <div class="col-sm-9">
                                <textarea id="atividades_pesquisa_planejadas" name="atividades_pesquisa_planejadas" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['atividades_pesquisa_planejadas']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('atividades_pesquisa_planejadas', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Descreva brevemente os resultados de <b>pesquisa</b> obtidos até o momento:</label>

                            <div class="col-sm-9">
                                <textarea id="atividades_pesquisa_planejadas_resultados" name="atividades_pesquisa_planejadas_resultados" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['atividades_pesquisa_planejadas_resultados']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('atividades_pesquisa_planejadas_resultados', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Que ou quais atividades de <b>extensão</b> foram planejadas para essa ação:</label>

                            <div class="col-sm-9">
                                <textarea id="atividades_extensao_planejadas" name="atividades_extensao_planejadas" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['atividades_extensao_planejadas']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('atividades_extensao_planejadas', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Descreva brevemente os resultados de <b>extensão</b> obtidos até o momento:</label>

                            <div class="col-sm-9">
                                <textarea id="atividades_extensao_planejadas_resultados" name="atividades_extensao_planejadas_resultados" rows="3" style="width:100%" class="col-xs-10 col-sm-5"> <?php echo ($last_cumprimento_objeto['atividades_extensao_planejadas_resultados']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('atividades_extensao_planejadas_resultados', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Comentar (se houver) restrições que impediram o fiel desempenho da atividade em conformidade com o planejado</label>

                            <div class="col-sm-9">
                                <textarea id="restricoes" name="restricoes" rows="3" style="width:100%" class="col-xs-10 col-sm-5"><?php echo ($last_cumprimento_objeto['restricoes']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('restricoes', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Síntese da ação para publicação do relatório acadêmico:</label>

                            <div class="col-sm-9">
                                <textarea id="sintese_acao" name="sintese_acao" rows="3" style="width:100%" class="col-xs-10 col-sm-5"><?php echo ($last_cumprimento_objeto['sintese_acao']); ?></textarea>
                                <script type="text/javascript">
                                    var editor = CKEDITOR.replace('sintese_acao', {
                                        height: 200
                                    });
                                </script>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data de geração do relatório </label>

                            <div class="col-sm-9">
                                <input type="date" id="form-field-1" OnKeyUp="mascaraData(this);" maxlength="10" name="data_geracao" class="col-xs-10 col-sm-5" value="<?php echo $last_cumprimento_objeto['data']; //echo date('d/m/Y', strtotime($last_cumprimento_objeto['data'])); 
                                                                                                                                                                        ?>" />
                            </div>
                        </div>



                        <button name="salvar" class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            Salvar
                        </button>
                    </form>

                    </p>
                </section>

                <section id="content2">
                    <p>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp; </label>

                        <div class="col-sm-9">
                            <p>Nessa área você deverá selecionar 1 ou mais projetos de ensino, pesquisa ou extensão.
                            <p>
                            <p>Após, deverá escolher uma ou mais ações ou atividades que foram realiziada par atingir esta ação especificada no plano de trabalho do convênio.</p>
                        </div>
                    </div>
                    </p>
                    <p>
                    <form class="form-horizontal" role="form" name="form" method="post" action="<?php echo $this->url('cumprimento-objeto-atividade/add', array('action' => 'add', 'atividade_id' => $atividade_id)); ?>" enctype="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Projeto</label>

                            <div class="col-sm-9">
                                <select class="form-control" name="projeto_id" id="projeto_id">
                                    <option></option>
                                    <?php foreach ($projetos_ativos as $projeto) { ?>
                                        <option value="<?php echo $projeto['id']; ?>"><?php echo ($projeto['meta']); ?> - <?php echo ($projeto['descricao']); ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <br><br>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Atividade</label>
                            <div class="col-sm-9">
                                <div id="nucleo"></div>
                                <select class='form-control' name='atividade_epe_id[]' id='atividade_epe_id' multiple='multiple' style='height:200px'>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">&nbsp;</label>
                            <div class="col-sm-9">
                                <button name="salvar" class="btn btn-info" type="submit">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Salvar
                                </button>
                            </div>
                        </div>
                    </form>
                    <hr>

                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp;</label>

                        <div class="col-sm-9">
                            <table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th width="80%">Atividades</th>
                                        <th>Opções</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($cumprimento_objeto_atividades as $cumprimento_objeto_atividade) { ?>
                                        <tr>
                                            <th><?php echo ($atividades_projeto[$cumprimento_objeto_atividade['atividade_epe_id']]); ?><br />
                                                <small><strong>Projeto</strong>: <?php echo ($projetos[$cumprimento_objeto_atividade['area_id']]['descricao']); ?></small><br /><?php echo ($projetos[$cumprimento_objeto_atividade['area_id']]['meta']); ?>
                                            </th>

                                            <th>
                                                <div class="hidden-sm hidden-xs btn-group">
                                                    <a href="javascript:func()" onclick="confirmacao('<?php echo $cumprimento_objeto_atividade['id'] ?>')">
                                                        <span class="red">
                                                            <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                        </span>
                                                    </a>
                                                </div>
                                                <div class="hidden-md hidden-lg">
                                                    <div class="inline pos-rel">
                                                        <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                                            <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                                        </button>

                                                        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                            <li>
                                                                <a href="javascript:func()" onclick="confirmacao('<?php echo $cumprimento_objeto_atividade['id'] ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
                                                                    <span class="red">
                                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                                    </span>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </th>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <br>&nbsp;<br>
                    </p>
                </section>

                <section id="content3">
                    <p>

                    <form class="form-horizontal" role="form" name="form" method="post" action="<?php echo $this->url('artefato/add', array('action' => 'add', 'atividade_id' => $atividade_id)); ?>" enctype="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">Selecione tipos de artefatos, anexe arquivos comprobatórios e faça uma breve descrição sobre o artefato anexado:</label>

                            <div class="col-sm-3">

                                <select class="form-control" name="tipo">
                                    <option></option>
                                    <option>Declarações assinadas pelo interlocutor do projeto</option>
                                    <option>Relatório de realização de capacitação</option>
                                    <option>Atas de reuniões realizadas</option>
                                    <option>Relatório técnico</option>
                                    <option>Relatório de consultor</option>
                                    <option>Fotografia</option>
                                    <option>Ilustrações (folders, imagens de jornal, revista, sites, impressão de telas de sistema).</option>
                                    <option>Outros</option>
                                </select>
                            </div>
                            <div class="col-sm-3">
                                <input type="file" name="arquivo" id="arquivo" value="enviar" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Informe o nome padrão do artefato (até 60 posições)</label>

                            <div class="col-sm-9">
                                <textarea id="form-field-1" name="descricao" rows="3" style="width:100%" class="col-xs-10 col-sm-5" /></textarea>
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">
                                Informe uma breve legenda (Caso de ilustrações, fotografias ou títulos para relatórios)
                            </label>

                            <div class="col-sm-9">
                                <textarea id="form-field-1" name="legenda" rows="3" style="width:100%" class="col-xs-10 col-sm-5" /></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Digite a data em que o artefato foi concebido ou registrado </label>

                            <div class="col-sm-4">
                                <input type="date" id="form-field-1" maxlength="10" name="data" class="col-xs-10 col-sm-5" value="" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> local em que o artefato foi concebido ou registrado.</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" maxlength="10" name="local" class="col-xs-10 col-sm-9" value="" />
                                <br />

                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">&nbsp;</label>
                            <div class="col-sm-9">
                                <button name="salvar" class="btn btn-info" type="submit">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Salvar
                                </button>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp;</label>
                            <div class="col-sm-9">
                                <table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th width="80%" colspan="3">Artefatos</th>
                                            <th>Opções</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php

                                        /* Diretorio Local */
                                        $dir = __DIR__;
                                        $dir = str_replace("\\", '/', $dir);
                                        $dir = explode("convenio", $dir);
                                        /* Diretorio Local */

                                        $dir = $dir[0] . 'convenio/public/artefatos/';

                                        foreach ($artefatos as $artefato) {
                                        ?>
                                            <tr>
                                                <th><?php echo ($artefato['tipo']); ?></th>
                                                <th><?php echo ($artefato['descricao']); ?></th>
                                                <th><?php echo date('d/m/Y',  strtotime($artefato['data'])); ?></th>
                                                <th>
                                                    <a href="<?php echo $this->basePath('public/artefatos/' . $artefato['arquivo']); ?>" target="_blank">
                                                        <span class="blue"><i class="ace-icon fa fa-download bigger-120"></i></span>
                                                    </a>
                                                    &nbsp;&nbsp;
                                                    <a href="<?php echo $this->url('artefato/delete', array('action' => 'delete', 'atividade_id' => $atividade_id, 'id' => $artefato['id'])); ?>">
                                                        <span class="red"><i class="ace-icon fa fa-trash-o bigger-120"></i></span>
                                                    </a>
                                                </th>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </form>

                    </p>
                </section>

                <section id="content4">
                    <p>
                        Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken. Pork belly meatball t-bone bresaola tail filet mignon kevin turkey ribeye shank flank doner cow kielbasa shankle. Pig swine chicken hamburger, tenderloin turkey rump ball tip sirloin frankfurter meatloaf boudin brisket ham hock. Hamburger venison brisket tri-tip andouille pork belly ball tip short ribs biltong meatball chuck. Pork chop ribeye tail short ribs, beef hamburger meatball kielbasa rump corned beef porchetta landjaeger flank. Doner rump frankfurter meatball meatloaf, cow kevin pork pork loin venison fatback spare ribs salami beef ribs.
                    </p>
                    <p>
                        Jerky jowl pork chop tongue, kielbasa shank venison. Capicola shank pig ribeye leberkas filet mignon brisket beef kevin tenderloin porchetta. Capicola fatback venison shank kielbasa, drumstick ribeye landjaeger beef kevin tail meatball pastrami prosciutto pancetta. Tail kevin spare ribs ground round ham ham hock brisket shoulder. Corned beef tri-tip leberkas flank sausage ham hock filet mignon beef ribs pancetta turkey.
                    </p>
                </section>

            </main>
        </div>
    </div>
</div>