
			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script>
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('projeto/delete', array('action'=>'delete', 'id' => ''));?>"+id;
				     }
				}
			</script> 	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Projetos</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Projetos

							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                   	<p>
									<i class="ace-icon fa fa-angle-double-right"></i>
									<a href="<?php echo $this->url('projeto/add', array('action'=>'add'));?>"> cadastrar novo projeto </a> 
									<!-- |  <span style=""><a href="<?php //echo $this->url('projeto/inativos', array('action'=>'inativos'));?>">Projetos inativos (<?php //echo $total_projetos_inativos; ?>)</a></span>-->
                                    </p> 
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
                                                    <th width="20%">Área/Núleo</th>                                                    
													<th width="20%">Nome do projeto</th>
                                                    <th width="15%"><small>Líder de projeto (UFMT)</small></th>

													<th width="5%"><small>Atividades Contempladas</small></th>
								                  
								                   <th width="5%"><small>Colaboradores</small></th>
								                  
                                                    <th>Opções</th>

													
												</tr>
											</thead>

											<tbody>         
											<?php 
												foreach($projetos as $projeto){	
											?>                                   
												<tr>
													<td><strong><?php echo ($areas[$projeto['area_id']]); ?></strong><br /><span style="color:#666"><?php echo ($nucleos[$projeto['nucleo_id']]); ?></span></td>													
													<td><?php echo ($projeto['descricao']); ?> <?php //if(isset($filhos[$projeto['id']])){ echo count($filhos[$projeto['id']]); }else{ echo 0; }  ?> </td>
                                                    <td><?php if(array_key_exists($projeto['coordenador_id'], $usuarios)){ echo ($usuarios[$projeto['coordenador_id']]); }else{ echo ''; } ?></td>
                                                                                                                                     
													<td>
														<a href="<?php echo $this->url('atividade-projeto/consulta', array('action'=>'consulta', 'projeto_id'=> $projeto['id'])); ?>">
		                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
															<?php if(isset($atividades_projetos[$projeto['id']])){ echo count($atividades_projetos[$projeto['id']]); }else{ echo 0; }  ?>
															</span>
														</a>
													</td>                                                    
                            						
                            						<td>							
	                                                    <a href="<?php echo $this->url('projeto/ver-colaboradores', array('action'=>'ver-colaboradores', 'id'=> $projeto['id'])); ?>">
	                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
															<?php if(isset($usuarios_projetos[$projeto['id']])){ echo count($usuarios_projetos[$projeto['id']]); }else{ echo 0; }  ?> 
	                                                    </span>
	                                                    </a>                                                    
                                                    </td>
                                                    
													<td>
														<div class="hidden-sm hidden-xs btn-group">                                                      
															<!--button  onclick="window.location.href='<?=$root;?>ver-projeto/<?=$r['id'];?>';" class="btn btn-xs btn-success">
																<i class="ace-icon fa fa-check bigger-120"></i>
															</button-->


															<a href="<?php echo $this->url('projeto/edit', array('action'=>'edit', 'id'=> $projeto['id'])); ?>" class="btn btn-xs btn-info">	
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a>
                                                         
															<button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo  $projeto['id']; ?>')">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button>

															<!--button class="btn btn-xs btn-warning">
																<i class="ace-icon fa fa-flag bigger-120"></i>
															</button-->
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                                    

																	<li>
																		<a href="<?php echo $this->url('projeto/edit', array('action'=>'edit', 'id'=> $projeto['id'])); ?>" class="btn btn-xs btn-info">	
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                 
																	<li>
																		<a href="javascript:func()" onclick="confirmacao('<?php echo  $projeto['id']; ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
																</ul>
															</div>
														</div>
													</td>
                                                    
												</tr>
                                                
												<?php        
                                                ///
                                                /// LISTA DO PROJETOS FILHOS 
                                                ///
                                                
                                                if(array_key_exists($projeto['id'], $filhos)){
                                                //echo 'debug';
                                                foreach ($filhos[$projeto['id']] as $key => $filho){ ?>
                                                 <tr>
													<td>
                                                    <div style="padding-left:20px;">
                                                    <strong><?php echo ($areas[$filho['area_id']]); ?></strong><br /><span style="color:#666"><?php echo ($nucleos[$filho['nucleo_id']]); ?></span></div></td>													
													<td><?php echo ($filho['descricao']); ?></td>
                                                    <td><?php if(array_key_exists($filho['coordenador_id'], $usuarios)){ echo ($usuarios[$filho['coordenador_id']]); }else{ echo ''; } ?></td>
                                                    <td><?php                                                          	
													 	  	if(array_key_exists($filho['id'], $projetos_representantes)){
															 	  foreach ($projetos_representantes[$filho['id']] as $key => $representante_id){
															 	  	if(array_key_exists($representante_id, $representantes)){
																   		echo "- ".($representantes[$representante_id])."<br>";
															 	  	}
																  }
													 	  	}
														  ?>
                                                          <br />
                                                          <?php //if(isset($filhos[$projeto['id']])){ echo count($filhos[$projeto['id']]); }else{ echo 0; }  ?> 

													</td>                                                                                   
													<td>
                                                    
														<a href="<?php echo $this->url('atividade-projeto/consulta', array('action'=>'consulta', 'projeto_id'=> $filho['id'])); ?>">
		                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
															<?php 
															if($filho['total_atividades']){ echo $filho['total_atividades']; }else{ echo 0; }; ?>
															</span>
														</a>
													</td>                                                    
                            						
                            						<td>							
	                                                    <a href="<?php echo $this->url('projeto/ver-colaboradores', array('action'=>'ver-colaboradores', 'id'=> $filho['id'])); ?>">
	                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content="">
															<?php 
															if($filho['total_usuarios']){ echo $filho['total_usuarios']; }else{ echo 0; }; ?>
															<?php //if(isset($usuarios_projetos[$filho['id']])){ echo count($usuarios_projetos[$filho['id']]); }else{ echo 0; }  ?> 
	                                                    </span>
	                                                    </a>                                                    
                                                    </td>
                                                    
													<td>
														<div class="hidden-sm hidden-xs btn-group">                                                      
															<!--button  onclick="window.location.href='<?=$root;?>ver-projeto/<?=$r['id'];?>';" class="btn btn-xs btn-success">
																<i class="ace-icon fa fa-check bigger-120"></i>
															</button-->


															<a href="<?php echo $this->url('projeto/edit', array('action'=>'edit', 'id'=> $filho['id'])); ?>" class="btn btn-xs btn-info">	
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a>
                                                         
															<button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo  $filho['id']; ?>')">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button>

															<!--button class="btn btn-xs btn-warning">
																<i class="ace-icon fa fa-flag bigger-120"></i>
															</button-->
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                                    

																	<li>
																		<a href="<?php echo $this->url('projeto/edit', array('action'=>'edit', 'id'=> $filho['id'])); ?>" class="btn btn-xs btn-info">	
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                 
																	<li>
																		<a href="javascript:func()" onclick="confirmacao('<?php echo  $filho['id']; ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
																</ul>
															</div>
														</div>
													</td>                                                    
												</tr>
													<? 
                                                }
                                            }
                                          ?>
                                                
                                                
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->                                                             

					</div><!-- /.page-content -->
			</div><!-- /.main-content -->
