
			<!-- /section:basics/sidebar -->
			<div class="main-content">
                	      
				<div class="main-content-inner">
                <link href="<?php echo $this->basePath('css/modal.css'); ?>" rel="stylesheet">   
                
    
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index')); ?>">Home</a>
							</li>

							<li class="active">Relatório simplificado de cumprimento do objeto</li>
						</ul><!-- /.breadcrumb -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">

						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Relatório simplificado de cumprimento do objeto
							</h3>
						</div><!-- /.page-header -->
 
						<div id="mascara"></div>

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">                      
									<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>								         
								    <script type="text/javascript">
//									$(document).ready(function() {
//								        $('#estado').change(function() {
//									        var area_id = $('#estado').val();
//								    		var ajax_url = "/tce/convenio/atividade-ptc/get-submetas/"+area_id;
//
//								    		 $.ajax({
//								 	            type: "POST",
//								 	            url: ajax_url,
//								 	            data: "area="+area_id,
//								 	            success: function(msg){
//								 	                $("#submeta_id").html(msg);
//								 	        	}
//								 	     	});
//								        });
//									});

                                    window.onload = function() {
                                        $(document).ready(function () {
                                            $('#estado').change(function() {
                                                $.post( "/tce/convenio21/atividade-ptc/get-submetas/"+$('#estado').val(), { area: ""+$('#estado').val()},function(data){
                                                    $("#submeta_id").html(data);
                                                } );

                                            });
                                        });
                                    };
								   
								    </script>   
     
                                 
                                    <form class="form-horizontal" role="form" action="<?php echo $this->url('relatorio-cumprimento-objeto/consulta', array('action'=>'consulta')); ?>" method="post">
								
									<div class="form-group" id="conteudo">
                                    
                                    
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Área</label>

										<div class="col-sm-9">

                                            <select  class="form-control"  name="area_id" id="estado"  >
                                            <option value=""></option>
                                            <?php foreach ($areas as $area_dados){ ?>  
                                            <option value="<?php echo $area_dados['id']; ?>"><?php echo ($area_dados['descricao']); ?></option>
                                            <?php } ?>	  
                                            </select>
										</div>
									<br /><br /><br />

                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Submeta</label>
                                <div class="col-sm-9">
                                
                                <div id="nucleo"></div>
                                            <select  class="form-control"  name="submeta_id" id="submeta_id"  >
                                            </select>
                                </div>
                                </div>
                                
                                	<div class="form-group" id="conteudo">
                                    
                                    
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> &nbsp;</label>

										<div class="col-sm-9">
                                <button class="btn btn-info" type="submit">
												
												Ver
											</button>
                                            </div></div>
                                    <hr />
                                   
                                    
                                    
                                    
									
									
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
									</div><!-- /.span -->
								</div><!-- /.row -->


									<div class="row">
									<div class="col-xs-12">
                                                                                
                                    <h3><strong>META:</strong> <?php echo ($area->descricao); //area ?> </h3>        
                                    <h3><strong>SUBMETA:</strong> <?php echo ($submeta->descricao); ?> 
                                    <span style="float:right"><a href="<?php echo $this->url('relatorio-cumprimento-objeto/exportar-relatorio-cumprimento-objeto', array('action'=>'exportar-relatorio-cumprimento-objeto', 'area_id'=> $area->id, 'submeta_id' => $submeta->id)); ?>"><img src="<?php echo $this->basePath('public/img/ico_excel.png'); ?>" width="30" height="30"  /></a></h3>                                            
                                    <table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th width="15%" rowspan="2">Etapa</th>													
                                                    <th width="30%" rowspan="2">Ação/Especificação</th>
                                                    <th width="15%" rowspan="2">Inicio/Fim</th>
                                                    <th width="10%" rowspan="2">Inicio da execu&ccedil;&atilde;o</th>
                                                    <th width="10%" rowspan="2">Fim da execu&ccedil;&atilde;o</th>
                                                    <th rowspan="2"><small>Situacao</small></th>
                                                    <th colspan="2"><small>Indicador físico</small></th>
                                                    <th rowspan="2"><small>Indicador desempenho</small></th>
												</tr>
												<tr>
												  <th>und</th>
												  <th>qtd</th>
										      </tr>
											</thead>
											<tbody>
											<?php foreach ($atividades_ptc as $atividade_ptc){ ?>
                                                 <tr>													
                                                    <td>
														<?php echo ($atividade_ptc['etapa']);?>
													</td>
                                                    <td>
														<?php echo ($atividade_ptc['atividade']);?>
													</td>
                                                    <td>
														<?php echo $dt_inicial = implode("-",array_reverse(explode("-", $atividade_ptc['inicio'])));?> /  
                                                        <?php echo $dt_final = implode("-",array_reverse(explode("-", $atividade_ptc['fim'])));?>
													</td>
                                                    <td><?php echo $data_inicio= implode("-",array_reverse(explode("-", $atividade_ptc['data_inicio'])));?></td>
                                                    <td><?php echo $data_fim = implode("-",array_reverse(explode("-", $atividade_ptc['data_fim'])));?></td>                                                                                                        
													<td><?php 
															  if ($atividade_ptc['status'] ==1){ echo "conclu&iacute;do"; }
															  if ($atividade_ptc['status'] ==2){ echo "n&atilde;ao concluido"; }
															  if ($atividade_ptc['status'] ==3){ echo "parcialmente conclu&iacute;do"; }
															  if ($atividade_ptc['status'] ==4){ echo "n&atilde;o iniciado"; }		  
															  ?>
													  </td>														
														<td><?php echo ($atividade_ptc['indicador_unid']);?></td>
														<td><?php echo ($atividade_ptc['indicador_quant']);?></td>
														<td><?php echo ($atividade_ptc['indicador_desempenho']);?></td>
													
												</tr>
                                                <?php } ?>

												
											</tbody>
                                            
										</table>
									</div><!-- /.span -->
					  </div><!-- /.row -->
								
                                
                                
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->

			</div><!-- /.main-content -->
