<?php
    $arquivo = substr($atividade_ptc->atividade, 0, 50);  // eu não sou besta
	header("Content-Type: application/vnd.msword");
	header("Expires: 0");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("content-disposition: attachment;filename=".$arquivo.".doc");	    
?> 
<meta charset='utf-8'>
<div id="tudo">
	<div id="conteudo">

    <h2><strong>1 - RELATÓRIO DE CUMPRIMENTO DO OBJETO</strong></h2>

<p>
    <strong>1.1 - META: </strong><?php echo $area->descricao; ?>
</p>
<p>
    <strong>1.2 - SUBMETA: </strong><?php echo ($submeta->descricao); ?>
</p>
<p>
    <strong>1.3 - ATIVIDADE: </strong><?php echo ($atividade_ptc->atividade); ?>
</p>
<p>
    <strong>1.4 - O relatório que está sendo gerado é parcial ou de conclusão da atividade?</strong>
	<?php if ($cumprimento_objeto['parcial_total']=='p'){ echo "Parcial";} else  if ($cumprimento_objeto['parcial_total']=='t'){ echo "Total";}?></p>
<p>

<p>
    <strong>1.5 - Resumo de cumprimento de objeto (Ênfase nos indicadores e artefatos entregues):</strong><br />
	<?php   echo $cumprimento_objeto['resumo_relatorio'];?>
</p>

<p>
    <strong>1.6 - Data de geração do relatório:</strong> <?php  echo date('d/m/Y', strtotime($cumprimento_objeto['data']));?>
</p>
<p>
    <strong>1.7 - Período de execução:</strong> <?php echo date('d/m/Y', strtotime($atividade_ptc->data_inicio)); ?>  <?php if ($atividade_ptc->data_fim != '0000-00-00'){ echo " - ".date('d/m/Y', strtotime($atividade_ptc->data_fim)); }?>
</p>
<p>
    <strong>1.8 - Período previsto:</strong> <?php echo date('d/m/Y', strtotime($atividade_ptc->inicio)); ?> - <?php echo date('d/m/Y', strtotime($atividade_ptc->fim)); ?>
</p>
<strong><h2>2. ATIVIDADE</h2></strong>

<p>
    <strong>2.1  Houve alterações na atividade ou cronograma programado e o cumprido? Se sim, justifique.</strong>
</p>
<p>
<?php if ($cumprimento_objeto['atividade_1']==0){ echo "Não";}?> <?php if ($cumprimento_objeto['atividade_1_justifique']!=""){ echo "Sim - ". $cumprimento_objeto['atividade_1_justifique'];}?>
</p>
<p>
    <strong>2.2  No atual estágio de execução da atividade, há necessidade de mudança na atividade ou cronograma programado? Caso sim propor</strong>
<p>
<p><?php if ($cumprimento_objeto['atividade_2']==0){ echo "Não";}?> <?php if ($cumprimento_objeto['atividade_2_justifique']!=""){ echo "Sim - ". $cumprimento_objeto['atividade_2_justifique'];} ?></p>

<strong><h2>
    3. RESULTADOS
</h2>
</strong>
<p><strong>3.1 - Atividades (EPE) que contribuíram para a realização da atividade do PTC</strong></p>
<br />
										<table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">

                                         <tr bgcolor="#EEEEEE">
                                          <td width="100%">Atividades</td>
                                          </tr>
                                          
										 <tbody>
                                         <?php /*
                                       $sqlr=mysql_query("select a.*, b.descricao as atividade, c.descricao as projeto, d.descricao as meta 
                                       		from relatorio_cumprimento_objeto_atividade a
                                       			left join atividade_projeto b on b.id = a.atividade_epe_id 
											    left join projeto c on c.id = b.projeto_id 
											    left join area d on d.id = c.area_id 
									   where a.del = 0 and a.atividade_ptc_id = ".(int)$_GET['id']."");
									   while($r2=mysql_fetch_array($sqlr)){
									   	*/
										foreach($cumprimento_objeto_atividades as $cumprimento_objeto_atividade){ 
									   ?>
                                         <tr >
                                           <td style="border-bottom:1px solid #EEEEEE"><?php echo ($atividades_projeto[$cumprimento_objeto_atividade['atividade_epe_id']]);?><?php //echo utf8_encode($r2['atividade); ?><br />
                                            <small><strong>Projeto</strong>: <?php echo ($projetos[$cumprimento_objeto_atividade['area_id']]['descricao']);?></small><br /><?php echo ($projetos[$cumprimento_objeto_atividade['area_id']]['meta']); ?>
                                           </td>

                                          
                                          </tr>
                                        <?php } ?>
										 </tbody>
                                        </table><br />
<br />
<p>
    <strong>3.2 - Descreva as principais ações executadas para a realização da atividade do PTC (procedimento, método ou processo)</strong>
</p>

<p>

    <?php echo $cumprimento_objeto['acoes_executadas']; ?>
</p>


   <strong> 3.3 - Avaliação da atividade até o momento:</strong>
</p>
<p><?php echo $cumprimento_objeto['avaliacao']; ?></p>
<p>
   <strong> Os quantitativos descritos nas atividades (indicadores físicos ou de desempenho) foram executados de acordo com o programado? Se negativo justificar</strong>
</p>
<p>
<?php if ($cumprimento_objeto['quantitativos_executados']==0){ echo "Não";} else { echo "Sim - ". $cumprimento_objeto['quantitativos_executados_justifique']; } ?>
</p>

<p>
   <strong>3.4 - Fale sobre os principais resultados ou contribuições da atividade para o contexto de Ensino, Pesquisa ou Extensão da UFMT.</strong>
</p>
<p><?php echo $cumprimento_objeto['principais_resultados'];?></p>

<p>
   <strong>3.5 - Que ou quais atividades de ensino foram planejadas para essa ação:</strong>
</p>
<p><?php echo $cumprimento_objeto['atividades_ensino_planejadas'];?></p>

<p>
   <strong>3.6 - Descreva brevemente os resultados de ensino obtidos até o momento:</strong>
</p>
<p><?php echo $cumprimento_objeto['atividades_ensino_planejadas_resultados'];?></p>

<p>
   <strong>3.7 - Que ou quais atividades de pesquisa foram planejadas para essa ação:</strong>
</p>
<p><?php echo $cumprimento_objeto['atividades_pesquisa_planejadas'];?></p>

<p>
   <strong>3.8 - Descreva brevemente os resultados de pesquisa obtidos até o momento:</strong>
</p>
<p><?php echo $cumprimento_objeto['atividades_pesquisa_planejadas_resultados'];?></p>

<p>
   <strong>3.9 - Que ou quais atividades de extensão foram planejadas para essa ação:</strong>
</p>
<p><?php echo $cumprimento_objeto['atividades_extensao_planejadas'];?></p>

<p>
   <strong>3.10 - Descreva brevemente os resultados de extensão obtidos até o momento:</strong>
</p>
<p><?php echo $cumprimento_objeto['atividades_extensao_planejadas_resultados'];?></p>



<p>
    <strong>3.11 Comentar (se houver) restrições que impediram o fiel desempenho da atividade em conformidade com o planejado. </strong>
</p>
<p><?php echo $cumprimento_objeto['restricoes'];?></p>

<hr />
<h2>
   LISTA DE ARTEFATOS ANEXOS:
</h2>
<p>Declarações anexadas pelo interlocutor do projeto</p>
                                        <?php
                                        /*
										$sqlr="select a.* from artefato a where a.del = 0 and a.atividade_id = ".(int)$_GET['id']."";									
                                       $sqlr=mysql_query($sqlr) or die (mysql_error());*/
                                       ?>
    									<table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">                                        
                                         	<tr bgcolor="#EEEEEE">
                                          		<td colspan="2" width="100%">descrição</td>
                                          	</tr>
										 <tbody>
                                         <?php
										$i = 1;
									
									    foreach ($artefatos as $artefato){
									   ?>
                                         <tr>
                                          <th valign="top" style="vertical-align:text-top"><?php //echo $i;?></th>
                                           <th><a href="<?php echo $this->basePath('public/artefatos/'.$artefato['arquivo']); ?>"  target="_blank"><font style="font-weight:normal"><?php echo $artefato['descricao'];?><br />
                                           <small><strong><?php echo $artefato['legenda'];?></strong></small></font></a></th>
                                           
                                          </tr>
                                          <?php $i++; } ?>
										 </tbody>
                                        </table>
                                        <br /><br />