		<!-- /section:basics/sidebar -->
			<div class="main-content">

				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="">Home</a>
							</li>

							<li class="active">Setores</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">

						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Setores
							</h3>
						</div><!-- /.page-header -->


						<div class="row">
							<div class="col-xs-12">
                                <p>
                                <i class="ace-icon fa fa-angle-double-right"></i>
                                <a href="<?php echo $this->url('setor/add', array('action'=>'add'));?>"> cadastrar novo setor</a></span                                ></p>
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">


										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th width="90%">Descrição</th>
                    			<th>Opções</th>
												</tr>
											</thead>

											<tbody>
                                                  <?php

												  foreach ($setores as $setor){

												  ?>
												<tr>

													<td><?php echo $setor['descricao']; ?></td>

													<td>
														<div class="hidden-sm hidden-xs btn-group">

															<a href="<?php echo $this->url('setor/edit', array('action'=>'edit', 'id'=> $setor['id'])); ?>" class="btn btn-xs btn-info">
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a>
														</div>

														<div class="hidden-sm hidden-xs btn-group">

															<a href="<?php echo $this->url('setor/delete', array('action'=>'delete', 'id'=> $setor['id'])); ?>" class="btn btn-xs btn-danger">
																<i class="ace-icon fa fa-trash bigger-120"></i>
															</a>
														</div>



														</div>
													</td>
												</tr>
                                                <?php } ?>


											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->


								<div class="row">
									<div class="col-xs-12">


										</div><!-- /.modal-content -->
									</div><!-- /.modal-dialog -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
