			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Lançamento de atividade mensal</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h1>
								Lançamento de atividade mensal
							</h1>
						</div>
						   
                    
                    <script type="text/javascript">
						var rec = "O preenchimento do campo é obrigatório";
						function aviso($campo){
							if("" == document.meuform.campo.value){
								document.write("preenchimento obrigatorio");
								return false;
							}else{
								return true;
							}
						}
					</script>
                    
                    <form name="meuform" class="form-horizontal" role="form" action="<?php echo $this->url('usuario-atividade/add-especifico', array('action'=>'add', 'projeto_id' => $projeto_id));?>" method="post">
                                   
                                      	<div class="form-group">
											<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Projetos: </label>
											<div class="col-sm-9">
				                               <?php foreach ($usuario_projetos as $usuario_projeto){ ?>         	
                                                   <DIV class="col-xs-10 col-sm-8"><strong><?=$usuario_projeto['descricao']; ?></strong><br>
                                                       <div >
                                                        <?
                                                        foreach ($atividade_usuario_projeto[$usuario_projeto['projeto_id']] as $projeto_id){
                                                            echo $projeto_id['atividade'].'<br/>';
                                                        } ?></div>
                                                <br>

                                                </DIV>
                                                <? } ?>
											</div>
										</div>
                                     
                                     <?php
                                     /*if (
									 		($_SESSION['vinculo'] == 1) ||
											($_SESSION['vinculo'] == 4) ||
											($_SESSION['vinculo'] == 5) ){
											*/ ?>
                                     

                                   
                                                                       
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Descrição das atividades desenvolvidas: </label>
										<div class="col-sm-9">
											<textarea rows="10" name="texto" class="col-xs-12" required></textarea>                                         
                                             <script type="text/javascript">
                          var editor = CKEDITOR.replace( 'texto', { height: 200} );
                        </script>
										</div>
									</div>
									
									<script type="text/javascript">
									   		function mascaraData(campoData){
									              var data = campoData.value;
									              if (data.length == 2){
									                  data = data + '/';
									                  document.forms[0].data_inicial.value = data;
									      			  return true;              
									              }
									              if (data.length == 5){
									                  data = data + '/';
									                  document.forms[0].data_inicial.value = data;
									                  return true;
									              }
									         }
											 
											function mascaraData1(campoData){
									              var data = campoData.value;
									              if (data.length == 2){
									                  data = data + '/';
									                  document.forms[0].data_final.value = data;
									      			  return true;              
									              }
									              if (data.length == 5){
									                  data = data + '/';
									                  document.forms[0].data_final.value = data;
									                  return true;
									              }
									         }		
											 
											  function mascaraData3(campoData){
									              var data = campoData.value;
									              if (data.length == 2){
									                  data = data + '/';
									                  document.forms[0].data_abrang_ini.value = data;
									      			  return true;              
									              }
									              if (data.length == 5){
									                  data = data + '/';
									                  document.forms[0].data_abrang_ini.value = data;
									                  return true;
									              }
									         }
											 
											function mascaraData4(campoData){
									              var data = campoData.value;
									              if (data.length == 2){
									                  data = data + '/';
									                  document.forms[0].data_abrang_fim.value = data;
									                  return true;              
									              }
									              if (data.length == 5){
									                  data = data + '/';
									                  document.forms[0].data_abrang_fim.value = data;
									                  return true;
									              }
									         }
											 
											 function mascaraData6(campoData){
									              var data = campoData.value;
									              if (data.length == 2){
									                  data = data + '/';
									                  document.forms[0].data_relatorio.value = data;
									      			return true;              
									              }
									              if (data.length == 5){
									                  data = data + '/';
									                  document.forms[0].data_relatorio.value = data;
									                  return true;
									              }
									         }			  
									</script>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data inicial</label>
										<div class="col-sm-9">
											<input type="text" OnKeyUp="mascaraData(this);" id="form-field-1" maxlength="10" name="data_inicial" value="" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data final</label>
										<div class="col-sm-9">
											<input type="text" OnKeyUp="mascaraData1(this);" id="form-field-1"  maxlength="10" name="data_final" value="" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
									  <?php
									  /*
									  if (
										 		($_SESSION['vinculo'] == 1) ||
												($_SESSION['vinculo'] == 2) ||
												($_SESSION['vinculo'] == 3) 
									  			){ 
									  	*/
									  ?>
									<!--div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">&nbsp;</label>
										<div class="col-sm-9">
										<hr />
										</div>
									</div>
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">&nbsp;</label>
										<div class="col-sm-9">
											Digite o período de abrang&ecirc;ncia do relatório:
										</div>
									</div>									
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Inicial</label>
										<div class="col-sm-9">
											<input type="text" OnKeyUp="mascaraData3(this);" id="form-field-1"  maxlength="10" name="data_abrang_ini" value="" class="col-xs-10 col-sm-5" required />
										</div>
									</div>									
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Final</label>
										<div class="col-sm-9">
											<input type="text" OnKeyUp="mascaraData4(this);" id="form-field-1"  maxlength="10" name="data_abrang_fim" value="" class="col-xs-10 col-sm-5"  onsubmit="return aviso(data_abrang_fim)" />
										</div>
									</div-->
									
									<?php //} ?>
									                                    
									    <br>
										<br>
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">&nbsp;</label>
										<div class="col-sm-9">
										Data para ser impressa no relat&oacute;rio:
										</div>
									</div>
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data:<br /> (Informar o último dia util do mês em que as atividades foram realizadas.)</label>
										<div class="col-sm-9">
											<input type="text" OnKeyUp="mascaraData6(this);" id="form-field-1"  maxlength="10" name="data_relatorio" value="" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>									
                        </form>
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
