<!-- /section:basics/sidebar -->
<div class="main-content">
    <script language="Javascript">
        function confirmacao(id) {
            var resposta = confirm("Deseja remover esse registro?");

            if (resposta == true) {
                window.location.href = "<?php echo $this->url('ferias/delete', array('action'=>'delete', 'id' => ''));?>"+id;
            }
        }
    </script>
    <div class="main-content-inner">

        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
                </li>

                <li class="active">Controle de férias</li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content">

            <!-- /section:settings.box -->
            <div class="page-header">
                <h2>
                    Controle de férias

                </h2>
            </div><!-- /.page-header -->



            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <div class="row">
                        <div class="col-xs-12">



                            <p> Total de férias em andamento: <?php echo count($colaboradores); ?>

                                <i class="ace-icon fa fa-angle-double-right"></i>
                                <a href="<?php echo $this->url('ferias/add', array('action'=>'add'));?>"> cadastrar nova férias</a>


                            <table id="simple-table" class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th width="20%">Nome</th>
                                    <th width="15%">Perido aquisitivo inicial</th>
                                    <th width="15%">Perido aquisitivo inicial</th>
                                    <th>Periodo das férias</th>
                                    <th>Opções</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($colaboradores as $colaborador){ ?>
                                <tr>
                                    <th width="20%"><?=$colaborador['colaborador'];?></th>
                                    <th width="15%"><?=$colaborador['pa_inicio'];?></th>
                                    <th width="15%"><?=$colaborador['pa_fim'];?></th>
                                    <th><?=$colaborador['inicio'];?> a <?=$colaborador['fim'];?></th>
                                    <th>
                                        <button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo $colaborador['id']; ?>')">
                                            <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                        </button>
                                    </th>
                                </tr>
                                <? } ?>

                            </table>


                        </div><!-- /.span -->
                    </div><!-- /.row -->
                </div><!-- PAGE CONTENT ENDS -->
            </div><!-- /.col -->
        </div><!-- /.row -->




         </div>
    </div>
</div><!-- /.main-content -->
