			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('participante/delete', array('action'=>'delete', 'id' => ''));?>"+id;
				     }
				}
				</script> 	       	      
				<fdiv class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Participantes</li>
						</ul><!-- /.breadcrumb -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h2>
								Participantes
								
							</h2>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    <style>
									/* Add this attribute to the element that needs a tooltip */
									[data-tooltip] {
									  position: relative;
									  z-index: 2;
									  cursor: pointer;
									}
									
									/* Hide the tooltip content by default */
									[data-tooltip]:before,
									[data-tooltip]:after {
									  visibility: hidden;
									  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
									  filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=0);
									  opacity: 0;
									  pointer-events: none;
									}
									
									/* Position tooltip above the element */
									[data-tooltip]:before {
									  position: absolute;
									  bottom: 150%;
									  left: 50%;
									  margin-bottom: 5px;
									  margin-left: -80px;
									  padding: 7px;
									  width: 160px;
									  -webkit-border-radius: 3px;
									  -moz-border-radius: 3px;
									  border-radius: 3px;
									  background-color: #000;
									  background-color: hsla(0, 0%, 20%, 0.9);
									  color: #fff;
									  content: attr(data-tooltip);
									  text-align: center;
									  font-size: 14px;
									  line-height: 1.2;
									}
									
									/* Triangle hack to make tooltip look like a speech bubble */
									[data-tooltip]:after {
									  position: absolute;
									  bottom: 150%;
									  left: 50%;
									  margin-left: -5px;
									  width: 0;
									  border-top: 5px solid #000;
									  border-top: 5px solid hsla(0, 0%, 20%, 0.9);
									  border-right: 5px solid transparent;
									  border-left: 5px solid transparent;
									  content: " ";
									  font-size: 0;
									  line-height: 0;
									}
									
									/* Show tooltip content on hover */
									[data-tooltip]:hover:before,
									[data-tooltip]:hover:after {
									  visibility: visible;
									  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
									  filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=100);
									  opacity: 1;
									}
									</style>
     
      
      								<p> Total de participantes: <?php echo count($participantes); ?> 
									<?php // if (($_SESSION['permissao']==8)|| ($_SESSION['usuario_id']==11) ){ ?>
                                    <i class="ace-icon fa fa-angle-double-right"></i>
                                    <a href="<?php echo $this->url('participante/add', array('action'=>'add'));?>"> cadastrar novo participante</a>
									<?php // } ?>
                                    
                                    
                                    
      
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th width="80%">Nome</th>
                                                    <th>Projetos</th>
                                                    <th>Opções</th>
												</tr>
											</thead>

											<tbody>
												<?php foreach ($participantes as $participante){ ?>												
												<tr>
													<td>
														<?php echo ($participante['nome']); ?><br />
														<small style="color:#999"><?php echo $participante['cpf']; ?>&nbsp;</small>
													</td>                                                   
                                                    <td><a href="<?php //echo $this->url('usuario-projeto/consulta', array('action'=>'consulta', 'usuario_id' =>$participante['id']));?>">
                                                    <span class="btn btn-sm" data-rel="popover" title="" data-content=""><?php if(isset($colaborador_projetos[$participante['id']])){ echo count($colaborador_projetos[$colaborador['id']]); }else{ echo '0'; }?></span></a></td>										
                                                    
                                                 
													<td>
                                                     <?php /*if (($_SESSION['usuario_id']==367) || ($_SESSION['usuario_id']==365)  || ($_SESSION['usuario_id']==12) || ($_SESSION['usuario_id']==11) ){ ?>
												<form action="" method="post">
							                      <input type="hidden" name="id" value="1" />
							                      	<button class="btn btn-info" type="submit">
														<i class="ace-icon fa fa-check bigger-110"></i>
														Resetar senha
													</button>
	                                            </form>
                                             <?php } */?>
														<div class="hidden-sm hidden-xs btn-group">  
                                                            															
                                                            <a href="<?php echo $this->url('participante/edit', array('action'=>'add', 'id'=> $participante['id']));?>" class="btn btn-xs btn-info">
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a>
                                                            
															<button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo $participante['id']; ?>')">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button>
                                                            
                                                            <?php //} ?>

														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
																	<?php //if ($_SESSION['permissao']==8){ ?>
																	<li>
																		<a href="<?php echo $this->url('participante/edit', array('action'=>'add', 'id'=> $participante['id']));?>" class="tooltip-success" data-rel="tooltip" title="Editar	">
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
																		</a>
																	</li>                                                                    
																	<li>
																		<a href="javascript:func()" onclick="confirmacao('<?php echo $participante['id']; ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                
																</ul>
															</div>
														</div>
													</td>
                                                        <?php //} ?>
												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
