		        <div class="row">
					<div class="col-lg-12">
						<div class="row">
							<div class="col-lg-12">
				                <h1 class="page-header">Lembrete de Senha</h1>
				                <p>Informe seu e-mail e logo enviaremos uma nova senha para acesso.</p>
							</div>
						</div>          
						<br> 	 
						<form method="post" action="<?php echo $this->url('login', array('action' => 'forget')); ?>" class="form-horizontal" role="form">
							                            <?php 
							                            if(isset($_GET['erro'])){
							                            	if($_GET['erro'] == 1){
							                            ?>
							                            <div class="alert alert-danger">
														  <strong>Erro!</strong> E-mail não encontrado em nosso banco de dados, favor entrar em contato com a administração!
														</div>
														<?php }else if($_GET['erro'] == 2){ ?>							                            
							                            <div class="alert alert-danger">
														  <strong>Erro!</strong> Favor entrar em contato com a administração para regularizar sua situação cadastral!
														</div>
							                            <?php 			}
							                            	}?>
							<div class="form-group">
								<label for="inputEmail" class="col-lg-2 control-label">E-mail</label>
								<div class="col-lg-5">
									<input type="email" class="form-control" id="associado_email" name="associado_email" placeholder="E-mail" required>
								</div>
							</div>												
							<div class="form-group">
								<div class="col-lg-offset-2 col-lg-10">
									<button type="submit" class="btn btn-primary btn-lg botao" >
										Confirmar
									</button>
								</div>
							</div>
						</form>             		
					</div>     		
                </div>	        