<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Cadastrar novo representante do TCE</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Cadastrar representante do TCE
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">

								<!-- PAGE CONTENT BEGINS -->
								<form id="representante_add" name="representante_add" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php echo $this->url('representante/add', array('action' => 'add'));?>" role="form" class="form-horizontal form-label-left">
             
  									<!-- #section:elements.form -->
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="nome" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Email </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="email" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                      <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Cpf </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="cpf" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="telefone" class="col-xs-10 col-sm-5" required />
										</div>
                                        
                                        </div>
                                        
                                        
                                        <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Orgão </label>

										<div class="col-sm-9">
											<select id="form-field-1" name="orgao" class="col-xs-10 col-sm-5"/>
                                             <option></option>
                                             <option value="TCE">TCE</option>
                                             <option value="UFMT">UFMT</option>
                                             <option value="OUTROS">OUTROS</option>
                                            </select>
                                            </div>
                                            </div>
                                             
                                        
                                   <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Setor </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="setor_lotacao" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome do cargo efetivado no orgão</label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="nome_cargo" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
	                                
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Função de confiança</label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="funcao_confianca" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                    
                                    
                                    
                                    
                                    
                                                                  

									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
