<?php
echo pack("CCC",0xef,0xbb,0xbf);

    $html = "<table border='1'>";
    $html .= "<tr>";
    $html .= "<td><b>Nome</b></td>";
    $html .= "<td><b>Data relatório</b></td>";
	$html .= "<td><b>Última atividade</b></td>";

    $html .= "</tr>";

	foreach ($usuarios as $usuario){

        $i = explode("||", $usuario['relatorio']);

    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".($usuario['nome'])."</td>";
    $html .= "<td>".($i[0])."</td>";
    $html .= "<td>".strip_tags($i[1])."</td>";
    $html .= "</tr>";

}
$html .= "</table>";

$arquivo = 'relatorio-atividade-mensal_'.$mes.'-'.$ano.'.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header ("Content-type: application/x-msexcel");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );

  echo   $html;
?>