			<!-- /section:basics/sidebar -->
			<div class="main-content"> 	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index')); ?>">Home</a>
							</li>

							<li class="active">Relatório do colaborador</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
									<!-- /section:settings.box -->
						<div class="page-header">
							<h1>
								Relatório do colaborador:

							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    
                                    
										
                                        <div class="form-group">

										Colaborador:  	<strong><?php echo ($usuario->nome); ?></strong> <br />
										Projeto: 		<strong><?php echo ($projeto->descricao); ?></strong>
										<br /><br />
										<?php 		
											$form_action = "";
											
											switch ($usuario->vinculo) {
												case '1': $form_action = 'get-relatorio-mensal-atividade'; break;
												case '2': $form_action = 'get-relatorio-servicos'; break;
												case '3': $form_action = 'get-relatorio-servicos'; break;												
												default: $form_action = 'get-relatorio-matriz-responsabilidade'; break;		
												
											}
											$form_action = 'get-relatorio-matriz-responsabilidade';
											//echo $form_action;
										?>
										
										<div class="col-sm-9">
										
                                        <label>Selecione um Mês:</label>
				
                                            <select name="mes" class="" onchange="location = this.value;" required>
                                            <option value="">selecione...</option>

                                           <?php foreach($usuario_atividades_meses as $usuario_atividade ){ ?>
                                            <option value="<?php echo $this->url('relatorio-colaborador/get-relatorio-especifico', array('action'=> $form_action, 'id'=> $usuario_atividade['id'],'projeto_id'=> $projeto_id)); ?>"><?php echo $usuario_atividade['mes']?>/<?php echo $usuario_atividade['ano']?></option>
                                            <?php } ?>
                                            </select>                  
                                           
										
                                            </div>
                                            </form>
                                            
											<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                                            
                                            <script>
                                             $(document).ready(function(){
                                            
                                                $('#link').on('change', function () {
                                                     var url = $(this).val(); 
                                                     if (url) { 
                                                         window.open(url, '_blank');
                                                      }
                                                      return false;
                                                    });
                                                 });
                                            </script>
										</div>
                                    
									</div><!-- /.span -->
								</div><!-- /.row -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
