		<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
function confirmacao(id) {
     var resposta = confirm("Deseja remover esse registro?");

     if (resposta == true) {
         // window.location.href = "remover.php?t=usuario_projeto&redirect=ver-colaborador/"+id;
     }
}
</script>
				<div class="main-content-inner">



					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index')); ?>">Home</a>
							</li>

							<li class="active">Ver relatórios do colaboradores</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Colaborador: <?php echo ($usuario->nome); ?>

							</h3>
						</div><!-- /.page-header -->




<div id="mascara"></div>


						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">

										<div style="border:2px solid #EEEEEE; padding:20px">
											<!-- /section:settings.box -->
											<div class="page-header">
												<h1>
													Projetos EPE
												</h1>
											</div><!-- /.page-header -->

											<?php foreach ($usuarios_projetos as $id => $projeto_id){
												 echo '<li>'.$projetos[$projeto_id].'</li>';
												 } ?>

												 <hr />


												 <table id="simple-table" class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th width="90%">Mês de referência:</th>
																		 <th>Opções</th>

				</tr>
			</thead>

			<tbody>
																	<?php

					switch ($usuario->vinculo) {
				case '1': $form_action = 'get-relatorio-mensal-atividade'; break;
				case '2': $form_action = 'get-relatorio-servicos'; break;
				case '3': $form_action = 'get-relatorio-servicos'; break;
				//case '6': $form_action = 'get-relatorio-estagio'; break;
				//case '7': $form_action = 'get-relatorio-estagio'; break;
				default: $form_action = 'get-relatorio-matriz-responsabilidade'; break;
		 }
					$meses = array (1 => "Janeiro", 2 => "Fevereiro", 3 => "Março", 4 => "Abril", 5 => "Maio", 6 => "Junho", 7 => "Julho", 8 => "Agosto", 9 => "Setembro", 10 => "Outubro", 11 => "Novembro", 12 => "Dezembro");
				?>
									 <?php foreach($usuario_atividades_meses as $usuario_atividade){
										?>
				<tr>

					<td>
						<?php echo $meses[(int)$usuario_atividade['mes']]; ?> / <?php echo $usuario_atividade['ano']; ?>
					</td>
					<td>
						<div class="hidden-sm hidden-xs btn-group">

																							<a target="_blank"  href="<?php echo $this->url('relatorio-colaborador/'.$form_action.'', array('action'=>$form_action, 'id' => $usuario_atividade['id'])); ?>" class="btn btn-xs btn-default">
																						 <span class="white"><i class="ace-icon fa fa-print bigger-120"></i></span>
																						 </a>

						</div>



						<!--div class="hidden-md hidden-lg">
							<div class="inline pos-rel">
								<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
									<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
								</button>

								<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
									<li>
										<a href="" class="tooltip-info" data-rel="tooltip" title="Ver">
											<span class="blue">
												<i class="ace-icon fa fa-edit bigger-120"></i>
											</span>
										</a>
									</li>
								</ul>
							</div>
						</div-->
					</td>
				</tr>
																 <?php } ?>
			</tbody>
		</table>
										</div>

<br>
									<div style="border:2px solid #EEEEEE; padding:20px">

										<div class="page-header">
											<h1>
											Projetos Específicos - Matrizes de Responsabilidades e PDI
											</h1>
										</div><!-- /.page-header -->


										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th width="90%">Nome do projeto</th>
                                                    <th>Opções</th>
												</tr>
											</thead>

											<tbody>
                                                  <?php foreach ($usuarios_projetos_especificos as $usuario_projeto_especifico_id => $projeto_especifico_id){ ?>
												<tr>

													<td>
														<?php echo $projetos_especificos[$projeto_especifico_id]; ?>
													</td>
													<td>
														<div class="hidden-sm hidden-xs btn-group">
                             <a  href="<?php echo $this->url('relatorio-colaborador/ver-relatorio-colaborador-projeto', array('action'=>'ver-relatorio-colaborador-projeto', 'id' => $usuario_projeto_especifico_id, 'projeto_id' => $projeto_especifico_id )); ?>" class="btn btn-xs btn-default">
	                            <span class="white"><i class="ace-icon fa fa-print bigger-120"></i></span>
                             </a>
														</div>													
													</td>
												</tr>
                                                <?php } ?>
											</tbody>
										</table>

									</div>




									</div><!-- /.span -->
								</div><!-- /.row -->
								</div><!-- PAGE CONTENT ENDS -->


                            </div><!-- /.col -->

						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
