<!-- /section:basics/sidebar -->
<div class="main-content">
	<script language="Javascript">
		function confirmacao(id) {
			var resposta = confirm("Deseja remover esse registro?");

			if (resposta == true) {
				//window.location.href = "<?php //echo $this->url('home', array('action'=>'index')); 
											?>"+id;
			}
		}
	</script>

	<div class="main-content-inner">
		<!-- #section:basics/content.breadcrumbs -->
		<div class="breadcrumbs" id="breadcrumbs">
			<script type="text/javascript">
				try {
					ace.settings.check('breadcrumbs', 'fixed')
				} catch (e) {}
			</script>

			<ul class="breadcrumb">
				<li>
					<i class="ace-icon fa fa-home home-icon"></i>
					<a href="<?php echo $this->url('home', array('action' => 'index')); ?>">Home</a>
				</li>

				<li class="active">Relatórios</li>
			</ul><!-- /.breadcrumb -->

			<!-- /section:basics/content.searchbox -->
		</div>

		<!-- /section:basics/content.breadcrumbs -->
		<div class="page-content">

			<!-- /section:settings.box -->
			<div class="page-header">
				<h2>
					Relatório de cumprimento de Metas
				</h2>
			</div><!-- /.page-header -->

			<div class="row">
				<div class="col-xs-12">
					<!-- PAGE CONTENT BEGINS -->
					<div class="row">
						<div class="col-xs-12">
							<style>
								/* Add this attribute to the element that needs a tooltip */
								[data-tooltip] {
									position: relative;
									z-index: 2;
									cursor: pointer;
								}

								/* Hide the tooltip content by default */
								[data-tooltip]:before,
								[data-tooltip]:after {
									visibility: hidden;
									-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
									filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=0);
									opacity: 0;
									pointer-events: none;
								}

								/* Position tooltip above the element */
								[data-tooltip]:before {
									position: absolute;
									bottom: 150%;
									left: 50%;
									margin-bottom: 5px;
									margin-left: -80px;
									padding: 7px;
									width: 160px;
									-webkit-border-radius: 3px;
									-moz-border-radius: 3px;
									border-radius: 3px;
									background-color: #000;
									background-color: hsla(0, 0%, 20%, 0.9);
									color: #fff;
									content: attr(data-tooltip);
									text-align: center;
									font-size: 14px;
									line-height: 1.2;
								}

								/* Triangle hack to make tooltip look like a speech bubble */
								[data-tooltip]:after {
									position: absolute;
									bottom: 150%;
									left: 50%;
									margin-left: -5px;
									width: 0;
									border-top: 5px solid #000;
									border-top: 5px solid hsla(0, 0%, 20%, 0.9);
									border-right: 5px solid transparent;
									border-left: 5px solid transparent;
									content: " ";
									font-size: 0;
									line-height: 0;
								}

								/* Show tooltip content on hover */
								[data-tooltip]:hover:before,
								[data-tooltip]:hover:after {
									visibility: visible;
									-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
									filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=100);
									opacity: 1;
								}
							</style>

							<table id="simple-table" class="table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th width="90%">Nome</th>
										<!-- <th width="30%">Área</th>                                                  
					<th>Representantes</th> -->
										<th width="5%">Projetos</th>
									</tr>
								</thead>

								<tbody>
									<?php foreach ($usuarios as $usuario) { ?>
										<tr>
											<td>
												<?php echo ($usuario['nome']); ?>
												<br /><small style="color:#999"><?php echo $usuario['cpf']; ?></small>
											</td>
											<!-- <td><?php echo ($usuario['area']); ?></td>                                                    
					<td>
					<?php
										if (isset($usuarios_projetos[$usuario['id']])) {
											if (is_array($usuarios_projetos[$usuario['id']])) {
												$representantes_usuario = array();
												foreach ($usuarios_projetos[$usuario['id']] as $usuario_projeto) {
													$representantes_usuario[] = $usuario_projeto['representante_id'];
												}
												$representantes_usuario_unicos = array_unique($representantes_usuario);
												foreach ($representantes_usuario_unicos as $representante_id) {
													echo $representantes[$representante_id] . '<br>';
												}
											}
										}
					?>
					</td>	 -->
											<td>
												<a href="<?php echo $this->url('relatorio-colaborador/assinar-relatorios-list-projetos', array('action' => 'assinar-relatorios-list-projetos', 'usuario_id' => $usuario['id'])); ?>">
													<span class="btn btn-sm" data-rel="popover" title="" data-content=""><?php if (isset($usuarios_projetos[$usuario['id']])) {
																																echo count($usuarios_projetos[$usuario['id']]);
																															} else {
																																echo 0;
																															}  ?></span>
												</a>
											</td>
										</tr>
									<?php } ?>
								</tbody>
							</table>
						</div><!-- /.row -->

					</div><!-- PAGE CONTENT ENDS -->
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.page-content -->
	</div>
</div><!-- /.main-content -->