			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}				
						</script>
                        
                        <ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Projetos - <?=$usuario->nome;?></li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h1>
								Projetos - <?=$usuario->nome;?>
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th width="90%">Nome do projeto</th>
                                                    <th>Opções</th>													
												</tr>
											</thead>

											<tbody>
                                                  <?php foreach ($usuarios_projetos as $usuario_projeto_id => $projeto_id){ ?>
												<tr>
													
													<td>
														<?php echo $projetos[$projeto_id]; ?>
													</td>
													<td>
														<div>                                                      
                                                        
															
															                                                     
                                                            <a  href="<?php echo $this->url('relatorio-colaborador/assinar-relatorios-list-relatorios', array('action'=> 'assinar-relatorios-list-relatorios', 'usuario_id'=> $usuario_id, 'projeto_id' => $projeto_id)); ?>" class="btn btn-xs btn-success">
															visualizar relatórios
															</a>
                                                            
                                                             <!-- <a  href="<?php echo $this->url('relatorio-colaborador/ver-relatorio-colaborador-projeto', array('action'=>'ver-relatorio-colaborador-projeto', 'id' => $usuario_projeto_id)); ?>" class="btn btn-xs btn-default">
                                                            <span class="white"><i class="ace-icon fa fa-print bigger-120"></i></span>
                                                            </a> -->
														</div>

														
													</td>
												</tr>
                                                <?php } ?>												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div>