		<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
function confirmacao(id) {
     var resposta = confirm("Deseja remover esse registro?");
 
     if (resposta == true) {
         // window.location.href = "remover.php?t=usuario_projeto&redirect=ver-colaborador/"+id;
     }
}
</script> 	       	      
				<div class="main-content-inner">
                
                
    
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index')); ?>">Home</a>
							</li>

							<li class="active">Ver relatórios do colaboradores</li>
						</ul><!-- /.breadcrumb -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Colaborador: <?php echo ($usuario->nome); ?>

							</h3>
						</div><!-- /.page-header -->



 
<div id="mascara"></div>


						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                   
                                
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th width="90%">Projetos</th>
                                                  
                                                    <th>Opções</th>
													
												</tr>
											</thead>

											<tbody>
 												<?php foreach ($usuarios_projetos as $id => $projeto_id){ ?>
 	     
												<tr>
													
													<td width="60%">
														<?php echo $projetos[$projeto_id]; ?>
													</td>
                                                   

													<td>
														<div class="hidden-sm hidden-xs btn-group">                                                                  
                                                            
                                                            <a  href="<?php echo $this->url('relatorio-colaborador/ver-relatorio-colaborador-projeto', array('action'=>'ver-relatorio-colaborador-projeto', 'id' => $id)); ?>" class="btn btn-xs btn-default">
                                                            <span class="white"><i class="ace-icon fa fa-search-plus bigger-120"></i></span>
                                                            </a>
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
																	<li>
																		<a href="" class="tooltip-info" data-rel="tooltip" title="Ver">
																			<span class="blue">
																				<i class="ace-icon fa fa-search-plus bigger-120"></i>
																			</span>
																		</a>
																	</li>
																	
																</ul>
															</div>
														</div>
													</td>
												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
                                        
                                      
									</div><!-- /.span -->
								</div><!-- /.row -->
								</div><!-- PAGE CONTENT ENDS -->
							
                            
                            </div><!-- /.col -->
                            
						</div><!-- /.row -->
					</div><!-- /.page-content -->

			</div><!-- /.main-content -->
