<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Cadastrar nova atividade</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Cadastrar atividade
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
                            <p>
                            	<a href="<?php echo $this->url('atividade-projeto/consulta', array('action'=>'consulta', 'projeto_id' => $projeto_id));?>">Voltar</a>
                            </p>

								<!-- PAGE CONTENT BEGINS -->
								<form id="atividade_projeto_add" name="atividade_projeto_add" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php echo $this->url('atividade-projeto/add', array('action' => 'add', 'projeto_id' => $projeto_id));?>" role="form" class="form-horizontal form-label-left">
               									
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Área / Núcleo </label>
										<div class="col-sm-9">
											<input type="text" id="form-field-1" value="<?php echo ($areas[$projeto->area_id])." / ".($nucleos[$projeto->nucleo_id]); ?>" name="descricao" class="col-xs-10 col-sm-5" disabled="disabled" />
										</div>
									</div>
									
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Projeto </label>
										<div class="col-sm-9">
											<input type="text" id="form-field-1" value="<?php echo ($projeto->descricao); ?>" name="descricao" class="col-xs-10 col-sm-5" disabled="disabled" />
										</div>
									</div>
                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Previs&atilde;o Inicio </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" OnKeyUp="mascaraData3(this);" maxlength="10" name="prev_inicio" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Previs&atilde;o Fim</label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" OnKeyUp="mascaraData4(this);" name="prev_fim" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Prazo <small>em dias</small></label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="prazo" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                                                        
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Registro EPE?</label>

										<div class="radio">
											<label>
												<input  type="radio" name="epe" value="1" class="ace" />
												<span class="lbl"> Sim</span>
											</label>
										&nbsp;&nbsp;
											<label>
												<input  type="radio" checked="checked" name="epe" value="0" class="ace" />
												<span class="lbl"> Não</span>
											</label>
										</div>
                                     </div>
                                    
                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Descrição </label>

										<div class="col-sm-9">
											<textarea id="form-field-1" name="descricao" class="col-xs-10 col-sm-5"  style="width:100%" rows="4" /></textarea>
										</div>
									</div>
                                    
									<div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">PTC?</label>

												<div class="radio">
													<label>
														<input  type="radio" name="ptc" value="1" class="ace" />
														<span class="lbl"> Sim</span>
													</label>
												&nbsp;&nbsp;
													<label>
														<input  type="radio" checked="checked" name="ptc" value="0" class="ace" />
														<span class="lbl"> Não</span>
													</label>
												</div>
                                          </div>
                                          
                                          <hr />
                                           <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Inicio da execu&ccedil;&atilde;o </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" OnKeyUp="mascaraData(this);" maxlength="10" name="dt_inicial" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Fim da execu&ccedil;&atilde;o</label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" OnKeyUp="mascaraData1(this);" name="dt_final" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
			
<script type="text/javascript">
   function mascaraData(campoData){
              var data = campoData.value;
              if (data.length == 2){
                  data = data + '/';
                  document.forms[0].dt_inicial.value = data;
      return true;              
              }
              if (data.length == 5){
                  data = data + '/';
                  document.forms[0].dt_inicial.value = data;
                  return true;
              }
         }

   function mascaraData1(campoData){
              var data = campoData.value;
              if (data.length == 2){
                  data = data + '/';
                  document.forms[0].dt_final.value = data;
      return true;              
              }
              if (data.length == 5){
                  data = data + '/';
                  document.forms[0].dt_final.value = data;
                  return true;
              }
         }
		 
		 function mascaraData3(campoData){
              var data = campoData.value;
              if (data.length == 2){
                  data = data + '/';
                  document.forms[0].prev_inicio.value = data;
      return true;              
              }
              if (data.length == 5){
                  data = data + '/';
                  document.forms[0].prev_inicio.value = data;
                  return true;
              }
         }
		 
		 
		 function mascaraData4(campoData){
              var data = campoData.value;
              if (data.length == 2){
                  data = data + '/';
                  document.forms[0].prev_fim.value = data;
      return true;              
              }
              if (data.length == 5){
                  data = data + '/';
                  document.forms[0].prev_fim.value = data;
                  return true;
              }
         }
</script>
