			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Editar atividade do projeto</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Editar atividade
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
                            <p>
                            	<a href="<?php echo $this->url('atividade-projeto/consulta', array('action'=>'consulta', 'projeto_id' => $projeto_id));?>">Voltar</a>
                            </p>

								<!-- PAGE CONTENT BEGINS -->
								<form id="atividade_projeto_edit" name="atividade_projeto_edit" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php echo $this->url('atividade-projeto/edit', array('action' => 'edit', 'id'=> $atividade_projeto->id, 'projeto_id' => $projeto_id));?>" role="form" class="form-horizontal form-label-left">
                                         
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Área / Núcleo </label>
										<div class="col-sm-9">
											<input type="text" id="form-field-1" value="<?php echo ($areas[$projeto->area_id])." / ".($nucleos[$projeto->nucleo_id]); ?>" name="descricao" class="col-xs-10 col-sm-5" disabled="disabled" />
										</div>
									</div>
									
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Projeto </label>
										<div class="col-sm-9">
											<input type="text" id="form-field-1" value="<?php echo ($projeto->descricao); ?>" name="descricao" class="col-xs-10 col-sm-5" disabled="disabled" />
										</div>
									</div>
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Previs&atilde;o Inicio </label>

										<div class="col-sm-9">
											<input  type="text" id="form-field-1" OnKeyUp="mascaraData3(this);" maxlength="10" name="prev_inicio" class="col-xs-10 col-sm-5"  value="<?php if ($atividade_projeto->prev_inicio != "0000-00-00"){ echo date('d/m/Y', strtotime($atividade_projeto->prev_inicio)); } ?>"/>
										</div>
									</div>
                                    

                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Previs&atilde;o Fim</label>

										<div class="col-sm-9">
											<input  type="text" id="form-field-1" OnKeyUp="mascaraData4(this);" name="prev_fim" class="col-xs-10 col-sm-5"  value="<?php if ($atividade_projeto->prev_fim != "0000-00-00"){ echo date('d/m/Y', strtotime($atividade_projeto->prev_fim)); } ?>" />
										</div>
									</div>
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Prazo:</label>

										<div class="col-sm-9">
											<input  type="text" value="<?php echo $atividade_projeto->prazo; ?>" id="form-field-1" name="prazo" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
                                    
                                    <div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Registro EPE?</label>

												<div class="radio">
													<label>
														<input   <?php if ($atividade_projeto->epe ==1){ echo 'checked="checked"'; } ?> type="radio" name="epe" value="1" class="ace" />
														<span class="lbl"> Sim</span>
													</label>
												&nbsp;&nbsp;
													<label>
														<input  <?php if ($atividade_projeto->epe ==0){ echo 'checked="checked"'; } ?> type="radio" name="epe" value="0" class="ace" />
														<span class="lbl"> Não</span>
													</label>
												</div>
                                          </div>
                                                                                
                                               
                                   
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Descrição </label>

										<div class="col-sm-9">
											<textarea rows="5" id="form-field-1" name="descricao" class="col-xs-10 col-sm-5" required  style="width:100%"/><?php echo $atividade_projeto->descricao;?></textarea>
										</div>
									</div>
                                    

									<div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">PTC? </label>

												<div class="radio">
													<label>
														<input <?php if ($atividade_projeto->ptc==1){ echo 'checked="checked"'; } ?>  type="radio" name="ptc" value="1" class="ace" />
														<span class="lbl"> Sim</span>
													</label>
												&nbsp;&nbsp;
													<label>
														<input <?php if ($atividade_projeto->ptc==0){ echo 'checked="checked"'; } ?> type="radio"  name="ptc" value="0" class="ace" />
														<span class="lbl"> Não</span>
													</label>
												</div>
                                     </div>
                                     
                                     
                                <?php if ($atividade_projeto->ptc==1){ ?>
                                          
                                          <div class="form-group">
												<label class="col-sm-3 control-label no-padding-right" for="form-field-1">Adicionar atividades PTC:</label>

												<div class="radio">
													<link rel="stylesheet" href="<?php echo $this->basePath('chosen-select/chosen.css'); ?>">
												  	<style type="text/css" media="all">
													    /* fix rtl for demo */
													    .chosen-rtl .chosen-drop { left: -9000px; }
												  	</style>
			
         											&nbsp; <select style="width:70%" name="atividade_ptc_id[]" data-placeholder="Selecione uma ou mais atividades" multiple class="chosen-select col-xs-10 col-sm-5" tabindex="8">
		            											<option value=""></option>         
		            											<?php foreach ($atividades_ptc as $atividade_ptc_id => $atividade_ptc){?>         		      													
     																<option value="<?php echo $atividade_ptc_id;?>"><?php echo ($areas[$atividade_ptc['area_id']]).' - '.($atividade_ptc['atividade']); ?></option>
		      													<?php }?>    
          													</select>
												</div>                                           
                                          </div>                                          
                                          <br />
                                          
										<div class="form-group">										
		                                	<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Atividade</label>
			                                <div class="col-sm-9">
	                                
		                                        <table width="100%" id="simple-table" class="table table-striped table-bordered table-hover">
			                                       	  <thead>
			                                         	<tr><th width="80%">Atividades</th></tr>
			                                          </thead>
													 <tbody>
			                                         <?php
			                                         foreach ($atividades_ptc_projeto as $atividade_ptc_projeto){
												   ?>
			                                         <tr><th><?php if(key_exists($atividades_ptc[$atividade_ptc_projeto['atividade_ptc_id']]['area_id'], $areas) && key_exists($atividade_ptc_projeto['atividade_ptc_id'], $atividades_ptc)){ echo $areas[$atividades_ptc[$atividade_ptc_projeto['atividade_ptc_id']]['area_id']].' - '.$atividades_ptc[$atividade_ptc_projeto['atividade_ptc_id']]['atividade']; } ?></th></tr>
                                					<?php } ?>
													</tbody>
		                                        </table>	                                          
											</div>
										</div>
                                          <?php } ?>
                                          
                                          
                                          
                                          
                                          
                                          

									<hr />
                                     
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Inicio da execu&ccedil;&atilde;o</label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" OnKeyUp="mascaraData(this);" maxlength="10" name="dt_inicial" class="col-xs-10 col-sm-5" value="<?php if ($atividade_projeto->dt_inicial !='0000-00-00'){ echo date('d/m/Y', strtotime($atividade_projeto->dt_inicial)); }?>" />
										</div>
									</div>
                                    
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Fim da execu&ccedil;&atilde;o </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" OnKeyUp="mascaraData1(this);" name="dt_final" class="col-xs-10 col-sm-5" value="<?php if ($atividade_projeto->dt_inicial !='0000-00-00'){ echo date('d/m/Y', strtotime($atividade_projeto->dt_final)); } ?>" />
										</div>
									</div>  
									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
			
           <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
           <script src="<?php echo $this->basePath('chosen-select/chosen.jquery.js'); ?>" type="text/javascript"></script>
           
           <script type="text/javascript">
			   function mascaraData(campoData){
			              var data = campoData.value;
			              if (data.length == 2){
			                  data = data + '/';
			                  document.forms[0].dt_inicial.value = data;
			      return true;              
			              }
			              if (data.length == 5){
			                  data = data + '/';
			                  document.forms[0].dt_inicial.value = data;
			                  return true;
			              }
			         }
			
			   function mascaraData1(campoData){
			              var data = campoData.value;
			              if (data.length == 2){
			                  data = data + '/';
			                  document.forms[0].dt_final.value = data;
			      return true;              
			              }
			              if (data.length == 5){
			                  data = data + '/';
			                  document.forms[0].dt_final.value = data;
			                  return true;
			              }
			         }
					 
					  
					 function mascaraData3(campoData){
			              var data = campoData.value;
			              if (data.length == 2){
			                  data = data + '/';
			                  document.forms[0].prev_inicio.value = data;
			      return true;              
			              }
			              if (data.length == 5){
			                  data = data + '/';
			                  document.forms[0].prev_inicio.value = data;
			                  return true;
			              }
			         }
					 
					 
					 function mascaraData4(campoData){
			              var data = campoData.value;
			              if (data.length == 2){
			                  data = data + '/';
			                  document.forms[0].prev_fim.value = data;
			      return true;              
			              }
			              if (data.length == 5){
			                  data = data + '/';
			                  document.forms[0].prev_fim.value = data;
			                  return true;
			              }
			         }		
                       var config = {
                         '.chosen-select'           : {},
                         '.chosen-select-deselect'  : {allow_single_deselect:true},
                         '.chosen-select-no-single' : {disable_search_threshold:10},
                         '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
                         '.chosen-select-width'     : {width:"95%"}
                       }
                       for (var selector in config) {
                         $(selector).chosen(config[selector]);
                       }
                     </script>     
