<?php

echo pack("CCC",0xef,0xbb,0xbf);

$contar = count($atividades_projeto);
 
	$html = "";
    $html .= "<table border='1'>";
    $html .= "<tr>";
    $html .= "<td><b>Atividades</b></td>";
    $html .= "<td><b>Inicio/Fim</b></td>";
	$html .= "<td><b>Inicio da execu&ccedil;&atilde;o</b></td>";
	$html .= "<td><b>Fim da execu&ccedil;&atilde;o</b></td>";
	$html .= "<td><b>EPE</b></td>";
	$html .= "<td><b>PTC</b></td>";
	$html .= "</tr>";
    //$html .= "</table>";
 
foreach($atividades_projeto as $atividade_projeto){
	
	
    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".($atividade_projeto['descricao'])."</td>";
    $html .= "<td>".implode("-",array_reverse(explode("-",$atividade_projeto['prev_inicio'])))." ".implode("-",array_reverse(explode("-",$atividade_projeto['prev_inicio'])))."</td>";
    $html .= "<td>".implode("-",array_reverse(explode("-",$atividade_projeto['dt_inicial'])))."</td>";
    $html .= "<td>".implode("-",array_reverse(explode("-",$atividade_projeto['dt_final'])))."</td>";
	$html .= "</td>";
    if ($atividade_projeto['epe'] == 1){ $epe = 'sim';  }else{ $epe = 'não'; } 

    $html .= "<td>". $epe ."</td>";
    if ($atividade_projeto['ptc'] == 1){ $ptc = 'sim';  }else{ $ptc = 'não'; }
    $html .= "<td>".$ptc."</td>";
    
    $html .= "</tr>";    
}
	$html .= "</table>";
 
$arquivo = 'atividades.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header( "Content-type: application/vnd.ms-excel; charset=UTF-8" );
//header ("Content-type: application/x-msexcel;  charset=iso-8859-1");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );
 
  echo   $html;

?>