
			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Cadastrar novo colaborador</li>
						</ul><!-- /.breadcrumb -->
						
						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Cadastrar colaborador
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">

								<!-- PAGE CONTENT BEGINS -->
								<form class="form-horizontal" role="form" action="" method="post">
									<!-- #section:elements.form -->
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome * </label>

										<div class="col-sm-9">
											<input type="text" id="nome" name="nome" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Email * </label>

										<div class="col-sm-9">
											<input type="email" id="email" name="email" class="col-xs-10 col-sm-5" required  />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Fixo </label>

										<div class="col-sm-9">
											<input type="text" id="tel_fixo" name="tel_fixo" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Móvel </label>

										<div class="col-sm-9">
											<input type="text" id="tel_movel" name="tel_movel" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> CPF * </label>

										<div class="col-sm-9">
											<input type="text" id="cpf1" name="cpf" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
									<!--div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> CNPJ </label>

										<div class="col-sm-9">
											<input type="text" id="cnpj" name="cnpj" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
									
                                    <!--div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Raz&atilde;o Social </label>

										<div class="col-sm-9">
											<input type="text" id="razao_social" name="razao_social" class="col-xs-10 col-sm-5"/>
										</div>
									</div-->                                   
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Vínculo *</label>

										<div class="col-sm-3">

                                            <select name="vinculo" class="form-control" id="vinculo" required >
                                            <option value="">Selecione...</option>
                                             <?php foreach ($tipo_vinculos as $tipo_vinculo){ ?>		  
                                            <option value="<?php echo $tipo_vinculo->id; ?>"><?php echo $tipo_vinculo->descricao; ?></option>
                                            <?php } ?>	 
                                            </select>
										</div>
									</div>
                                    
                                    <!--div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Instituições </label>

										<div class="col-sm-9">
											<input type="text" id="instituicao" name="instituicao" class="col-xs-10 col-sm-5"  />
										</div>
									</div-->
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Curso </label>

										<div class="col-sm-9">
											<input type="text" id="curso" name="curso"  class="col-xs-10 col-sm-5" />
										</div>
									</div>                                                                                                            
                                        
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Pólo </label>

										<div class="col-sm-9">
											<input type="text" id="polo" name="polo" class="col-xs-10 col-sm-5" />
										</div>
									</div>
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Tipo de processo seletivo </label>

										<div class="col-sm-9">
											<input type="text" id="tipo_processo_seletivo" name="tipo_processo_seletivo"  class="col-xs-10 col-sm-5" />
										</div>
									</div>
                                    
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Número do edital</label>

										<div class="col-sm-9">
											<input type="text" id="nu_edital" name="nu_edital" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data de Admissão</label>

										<div class="col-sm-4">
											<input type="date" id="data_admissao" name="data_admissao" class="col-xs-10 col-sm-5"  />
										</div>
									</div>
                                    
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Cargo </label>

										<div class="col-sm-9">
											<input type="text" id="cargo_funcao" name="cargo_funcao" class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" class="col-xs-10 col-sm-2">Função: </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="funcao" name="funcao" class="col-xs-10 col-sm-5"  />
                                        </div>
                                    </div>
                                    
                                    <!--div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">  Status do enquadramento funcional: </label>

										<div class="col-sm-9">
											<input type="text" id="status_enquadramento_funcional" name="status_enquadramento_funcional" class="col-xs-10 col-sm-2"  />
										</div>
									</div>
                                    
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1">  Unidade que o colaborador atuará: </label>

										<div class="col-sm-9">
											<input type="text" id="unidade_lotacao" name="unidade_lotacao" class="col-xs-10 col-sm-5"  />
										</div>
									</div-->
                                    

                                    
                                     <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> perfil *</label>

										<div class="col-sm-9">                                        
                                        
                                         	<?php foreach ($permissoes as $permissao){ ?>	

                                            <div class="radio">
													<label>
													<input type="radio" class="ace" name="permissao" value="<?php echo $permissao['id']; ?>" required />
                                                        <span class="lbl"> <?php echo $permissao['descricao']; ?></span>
													</label>
												</div>
                                                
											<?php } ?>
                                                
                                                
										</div>
									</div>
									
									<?php 
									$url_get_projetos = $this->serverUrl().$this->url('colaborador/get-projetos', array('action'=>'get-projetos', 'id' => ''));
									//$url_get_projetos = str_replace('https', 'http', $url_get_projetos);
									?>
									<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.js"></script>								         
								    <script type="text/javascript">
								    
									$(document).ready(function() {
								        $('#estado').change(function() {
									        var area_id = $('#estado').val();		            
									        var ajax_url = "<?php echo $url_get_projetos; ?>"+area_id+""; 
								    		//var ajax_url = "/uab/convenio/colaborador/get-projetos/"+area_id;
								    		//var ajax_url = "https://localhost/conveniotcezend/colaborador/get-projetos/"+area_id;
								    		//http://localhost/conveniotcezend/colaborador/get-projetos/7
									    	//alert(ajax_url);
								    		
								    		 $.ajax({
								 	            type: "POST",
								 	            url: ajax_url,
								 	            data: "area="+area_id,
								 	            success: function(msg){ 		
								 	                $("#projeto_id").html(msg);
								 	        	}
								 	     	});     	   
								        });
									});
								   
								    </script>

                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Representante</label>

                                        <div class="col-sm-4">

                                            <select name="representante_id" class="form-control" >
                                                <option></option>
                                                <?php foreach ($representantes as $representante){ ?>
                                                    <option value="<?php echo $representante['id']; ?>"><?php echo ($representante['nome']); ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Área *</label>

										<div class="col-sm-4">

                                            <select name="area_id" class="form-control" id="estado" >
                                            <option></option>
                                            <?php foreach ($areas as $area){ ?>		  
                                            <option value="<?php echo $area['id']; ?>"><?php echo ($area['descricao']); ?></option>
                                            <?php } ?>	  
                                            </select>
										</div>
									</div>
                                    
                                     <!--div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Projetos</label>
                                        <div class="col-sm-9">

                                        <div id="projeto">
                                            <select name="projeto_id[]" class="form-control" multiple="multiple" id="projeto_id" ></select>
                                        </div>
                                        </div>
                                     </div-->
                                    
                                      <div class="form-group">
									
									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div>
					
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js"></script>
			<script src="dist/jquery.maskMoney.min.js" type="text/javascript"></script>
			<script>

				$("#cpf").mask("999.999.999-99");
				$("#cnpj").mask("99.999.999/9999-99");	
				
		    	$("#tel_movel").mask("(99) 99999999?9");
		        $("#tel_movel").blur(function(event) {
		    		var verificastring = $(this).val().substring($(this).val().length-1, $(this).val().length);
		            if($(this).val().length == 15){
		              $("#tel_movel").mask("(99) 99999999?9");
		            } else {
		              $("#tel_movel").mask("(99) 99999999?9");
		            }
		        });
		        
		    	$("#tel_fixo").mask("(99) 99999999?9");
		        $("#tel_fixo").blur(function(event) {
		    		var verificastring = $(this).val().substring($(this).val().length-1, $(this).val().length);
		            if($(this).val().length == 15){
		              $("#tel_fixo").mask("(99) 99999999?9");
		            } else {
		              $("#tel_fixo").mask("(99) 99999999?9");
		            }
		        });
			
			</script>
					
