		<!-- /section:basics/sidebar -->
		<div class="main-content">
			<script language="Javascript">
				function confirmacao(id, area_id) {
					var resposta = confirm("Deseja remover esse registro?");

					if (resposta == true) {
						window.location.href = "<?php echo $this->url('area/funcao-delete', array('action' => 'funcao-delete', 'id' => $id, 'area_id' => $id)); ?>" + id;
					}
				}
			</script>
			<div class="main-content-inner">
				<!-- #section:basics/content.breadcrumbs -->
				<div class="breadcrumbs" id="breadcrumbs">
					<script type="text/javascript">
						try {
							ace.settings.check('breadcrumbs', 'fixed')
						} catch (e) {}
					</script>

					<ul class="breadcrumb">
						<li>
							<i class="ace-icon fa fa-home home-icon"></i>
							<a href="<?php echo $this->url('home', array('action' => 'index')); ?>">Home</a>
						</li>

						<li class="active">Funções</li>
					</ul><!-- /.breadcrumb -->


				</div>

				<!-- /section:basics/content.breadcrumbs -->
				<div class="page-content">

					<!-- /section:settings.box -->
					<div class="page-header">
						<h3>
							Funções: <?php //echo $area->descricao; ?>
						</h3>
					</div><!-- /.page-header -->

					<div class="row">
						<div class="col-xs-12">
							
							<p>
								<i class="ace-icon fa fa-angle-double-right"></i>
								<a href="<?php echo $this->url('area/funcao-add', array('action' => 'funcao-add', 'id' => $id)); ?>"> adicionar nova função</a>
							</p>
							
							<!-- PAGE CONTENT BEGINS -->
							<div class="row">
								<div class="col-xs-12">


									<table id="simple-table" class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
												<th>Função</th>
												<th>Carga horária</th>
												<th>Meses</th>
												<th>Colaborador</th>
												<th>opções</th>

											</tr>
										</thead>

										<tbody>
											<?php
											foreach ($areaFuncoes as $funcao) { ?>
												<tr>
													<td><?php echo $funcao['codigo']; ?> - <?php echo $funcao['funcao']; ?></td>
													<td><?php echo $funcao['carga_horaria']; ?></td>
													<td><?php echo $funcao['meses']; ?></td>
													<td><?php echo $funcao['colaborador']; ?></td>

													<td width="10%">
														<div class="btn-group">
															<? //if (($_SESSION['usuario_id'] != 367)|| ($_SESSION['usuario_id'] == 12) || ($_SESSION['usuario_id'] == 11)){ ?>
															<!-- <a href="<?php //echo $this->url('nucleo/edit', array('action' => 'edit', 'area_id' => $area_id, 'id' => $nucleo['id'])); ?>" class="btn btn-xs btn-info">
																<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a> -->

															<!-- <button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo  $funcao['id']; ?>')">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button> -->
															<a href="<?php echo $this->url('area/funcao-delete', array('action' => 'funcao-delete', 'id' => $funcao['id'], 'area_id' => $funcao['area_id'])); ?>">
															<button class="btn btn-xs btn-danger">
																<i class="ace-icon fa fa-trash-o bigger-120"></i>
															</button>
															</a>
															<? //} ?>

															<!--button class="btn btn-xs btn-warning">
																<i class="ace-icon fa fa-flag bigger-120"></i>
															</button-->
														</div>

														
													</td>
												</tr>
											<?php } ?>


										</tbody>
									</table>
								</div><!-- /.span -->
							</div><!-- /.row -->


							<div class="row">
								<div class="col-xs-12">
								</div><!-- /.modal-content -->
							</div><!-- /.modal-dialog -->

						</div><!-- PAGE CONTENT ENDS -->
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.page-content -->
		</div><!-- /.main-content -->