<!-- /section:basics/sidebar -->
<div class="main-content">
	<div class="main-content-inner">
		<!-- #section:basics/content.breadcrumbs -->
		<div class="breadcrumbs" id="breadcrumbs">
			<script type="text/javascript">
				try {
					ace.settings.check('breadcrumbs', 'fixed')
				} catch (e) {}
			</script>

			<ul class="breadcrumb">
				<li>
					<i class="ace-icon fa fa-home home-icon"></i>
					<a href="<?php echo $this->url('home', array('action' => 'index')); ?>">Home</a>
				</li>

				<li class="active">Adicionar nova função</li>
			</ul><!-- /.breadcrumb -->


			<!-- /section:basics/content.searchbox -->
		</div>

		<!-- /section:basics/content.breadcrumbs -->
		<div class="page-content">

			<div class="page-header">
				<h3>
					Adicionar nova função
					<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
				</h3>
			</div><!-- /.page-header -->

			<div class="row">
				<div class="col-xs-12">

					<!-- PAGE CONTENT BEGINS -->
					<form id="nucleo_add" name="nucleo_add" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php //echo $this->url('nucleo/add', array('action' => 'add', 'area_id' => $area_id));
																																							?>" role="form" class="form-horizontal form-label-left">

						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Função:</label>

							<div class="col-sm-9">

								<select class="form-control" name="funcao_id">
									<option></option>
									<?php
									foreach ($funcoes as $funcao) { ?>
										<option value="<?php echo $funcao['id']; ?>"><?php echo $funcao['descricao']; ?> - <?php echo $funcao['carga_horaria']; ?>H - <?php echo $funcao['meses']; ?> meses</option>
									<?php 	} 	?>
								</select>
							</div>
						</div>

						<div class="clearfix form-actions">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn btn-info" type="submit">
									<i class="ace-icon fa fa-check bigger-110"></i>
									Salvar
								</button>
							</div>
						</div>
				</div><!-- /.col -->
			</div><!-- /.row -->
			</form>
		</div><!-- /.page-content -->
	</div>
</div><!-- /.main-content -->