<?php

echo pack("CCC",0xef,0xbb,0xbf);

$contar = count($atividades_ptc);
 
	$html = "";
    $html .= "<table border='1'>";
    $html .= "<tr>";
    $html .= "<td><b>Atividades</b></td>";
    $html .= "<td><b>Inicio/Fim</b></td>";
	$html .= "<td><b>Inicio da execu&ccedil;&atilde;o</b></td>";
	$html .= "<td><b>Fim da execu&ccedil;&atilde;o</b></td>";
	$html .= "<td><b>Situacao</b></td>";
	$html .= "<td><b>Indicador  f&iacute;sico - un</b></td>";
	$html .= "<td><b>Indicador  f&iacute;sico - qtd</b></td>";		
	$html .= "<td><b>Indicador desempenho</b></td>";
    $html .= "</tr>";
    //$html .= "</table>";
 
foreach($atividades_ptc as $atividade_ptc){
	
	
    //$html .= "<table>";
    $html .= "<tr>";
    $html .= "<td>".($atividade_ptc['atividade'])."</td>";
    $html .= "<td>".implode("-",array_reverse(explode("-",$atividade_ptc['inicio'])))." ".implode("-",array_reverse(explode("-",$atividade_ptc['fim'])))."</td>";
    $html .= "<td>".implode("-",array_reverse(explode("-",$atividade_ptc['data_inicio'])))."</td>";
    $html .= "<td>".implode("-",array_reverse(explode("-",$atividade_ptc['data_fim'])))."</td>";
	$html .= "</td>";
		if ($atividade_ptc['status'] ==1){ $status = "conclu&iacute;do"; }
		  if ($atividade_ptc['status'] ==2){ $status = "n&atilde;ao concluido"; }
		  if ($atividade_ptc['status'] ==3){ $status = "parcialmente conclu&iacute;do"; }
		  if ($atividade_ptc['status'] ==4){ $status = "n&atilde;o iniciado"; }		

    $html .= "<td>". $status ."</td>";

    $html .= "<td>".($atividade_ptc['indicador_unid'])."</td>";
    $html .= "<td>".($atividade_ptc['indicador_quant'])."</td>";
    $html .= "<td>".($atividade_ptc['indicador_desempenho'])."</td>";		

    $html .= "</tr>";    
}
	$html .= "</table>";
 
$arquivo = 'atividades.xls';
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header( "Content-type: application/vnd.ms-excel; charset=UTF-8" );
//header ("Content-type: application/x-msexcel;  charset=iso-8859-1");
header ("Content-Disposition: attachment; filename={$arquivo}" );
header ("Content-Description: PHP Generated Data" );
 
  echo   $html;

?>