<?php
use Zend\Session\Container;
$usuario_dados = new Container('usuario_dados');
?>			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('atividade-ptc/delete', array('action'=>'delete', 'id' => ''));?>"+id;
				     }
				}
			</script> 	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Plano de Trabalho</li>
						</ul><!-- /.breadcrumb -->

						
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Plano de Trabalho
							</h3>
						</div><!-- /.page-header -->
						
						<div class="row">
							<div class="col-xs-12">
								
	                            <p>
									
                                    <?php if(in_array('atividade-ptc/add', $usuario_dados->funcionalidades_usuario)){ ?>
                                    <i class="ace-icon fa fa-angle-double-right"></i> <a href="<?php echo $this->url('atividade-ptc/add', array('action'=>'add'));?>"> cadastrar nova atividade</a>
                                    <? } ?>

                                    <?php //if(in_array('atividade-ptc/concluido', $usuario_dados->funcionalidades_usuario)){ ?>
									<!--span style=""><a href="<?php echo $this->url('atividade-ptc/concluido', array('action'=>'concluido'));?>">Atividades concluídas (<?php echo count($atividades_concluidas); ?>)</a></span-->
                                    <? //} ?>
                                    
								</p>
                                
                                 <p>
                                <form class="form-horizontal" role="form" action="" method="get">
                                    Status:
                                    <select name="status">
                                        <option value="">todos</option>
                                        <option <?php if ($_GET['status']=="1"){ echo "selected"; }?> value="1">Concluído</option>
                                        <option <?php if ($_GET['status']=="2"){ echo "selected"; }?> value="2">Não concluído</option>
                                        <option <?php if ($_GET['status']=="3"){ echo "selected"; }?> value="3">Parcialmente concluído</option>
                                        <option <?php if ($_GET['status']=="4"){ echo "selected"; }?> value="4">Não Iniciada</option>
                                    </select> &nbsp;

                                <input type="submit" value="filtrar">
                                </form>
                                </p>
                                
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th width="20%">Área/núcleo</th>
                                                    <th width="35%">Atividade</th>
                                                    <th width="15%">Inicio/Fim</th>
                                                    <th width="10%">Inicio da execu&ccedil;&atilde;o</th>
                                                    <th width="8%">Fim da execu&ccedil;&atilde;o</th>
                                                    <th><small>status</small></th>                                                    
                                              		
                                                    <th width="20%">Opções</th>
                                                    
													
												</tr>
											</thead>

											<tbody>
												<?php
												  foreach($atividades_ptc as $atividade_ptc){ ?>
	  												<tr>													
	                                                    <td>
														<?php  if(key_exists($atividade_ptc['area_id'], $areas)){ echo (($areas[$atividade_ptc['area_id']])); } ?><br />
														<small style="color:#000"><?php echo  $atividade_ptc['nucleo'] ?></small>
														</td>														
	                                                    <td>
														<?php echo ($atividade_ptc['etapa']); ?> - <?php echo ($atividade_ptc['atividade']); ?>
														</td>
														<td><?php echo implode("-",array_reverse(explode("-", $atividade_ptc['inicio']))); ?> / <?php echo implode("-",array_reverse(explode("-", $atividade_ptc['fim']))); ?></td>	
														<td><?php echo implode("-",array_reverse(explode("-", $atividade_ptc['data_inicio']))); ?></td>	
														<td><?php echo implode("-",array_reverse(explode("-", $atividade_ptc['data_fim']))); ?></td>	
	                                                    <td>
	                                                    	<small><?php 
																  if ($atividade_ptc['status'] ==1){ echo "Concluído"; }
																  if ($atividade_ptc['status'] ==2){ echo "Cancelado"; }
																  if ($atividade_ptc['status'] ==3){ echo "Parcialmente conclu&iacute;do"; }
																  if ($atividade_ptc['status'] ==4){ echo "N&atilde;o iniciado"; }		  
																  ?>
															</small>
														</td>

                                              
													<td>
                                                        <?php if(in_array('relatorio-cumprimento-objeto/get-relatorio-cumprimento-objeto', $usuario_dados->funcionalidades_usuario)){ ?>
														     <a href="<?php echo $this->url('relatorio-cumprimento-objeto/get-relatorio-cumprimento-objeto', array('action'=>'get-relatorio-cumprimento-objeto', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-default">
                                                            		<span class="white"><i class="ace-icon fa fa-print bigger-120"></i></span>
                                                            </a>
                                                        <? } ?>

														<!-- <?php if(in_array('relatorio-cumprimento-objeto/get-relatorio-cumprimento-objeto-word', $usuario_dados->funcionalidades_usuario)){ ?>
														     <a href="<?php echo $this->url('relatorio-cumprimento-objeto/get-relatorio-cumprimento-objeto-word', array('action'=>'get-relatorio-cumprimento-objeto-word', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-default">
                                                            		<span class="white"><i class="ace-icon fa fa-file bigger-120"></i></span>
                                                            </a>
                                                        <? } ?> -->

                                                        <?php if(in_array('cumprimento-objeto/add', $usuario_dados->funcionalidades_usuario)){ ?>
                                                            <a href="<?php echo $this->url('cumprimento-objeto/add', array('action'=>'add', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-warning">
                                                                <i class="ace-icon fa fa-list bigger-120"></i>
                                                            </a>
                                                        <? } ?>


                                                            <?php if(in_array('atividade-ptc/edit', $usuario_dados->funcionalidades_usuario)){ ?>
                                                                <a href="<?php echo $this->url('atividade-ptc/edit', array('action'=>'edit', 'id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-info" data-rel="tooltip" title="Editar">
                                                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                                </a>
                                                            <? } ?>


                                                            <?php if(in_array('atividade-ptc/delete', $usuario_dados->funcionalidades_usuario)){ ?>
                                                            <button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo $atividade_ptc['id']; ?>')">
                                                                <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                            </button>
                                                            <? } ?>
	                                                            
                                                    </td>

												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->


								<div class="row">
									<div class="col-xs-12">
									</div><!-- /.modal-content -->
								</div><!-- /.modal-dialog -->
									
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
			</div><!-- /.main-content -->