<?php 

$_SESSION['permissao'] = 8 ;

?>

			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('representante', array('action'=>'delete'));?>/"+id;
				     }
				}

				function marcarTodosChecks(val){

					var boolean_check = $("#funcionalidades_"+val).is(':checked');
										
					$(".funcionalidades_"+val).each(function( index ) {
						  $( this ).prop('checked', boolean_check);
					});
				}
			</script> 	       	
			
				<div class="main-content-inner" style=" border-top: 1px solid #dddddd; }">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Representantes do TCE</li>
						</ul><!-- /.breadcrumb -->

						
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3><?php echo ($perfil_dados->descricao);?> <small>Marque todas as funcionalidades que esse perfil ter&aacute; acesso.<br></small></h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
							
  				<form method="post" action="<?php echo $this->url('perfil-acesso',  array('action'=>'edit', 'id'=> $id));?>" role="form" class="form-horizontal form-label-left">
                   
                  <input type="hidden" name="perfil_id" id="perfil_id" value="<?php echo $id;?>">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">                  
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">

                  <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" value="3" name="funcionalidades_3" id="funcionalidades_3" class="flat" onClick="marcarTodosChecks(this.value);"> <!-- 3/4/5/7 17/18/19/20 21/22/23/24 -->
                        </th>
                        <th class="column-title" colspan="6">Áreas </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="3" <?php if(in_array('3', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Consultar
                         </td>

                         <td class=" ">
                          <input type="checkbox" value="4" <?php if(in_array('4', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Cadastrar
                         </td>

                        <td class=" ">
                          <input type="checkbox" value="5" <?php if(in_array('5', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Editar
                         </td>
						

                         
                      </tr>
                      
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="26" <?php if(in_array('26', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Consultar Submetas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="18" <?php if(in_array('18', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Cadastrar Submetas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="19" <?php if(in_array('19', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Editar Submetas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="20" <?php if(in_array('20', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Remover Submetas
                         </td>
                      </tr>
                      
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="27" <?php if(in_array('27', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Consultar Núcleos
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="22" <?php if(in_array('22', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Cadastrar Núcleos
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="23" <?php if(in_array('23', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Editar Núcleos
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="24" <?php if(in_array('24', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_3">
                          Remover Núcleos
                         </td>
                      </tr>
                      
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" value="8" name="funcionalidades_8" id="funcionalidades_8" class="flat" onClick="marcarTodosChecks(this.value);"> <!-- 8/9/10/25 -->
                        </th>
                        <th class="column-title" colspan="6">Representantes </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="8" <?php if(in_array('8', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_8">
                          Consultar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="9" <?php if(in_array('9', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_8">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="10" <?php if(in_array('10', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_8">
                          Editar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="25" <?php if(in_array('25', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_8">
                          Remover
                         </td>
                      </tr>
                      
                    <thead>
                      <tr class="headings">
                        <th>
                  <input   type="checkbox" value="9" name="funcionalidades_9" id="funcionalidades_9" class="flat"  onClick="marcarTodosChecks(this.value);">
                        </th>
                        <th class="column-title" colspan="6">Colaboradores </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input  type="checkbox" value="67" <?php if(in_array('67', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="68" <?php if(in_array('68', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="69" <?php if(in_array('69', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Editar
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="70" <?php if(in_array('70', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Remover
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="71" <?php if(in_array('71', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Exportar
                         </td>
                      </tr>
                                            
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input  type="checkbox" value="77" <?php if(in_array('77', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Ver projetos do colaborador
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="74" <?php if(in_array('74', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Vincular Projetos ao colaborador
						
                        <input  type="hidden" value="72"  name="funcionalidades[]" >
                         </td>                         
                        <td class=" ">
                          <input  type="checkbox" value="79" <?php if(in_array('79', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar Representante de Projeto do colaborador
                         </td>                         
                        <td class=" ">
                          <input   type="checkbox" value="78" <?php if(in_array('78', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Remover Projetos do colaborador
                         </td>   
                      </tr>
                                            
                      <!--tr class="even pointer">
                        <td class="a-center ">
                        </td>                   
                        <td class=" ">
                          <input  disabled="disabled" type="checkbox" value="" <?php if(in_array('', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Cadastrar atividade mensal
                         </td>   
                        <td class=" ">
                          <input disabled="disabled"  type="checkbox" value="" <?php if(in_array('', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar atividade mensal
                         </td>   
                      </tr-->
                      
                      
                      <thead>
                      <tr class="headings">
                        <th>
                  <input   type="checkbox" value="10" name="funcionalidades_10" id="funcionalidades_10" class="flat"  onClick="marcarTodosChecks(this.value);">
                        </th>
                        <th class="column-title" colspan="6">Participantes </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input  type="checkbox" value="81" <?php if(in_array('81', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="82" <?php if(in_array('82', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="88" <?php if(in_array('88', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Editar
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="89" <?php if(in_array('89', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Remover
                         </td>
                        <!--td class=" ">
                          <input   type="checkbox" value="71" <?php if(in_array('71', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_9">
                          Exportar
                         </td-->
                      </tr>
                      
                      
                      
                                            
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" value="13" name="funcionalidades_13" id="funcionalidades_13" class="flat" onClick="marcarTodosChecks(this.value);"> <!-- 13/14/15/16 -->
                        </th>
                        <th class="column-title" colspan="6">Projetos </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          
                          <input type="hidden" value="29"  name="funcionalidades[]">
                          
                          <input type="checkbox" value="13" <?php if(in_array('13', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Consultar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="14" <?php if(in_array('14', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="15" <?php if(in_array('15', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Editar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="16" <?php if(in_array('16', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Remover
                         </td>
                      </tr>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input  type="checkbox" value="31" <?php if(in_array('31', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Consultar Atividades
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="32" <?php if(in_array('32', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Cadastrar Atividades
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="33" <?php if(in_array('33', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Editar Atividades
                         </td> 
                        <td class=" ">
                          <input type="checkbox" value="34" <?php if(in_array('34', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Remover Atividades
                         </td>
                         
                          <td class=" ">
                          <input type="checkbox" value="80" <?php if(in_array('80', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_13">
                          Exportar atividades
                         </td>
                         
                         
                      </tr>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input disabled="disabled"  type="checkbox" value="" <?php if(in_array('', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar Colaboradores
                         </td>
                        <td class=" ">
                          <input  disabled="disabled" type="checkbox" value="" <?php if(in_array('', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Exportar Colaboradores
                         </td>
                      </tr>
                      
                      <thead>
                      <tr class="headings">
                        <th>
                          <input  type="checkbox" value="57" name="funcionalidades_57" id="funcionalidades_57"class="flat" onClick="marcarTodosChecks(this.value);" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Meus Projetos </th>
                      </tr>
                    </thead>
                                        
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="83"  <?php if(in_array('83', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_57">
                          Ver meus projetos
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="84" <?php if(in_array('84', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_57">
                          Cadastrar relatórios mensais
                         </td>
                         
                         <td class=" ">
                          <input   type="checkbox" value="85" <?php if(in_array('85', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_57">
                          Visualizar relatório mensais
                         </td>
                        
                        <td class=" ">
                          <input   type="checkbox" value="87" <?php if(in_array('87', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_57">
                          Editar relatórios mensais
                         </td>
                        
                        <td class=" ">
                          <input   type="checkbox" value="86" <?php if(in_array('86', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_57">
                          Imprimir Relatório de Atividades
                         </td> 

                         <td class="">
                          <input   type="checkbox" value="93" <?php if(in_array('93', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_57">
                          Assinar relatório
                         </td> 
                      </tr>
                                                
                    <thead>
                      <tr class="headings">
                        <th>
                          <input  value="58"  type="checkbox" name="funcionalidades_58" id="funcionalidades_58" class="flat" onClick="marcarTodosChecks(this.value);">
                        </th>
                        <th class="column-title" colspan="6">Plano de Trabalho </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
						<!-- get submetas -->
                        <input  type="hidden" name="funcionalidades[]" value="40" >
                        <!-- get atividade projetos -->
                        <input  type="hidden" name="funcionalidades[]" value="47" >


                          <input  type="checkbox" value="35" <?php if(in_array('35', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58">
                          Consultar
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="36" <?php if(in_array('36', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58" >
                          Cadastrar Atividade
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="37" <?php if(in_array('37', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58" >
                          Editar Atividade
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="38" <?php if(in_array('38', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58" >
                          Remover Atividade
                         </td>
                            
                      
                       <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
						<!-- get submetas -->
                        <input  type="hidden" name="funcionalidades[]" value="40" >


                          <input  type="checkbox" value="39" <?php if(in_array('39', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58">
                          Consultar atividades concluídas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="42" <?php if(in_array('42', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58" >
                          Cumprimento do Objeto
                         </td>
                        <td class=" ">
                          <input  type="checkbox" value="66" <?php if(in_array('66', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_58" >
                          Imprimir Relatório do cumprimento
                         </td>
                      </tr>
                      </tr>                 
                    </tbody>
                                          
                    <thead>
                      <tr class="headings">
                        <th>
                          <input disabled="disabled"  type="checkbox" value="" name="" id="" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Relatórios </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">                          
                          <input   type="checkbox" value="51" <?php if(in_array('51', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar tela com lista de colaboradores para gerar relatório
                         </td>
                        <td class=" ">
                          <input   type="checkbox" value="53" <?php if(in_array('53', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar lista mensal de relatórios do colaborador
                         </td>
                         
                          <td class=" ">
                          <input  type="checkbox" value="63" <?php if(in_array('63', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Imprimir relatorios UNISELVA
                         </td>
                         
                         <td class=" ">
                          <input  type="checkbox" value="62" <?php if(in_array('62', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Imprimir relatorios CAPE
                         </td>
                         
                         <td class=" ">
                          <input  type="checkbox" value="64" <?php if(in_array('64', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Imprimir relatorios Matriz de responsabilidade
                         </td>
                      </tr>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">                          
                          <input   type="checkbox" value="94" <?php if(in_array('94', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat">
                          relatorio-colaborador/assinar-relatorios-list-colaboradores</td>
                        <td class=" ">
                          <input   type="checkbox" value="95" <?php if(in_array('95', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          relatorio-colaborador/assinar-relatorios-list-projetos                         </td>
                         
                          <td class=" ">
                          <input  type="checkbox" value="96" <?php if(in_array('96', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          relatorio-colaborador/assinar-relatorios-list-relatorios
                         </td>
                         
                         <td class=" ">

                         <input  type="checkbox" value="97" <?php if(in_array('97', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                         relatorio-colaborador/assinar-relatorio-coordenador
                          
                         </td>
                         
                         <td class=" ">
                          
                         </td>
                      </tr>
                      
                      <?php 
                      		$perfil_check = '';
                      		
                      		if(in_array('11', $array_perfis[$id]) && in_array('12', $array_perfis[$id])){
                      			$perfil_check = "checked='checked'";
                      		}
                      		
                      
                      ?>
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" <?php echo $perfil_check; ?> value="11" name="funcionalidades_11" id="funcionalidades_11" class="flat" onClick="marcarTodosChecks(this.value);"> <!--  11/12 -->
                        </th>
                        <th class="column-title" colspan="6">Perfil de Acesso </th>
                      </tr>
                    </thead>
                    
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="11" <?php if(in_array('11', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_11">
                          Consultar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="12" <?php if(in_array('12', $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_11">
                          Editar
                         </td>
                      </tr>

                  </table>
                  
                  
                </div>
              </div>
            </div>
                 
                  
                  <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('home', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
				  </div>
                  
                  </form>
				                  <!-- end project list -->
							</div><!-- PAGE CONTENT ENDS -->
						</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
			</div><!-- /.main-content -->