<?php 

$_SESSION['permissao'] = 8 ;

?>

			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('representante', array('action'=>'delete'));?>/"+id;
				     }
				}

				function marcarTodosChecks(val){

					var boolean_check = $("#funcionalidades_"+val).is(':checked');
										
					$(".funcionalidades_"+val).each(function( index ) {
						  $( this ).prop('checked', boolean_check);
					});
				}
			</script> 	       	
			
				<div class="main-content-inner" style=" border-top: 1px solid #dddddd; }">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Permissões</li>
						</ul><!-- /.breadcrumb -->

						
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3><?php echo ($perfil_dados->descricao);?> <small>Marque todas as funcionalidades que esse perfil ter&aacute; acesso.<br></small></h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
							
  				<form method="post" action="<?php echo $this->url('perfil-acesso',  array('action'=>'edit', 'id'=> $id));?>" role="form" class="form-horizontal form-label-left">
                   
                  <input type="hidden" name="perfil_id" id="perfil_id" value="<?php echo $id;?>">


                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content">
                                <?php foreach ($pai as $v_pai){ ?>
                                <table class="table table-striped responsive-utilities jambo_table bulk_action">
                                    <thead>

                                    <tr class="headings">
                                        <th><label><input type="checkbox" value="<?=$v_pai['funcionalidade_id'];?>"
                                                    <?php if(in_array($v_pai['funcionalidade_id'], $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades_<?=$v_pai['funcionalidade_id'];?>" class="flat" onClick="marcarTodosChecks(this.value);"> <?=$v_pai['funcionalidade_nome'];?></label>
                                        </th>
                                    </tr>

                                    </thead>

                                    <tbody>
                                    <?php

                                    foreach($filhos[$v_pai['funcionalidade_id']] as $filho){
                                    echo '<tr><Td>'; ?>
                                    <label><input type="checkbox" value="<?=$filho['funcionalidade_id'];?>" <?php if(in_array($filho['funcionalidade_id'], $array_perfis[$id])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat funcionalidades_<?=$v_pai['funcionalidade_id'];?>">
                                        <? echo $filho['funcionalidade_nome'].'</label><br>';
                                        echo '</td></tr>';
                                        }

                                        ?>
                                    </tbody>
                                    <? } ?>
                                </table>
                                <br><br>

                            </div>
                        </div>
                    </div>

                 
                  
                  <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('home', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
				  </div>
                  
                  </form>
				                  <!-- end project list -->
							</div><!-- PAGE CONTENT ENDS -->
						</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
			</div><!-- /.main-content -->