<?php 

$_SESSION['permissao'] = 8 ;

?>
			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('representante', array('action'=>'delete'));?>/"+id;
				     }
				}
			</script> 	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Representantes do TCE</li>
						</ul><!-- /.breadcrumb -->

						
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Perfil de Acesso							
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
							
								<!-- start project list -->
				                  <table class="table table-striped projects">
				                    <thead>
				                      <tr>
				                        <th style="width: 15%">Nome</th>
				                        <th style="width: 10%"></th>
				                      </tr>
				                    </thead>
				                    
				                    <tbody>
				                    <?php 
				
										foreach ($perfis as $perfil)
										{
									?>
				                      <tr>
				                        <td><?php echo ($perfil->descricao); ?></td>
				                        <td><a href="<?php echo $this->url('perfil-acesso', array('action' => 'edit', 'id' => $perfil->id));?>" ><i class="fa fa-pencil"></i> Editar </a></td>
				                      </tr>
				                      <?php 
										}
				                      ?>                      
				                    </tbody>
				                  </table>
				                  <!-- end project list -->
							</div><!-- PAGE CONTENT ENDS -->
						</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
			</div><!-- /.main-content -->