
			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Cadastrar novo beneficiário</li>
						</ul><!-- /.breadcrumb -->

						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">

						<div class="page-header">
							<h3>
								Cadastrar beneficiário
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">

                            <!--form id="participante_add" name="participante_add" enctype="multipart/form-data" method="get" action="" role="form" class="form-horizontal form-label-left">
                            <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> CPF </label>

										<div class="col-sm-9">
											<input type="text" name="cpf" class="col-xs-10 col-sm-5"  required /> &nbsp; <input type="submit" value="consultar cpf" />
										</div>
									</div>

                                    </form-->


                      <? echo $msg;?>

								<!-- PAGE CONTENT BEGINS -->
								<form id="participante_add" name="participante_add" enctype="multipart/form-data" method="post" action="<?php echo $this->url('participante/add', array('action' => 'add', 'projeto_id' => $projeto_id)); ?>" role="form" class="form-horizontal form-label-left">
                                <input type="hidden" name="projeto_id" value="<?=$projeto_id;?>" />
									<!-- #section:elements.form -->
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome </label>

										<div class="col-sm-9">
											<input type="text" id="nome" name="nome" class="col-xs-10 col-sm-5" required />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Email </label>

										<div class="col-sm-9">
											<input type="email" id="email" name="email" class="col-xs-10 col-sm-5"  />
										</div>
									</div>



                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Móvel </label>

										<div class="col-sm-9">
											<input type="text" id="tel_movel" name="tel_movel" class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> CPF </label>

										<div class="col-sm-9">
											<input type="text" name="cpf" class="col-xs-10 col-sm-5"  required />
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Data de nascimento</label>

										<div class="col-sm-4">
											<input type="date" id="data_nascimento" name="data_nascimento"  class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Nível de escolaridade</label>

										<div class="col-sm-3">

                                            <select name="nivel_escolaridade" id="nivel_escolaridade" class="form-control" id="nivel_escolaridade" >
                                            <option value="">Selecione...</option>
                                             <?php foreach ($escolaridades as $escolaridade){ ?>
                                            <option value="<?php echo $escolaridade->id; ?>"><?php echo $escolaridade->descricao; ?></option>
                                            <?php } ?>
                                            </select>
										</div>
									</div>






                                      <div class="form-group">


									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div>

			<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js"></script>
			<script src="dist/jquery.maskMoney.min.js" type="text/javascript"></script>
			<script>

				$("#cpf").mask("999.999.999-99");
				$("#cnpj").mask("99.999.999/9999-99");

		    	$("#tel_movel").mask("(99) 99999999?9");
		        $("#tel_movel").blur(function(event) {
		    		var verificastring = $(this).val().substring($(this).val().length-1, $(this).val().length);
		            if($(this).val().length == 15){
		              $("#tel_movel").mask("(99) 99999999?9");
		            } else {
		              $("#tel_movel").mask("(99) 99999999?9");
		            }
		        });

		    	$("#tel_fixo").mask("(99) 99999999?9");
		        $("#tel_fixo").blur(function(event) {
		    		var verificastring = $(this).val().substring($(this).val().length-1, $(this).val().length);
		            if($(this).val().length == 15){
		              $("#tel_fixo").mask("(99) 99999999?9");
		            } else {
		              $("#tel_fixo").mask("(99) 99999999?9");
		            }
		        });

			</script>
