
			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Editar beneficiário</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">

						<div class="page-header">
							<h3>
								Editar beneficiário
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">

								<!-- PAGE CONTENT BEGINS -->
								<form class="form-horizontal" method="post" action="<?php echo $this->url('participante/edit', array('action' => 'edit', 'id'=> $participante->id)); ?>"  role="form" >
									<!-- #section:elements.form -->
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Nome </label>

										<div class="col-sm-9">
											<input type="text" id="nome" name="nome" value="<?php echo $participante->nome; ?>" class="col-xs-10 col-sm-5" required />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right"  for="form-field-1"> Email </label>

										<div class="col-sm-9">
											<input type="email" id="email" name="email" value="<?php echo $participante->email; ?>" class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Fixo </label>

										<div class="col-sm-9">
											<input type="text" id="tel_fixo" name="tel_fixo" value="<?php echo $participante->tel_fixo; ?>" class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Telefone Móvel </label>

										<div class="col-sm-9">
											<input type="text" id="tel_movel" name="tel_movel" value="<?php echo $participante->tel_movel; ?>" class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right"  for="form-field-1"> CPF </label>

										<div class="col-sm-9">
											<input type="text" id="cpf" name="cpf" value="<?php echo $participante->cpf; ?>" class="col-xs-10 col-sm-5"  />
										</div>
									</div>

                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right"  for="form-field-1"> Data nascimento </label>

										<div class="col-sm-9">
											<input type="date" id="data_nascimento" name="data_nascimento"  value="<?php echo $participante->data_nascimento; ?>" class="col-xs-10 col-sm-5"  />
										</div>
									</div>



                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Escolaridade</label>

										<div class="col-sm-4">

                                            <select name="nivel_escolaridade" class="form-control" id="nivel_escolaridade" >
                                             <?php foreach ($escolaridades as $escolaridade){ ?>
                                            <option <?php if ($participante->nivel_escolaridade == $escolaridade->id) { echo "selected"; }?> value="<?php echo $escolaridade->id; ?>"><?php echo $escolaridade->descricao; ?></option>
                                            <?php } ?>
                                            </select>
										</div>
									</div>





                                      <div class="form-group">


									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
                                            </form>
                      
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
			</div><!-- /.main-content -->

			<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js"></script>
			<script src="dist/jquery.maskMoney.min.js" type="text/javascript"></script>
			<!--script>

				$("#cpf").mask("999.999.999-99");
				$("#cnpj").mask("99.999.999/9999-99");

		    	$("#tel_movel").mask("(99) 99999999?9");
		        $("#tel_movel").blur(function(event) {
		    		var verificastring = $(this).val().substring($(this).val().length-1, $(this).val().length);
		            if($(this).val().length == 15){
		              $("#tel_movel").mask("(99) 99999999?9");
		            } else {
		              $("#tel_movel").mask("(99) 99999999?9");
		            }
		        });

		    	$("#tel_fixo").mask("(99) 99999999?9");
		        $("#tel_fixo").blur(function(event) {
		    		var verificastring = $(this).val().substring($(this).val().length-1, $(this).val().length);
		            if($(this).val().length == 15){
		              $("#tel_fixo").mask("(99) 99999999?9");
		            } else {
		              $("#tel_fixo").mask("(99) 99999999?9");
		            }
		        });

			</script-->
