			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Editar núcleo</li>
						</ul><!-- /.breadcrumb -->


						<!-- /section:basics/content.searchbox -->
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
					
						<div class="page-header">
							<h3>
								Editar núcleo
								<!--small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common form elements and layouts
								</small-->
							</h3>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
                            <p>
                            	<a href="<?php echo $this->url('nucleo/consulta', array('action'=>'consulta', 'area_id' => $area_id));?>">Voltar</a>
                            </p>

								<!-- PAGE CONTENT BEGINS -->
								<form id="nucleo_edit" name="nucleo_edit" enctype="multipart/form-data" method="post" onSubmit="validateForm(); return false;" action="<?php echo $this->url('nucleo/edit', array('action' => 'edit', 'id'=> $nucleo->id, 'area_id' => $area_id));?>" role="form" class="form-horizontal form-label-left">
                                         
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Atividade </label>

										<div class="col-sm-9">
											<input type="text" id="form-field-1" name="descricao" value="<?php echo $nucleo->descricao; ?>" class="col-xs-10 col-sm-5" required />
										</div>
									</div>
																		
                                    <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Coordenador</label>

										<div class="col-sm-9">

                                            <select  class="form-control"  name="coordenador_id" >
                                            <option></option>                                            
                                            <?php	
                                            		foreach($coordenadores_nucleo as $usuario_id => $usuario_nome){ 
                                            			if($nucleo->coordenador_id == $usuario_id){		
                                            ?>	  
                                            			<option selected="selected" value="<?php echo $usuario_id; ?>"><?php echo $usuario_nome; ?></option>
                                            			
                                            <?php 		}else{ 	?>	  
                                            
                                            			<option value="<?php echo $usuario_id; ?>"><?php echo $usuario_nome; ?></option>
                                            <?php 		} 
                                            		}
                                            ?>	  
                                            </select>
										</div>
									</div>
									
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Salvar
											</button>
										</div>
									</div>
							</div><!-- /.col -->
						</div><!-- /.row -->
                        </form>
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->
