<?php 

$_SESSION['permissao'] = 8 ;

?>
			<!-- /section:basics/sidebar -->
			<div class="main-content">
            <script language="Javascript">
				function confirmacao(id) {
				     var resposta = confirm("Deseja remover esse registro?");
				 
				     if (resposta == true) {
				          window.location.href = "<?php echo $this->url('atividade-ptc/delete', array('action'=>'delete', 'id' => ''));?>"+id;
				     }
				}
			</script> 	       	      
				<div class="main-content-inner">
					<!-- #section:basics/content.breadcrumbs -->
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="<?php echo $this->url('home', array('action'=>'index'));?>">Home</a>
							</li>

							<li class="active">Plano Estratégico</li>
						</ul><!-- /.breadcrumb -->

						
					</div>

					<!-- /section:basics/content.breadcrumbs -->
					<div class="page-content">
						
						<!-- /section:settings.box -->
						<div class="page-header">
							<h3>
								Plano Estratégico
							</h3>
						</div><!-- /.page-header -->
						
						<div class="row">
							<div class="col-xs-12">
								<? if($_SESSION['permissao'] == 8){ ?>
	                            <p>
									<i class="ace-icon fa fa-angle-double-right"></i>
									<a href="<?php echo $this->url('atividade-ptc/add', array('action'=>'add'));?>"> cadastrar nova atividade</a> |
									<span style=""><a href="<?php echo $this->url('atividade-ptc/concluido', array('action'=>'concluido'));?>">Atividades concluídas (<?php echo count($atividades_concluidas); ?>)</a></span>
                                    
								</p>
                                <? } ?>
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-xs-12">
                                    
                                    
										<table id="simple-table" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<!--th class="center">
														<label class="pos-rel">
															<input type="checkbox" class="ace" />
															<span class="lbl"></span>
														</label>
													</th-->
													<th width="15%">Área/submeta</th>													
                                                    <th width="45%">Atividade</th>
                                                    <th width="15%">Inicio/Fim</th>
                                                    <th width="10%">Inicio da execu&ccedil;&atilde;o</th>
                                                    <th width="8%">Fim da execu&ccedil;&atilde;o</th>
                                                    <th><small>status</small></th>                                                    
                                              		<?php 
                                              		if (($_SESSION['permissao']==8) || ($_SESSION['permissao']==2) ){ ?>
                                                    <th width="15%">Opções</th>
                                                    <?php } ?>
													
												</tr>
											</thead>

											<tbody>
												<?php
												  foreach($atividades_ptc as $atividade_ptc){ ?>
	  												<tr>													
	                                                    <td>
															<?php  if(key_exists($atividade_ptc['area_id'], $areas)){ echo (($areas[$atividade_ptc['area_id']])); } ?><br /><small style="color:#999"><?php  if(key_exists($atividade_ptc['submeta_id'], $submetas)){  echo ($submetas[$atividade_ptc['submeta_id']]['descricao']); } ?></small>
														</td>														
	                                                    <td>
															<?php echo ($atividade_ptc['atividade']); ?>
														</td>
														<td><?php echo implode("-",array_reverse(explode("-", $atividade_ptc['inicio']))); ?> / <?php echo implode("-",array_reverse(explode("-", $atividade_ptc['fim']))); ?></td>	
														<td><?php echo implode("-",array_reverse(explode("-", $atividade_ptc['data_inicio']))); ?></td>	
														<td><?php echo implode("-",array_reverse(explode("-", $atividade_ptc['data_fim']))); ?></td>	
	                                                    <td>
	                                                    	<small><?php 
																  if ($atividade_ptc['status'] ==1){ echo "conclu&iacute;do"; }
																  if ($atividade_ptc['status'] ==2){ echo "n&atilde;o concluido"; }
																  if ($atividade_ptc['status'] ==3){ echo "parcialmente conclu&iacute;do"; }
																  if ($atividade_ptc['status'] ==4){ echo "n&atilde;o iniciado"; }		  
																  ?>
															</small>
														</td>

                                              <?php if (($_SESSION['permissao']==8) || ($_SESSION['permissao']==2) ){ ?>
													<td>
														<div class="hidden-sm hidden-xs btn-group">      
                                                             <a href="<?php echo $this->url('relatorio-cumprimento-objeto/get-relatorio-cumprimento-objeto', array('action'=>'get-relatorio-cumprimento-objeto', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-default">
                                                            		<span class="white"><i class="ace-icon fa fa-print bigger-120"></i></span>
                                                            </a>
                                                   	 <?php 
                                                   	 $_SESSION['usuario_id'] = 0;
                                                   	 		if (($_SESSION['usuario_id']!=367)  || ($_SESSION['usuario_id']==365) || ($_SESSION['usuario_id']==12) ){ ?>
                                                                <a href="<?php echo $this->url('cumprimento-objeto/add', array('action'=>'add', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-warning">
																	<i class="ace-icon fa fa-list bigger-120"></i>
																</a>
																<a href="<?php echo $this->url('atividade-ptc/edit', array('action'=>'edit', 'id'=> $atividade_ptc['id'])); ?>" class="btn btn-xs btn-info" data-rel="tooltip" title="Editar">
																	<i class="ace-icon fa fa-pencil bigger-120"></i>
																</a>
																
	                                                            <?php if ($_SESSION['permissao'] ==8){ ?>
																		<button class="btn btn-xs btn-danger" onclick="confirmacao('<?php echo $atividade_ptc['id']; ?>')">
																			<i class="ace-icon fa fa-trash-o bigger-120"></i>
																		</button>
	                                                            <?php } ?>                                                            
                                                     <?php } ?>
                                                     
														</div>

														<div class="hidden-md hidden-lg">
															<div class="inline pos-rel">
																<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
																	<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
																</button>

																<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                            <?php if (($_SESSION['usuario_id']!=367)  || ($_SESSION['usuario_id']==365) || ($_SESSION['usuario_id']==365) || ($_SESSION['usuario_id']==12) || ($_SESSION['usuario_id']==11)){ ?>
                                                             
                                                              		<li>
																		<a target="_blank" href="<?php echo $this->url('relatorio-cumprimento-objeto/get-relatorio-cumprimento-objeto', array('action'=>'get-relatorio-cumprimento-objeto', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="tooltip-success" data-rel="tooltip" title="Cumprimento do objeto">
																			<span class="blue"><i class="ace-icon fa fa-print bigger-120"></i></span>
																		</a>
																	</li>
                                                                    
																	<li>
																		<a href="<?php echo $this->url('cumprimento-objeto/add', array('action'=>'add', 'atividade_id'=> $atividade_ptc['id'])); ?>" class="tooltip-success" data-rel="tooltip" title="Cumprimento do objeto">
																			<span class="default">
																				<i class="ace-icon fa fa-list bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                    
																	<li>
																		<a href="<?php echo $this->url('atividade-ptc/edit', array('action'=>'edit', 'id'=> $atividade_ptc['id'])); ?>" class="tooltip-success" data-rel="tooltip" title="Editar">
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                    
                                                            <?php if ($_SESSION['permissao'] ==8){ ?>
																	<li>
																		<a href="javascript:func()" onclick="confirmacao('<?php echo $atividade_ptc['id']; ?>')" class="tooltip-error" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																			</span>
																		</a>
																	</li>
                                                                    
                                                            <?php } ?>
                                                                    <?php } ?>
																</ul>
															</div>
														</div>
													</td>
                                                    <?php } ?>
												</tr>
                                                <?php } ?>

												
											</tbody>
										</table>
									</div><!-- /.span -->
								</div><!-- /.row -->


								<div class="row">
									<div class="col-xs-12">
									</div><!-- /.modal-content -->
								</div><!-- /.modal-dialog -->
									
								</div><!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
			</div><!-- /.main-content -->